### ISSUE TITLE
Nicaea sub-system test feedback

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#1029]
As before, I'm making a rather rough list of the issues uncovered at this point. One of the testers left a much more comprehensive feedback document, but not all of these issues are possible to fix at this point. In my opinion, these are the issues we should discuss and/or target before release.

#### Worker Info
Show more data in the working groups overview
Most of these won't require any additional queries. For the ones that do, don't bother unless it's super easy :)
- Show `workerId`
- Show blockheight hired

Nice to haves:
- Show rewards missed
- Show reward frequency/amount
  - Perhaps also "next payment"?
- Show `openingId`

#### Opportunities
This whole thing is kinda broken, but not sure how if it's worth piling resources on it. Still:
- Show `openingId`
- Drop down "All Opportuniries" -> "All Opportunities"

Nice to haves:
- It would be *nice* to have something like the [#/working-groups/admin](https://testnet.joystream.org/#/working-groups/admin) board visible, but not critical.

#### My Roles
Pretty much like the above, in the sense that there is limited info, but not worth investing in.
- Would be nice if you could see your `applicationId` and `workerId` somewhere.
- Consider renaming to "My roles and applications"

#### Create New Proposals
- Some of the new proposals related to hiring a new lead includes a `CurrentBlock` or `ExactBlock`
   - How are the `ExactBlock` limits calculated? Is it current block + grace period?
- For the "Add Working Group Leader Opening"  the page automatically scrolls down to the "Opening schema" field of the page, leaving some input fields above unseen for the user.

#### Existing Proposals List
- Consider adding pagination
- No markdown rendering for previews

#### All Storage Working Group Proposals
- "Storage Wroking Group" -> "Storage Working Group"

# CLI

## Setup
- It would be nice to prompt the user to import and select account(s) at first startup.
- Same applies for selecting endpoint. Choose between `wss://rome-rpc-endpoint.joystream.org:9944/`, `localhost` or `custom`?

Nice to haves:
- Would it be possible to integrate subkey, or some light version of it, in order to allow creating seeds?

## Working groups
- The name implies both `storage` and `curator` working groups can use this. Should the cli make it clear only `storage` works?
- Instead of a purely alphabetical ordering here, perhaps it could be separated between "Storage Providers" and "Storage Provider Lead" commands here?
- When prompted to provide input, the runtime value is displayed. Example from `working-groups:leaveRole`:
  - `Provide value for rationale (0x)`
  - It would be nice to instead display the input value.

There are plenty of other improvements that would be nice to target, but I think it would require too much work compared to the benefits. Both due to the "cost" of performing all the queries, and especially as long as the "final" working groups design is still ongoing.

#### openings
- "Lots" of IDs to deal with in working groups:

```
Wg opening id     Opening id     Type       Stage                               Applications     
5                 7              Worker     Complete (#73092)                   1                
4                 6              Leader     Complete (#65196)                   3                
3                 5              Leader     Accepting Applications (#52173)     1                
2                 4              Worker     Complete (#26021)                   4                
1                 3              Worker     Complete (#24236)                   4                
0                 2              Leader     Complete (#12753)                   3   
```
- Does the concept of `Opening id` exist on chain, or is it just the sum of the openingIds from storage and curator? I would prefer leaving it out regardless, and keep `Wg opening id` only.

#### overview
- Would it be possible to highlight the line if the role (and/or member?) account is imported?

**Comment by Lezek123** [comment]
**DONE:**
- Worker info - `workerId`
- Opening box - `openingId` (in working group module)
- Typos
- "My roles" => "My roles and applications"
- My roles - `workerId` (added a while back)
- It would be nice to prompt the user to import and select account(s) at first startup.
_I'm not sure what you mean by first startup, but I added a suggestion to use `account:import` in case it is detected that no accounts are available (but some is required to execute the command). In case there are accounts available, but none is selected, user is prompted to select one of the accounts (that didn't change but I fixed minor related bug)_
- Choosing api endpoint.
_User will now be prompted for an endpoint as described, if he haven't already set it (and it's required to execute the provided command)_
- CLI: `working-groups:openings` - removed `Opening ID` in the listing
- Worker info - rewards missed
- Worker info - reward policy (frequency, amount, next payment)
- My roles - `applicationId`
- **Glitch:** For the "Add Working Group Leader Opening" the page automatically scrolls down to the "Opening schema"
- Proposals pagination
- Markdown in previews
- `0x` as default value
- `working-groups:overview` - highlight workers for which role keys are available in the CLI
- log current group in the console when executing `working-groups`-family commands

**NOT DONE**

- Making "Admin" tool visible (top menu link?)
_I think would then make sense to also add something like **leadOnly** guard_

**Hard to implement**
- Worker info - blockheight hired
_Will probably require parsing events and I don't think there currently exists any reasonably optimal solution to do this in Pioneer_
- Changing the order of commands in `--help` etc.
_It may be harder to implement, because this is handled by the `oclif` plugin and I'm not sure how much control we can have over this_

**Questions**
> How are the `ExactBlock` limits calculated? Is it current block + grace period?

Those are `currentBlock` + some constant (defined in `validationSchema.js`). Sometimes this constant in based on the maximum period it may take for the proposal to execute (`votingPeriod` + `gracePeriod`), but it can be set to any other number or this can be changed to use the current runtime values instead (shouldn't be hard to implement).

> Would it be possible to integrate subkey, or some light version of it, in order to allow creating seeds?

Do you mean that `account:create` command should print a seed and perhaps there should also be a command to restore account from seed (`account:restore`)?

> The name implies both storage and curator working groups can use this. Should the cli make it clear only storage works?

Actually the `working-groups` command family is already build in such a way, that it should work for any working group in the future. Currently, because there's only one working group, there's a "shortcut", meaning that you can use any `working-groups` command without `--group` or `-g` flag, because it defaults to `storageProviders`, but this is made clear in all related commands help description (ie. `working-groups:overview --help`). I can log the current group in the console when executing `working-groups`-family commands to make it more clear.

> Does the concept of Opening id exist on chain, or is it just the sum of the openingIds from storage and curator?

It exists in the `hiring` module on chain (which is a utility module, while `working-group` and `content-working-group` have their own "wrappers" for `hiring` module entities, so there are always two separate `Opening`s, `Application`s etc.)

**Comment by bwhm** [comment]
> **DONE:**
> 
>  ...

Wonderful!

> **NOT YET DONE** _(but relatively easy to add)_
>
> ...
>
>     * Making "Admin" tool visible (top menu link?)
>       _I think would then make sense to also add something like **leadOnly** guard_

I didn't mean the entire admin board, with `Create new opening` dropdown, checkboxes, and set stage, but letting users see the data in there. Looking at `ID #1`:
<img width="1156" alt="Screen Shot 2020-07-24 at 11 12 43" src="https://user-images.githubusercontent.com/35237943/88376906-99f94b00-cd9e-11ea-823d-83eff474c48b.png">
The interesting part currently not displayed under [opportunities](https://testnet.joystream.org/#/working-groups/opportunities) are shown below:
<img width="1043" alt="Screen Shot 2020-07-24 at 11 14 18" src="https://user-images.githubusercontent.com/35237943/88377029-d2008e00-cd9e-11ea-9c8a-68d84f0f2377.png">

So, it could be:
- having this as an expandable field below the 
- making the opening clickable, and redirecting you to a new page with details for this specific listing
- adding it to the opening block

The latter *seems* by far the easiest, so you would end up "cramming" it in at the bottom below:

<img width="1256" alt="Screen Shot 2020-07-24 at 11 18 24" src="https://user-images.githubusercontent.com/35237943/88377651-d7120d00-cd9f-11ea-82ee-9d5f7df937fd.png">

How much time would you guesstimate that takes? If there as an easier approach, I'm all ears :)
 

>     * `0x` as default value
>       _This is caused by the fact that the field is of `Bytes` type and that's how the default value looks when converted with `.toString()`. We still want to preserve those default values for other types, but perhaps there is some easy workaround._

The confusion here is that people will think they have to type in something starting with `0x`. My guess is that people would think they need to write either "0x I want to store data", or that they have to convert from string to hex...

> **Hard to implement**
> 
>     * Worker info - blockheight hired
>       _Will probably require parsing events and I don't think there currently exists any reasonably optimal solution to do this in Pioneer_

Then we skip it :)
 
>     * Changing the order of commands in `--help` etc.
>       _It may be harder to implement, because this is handled by the `oclif` plugin and I'm not sure how much control we can have over this_

Then just leave as is, you've added a note about it anyway!
 

> **Questions**
> 
> > How are the `ExactBlock` limits calculated? Is it current block + grace period?
> 
> Those are `currentBlock` + some constant (defined in `validationSchema.js`). Sometimes this constant in based on the maximum period it make take for the proposal to execute (`votingPeriod` + `gracePeriod`), but it can be set to any other number or this can be changed to use the current runtime values instead (shouldn't be hard to implement).

I thought so. It defaults to currentblock anyway, so  let's leave it then!

> > Would it be possible to integrate subkey, or some light version of it, in order to allow creating seeds?
> 
> Do you mean that `account:create` command should print a seed and perhaps there should also be a command to restore account from seed (`account:restore`)?

Yes. This is by no means critical at this point, but would be a nice feature, as there is currently no way (?) to extract the mnemonic seed from the json.


> > The name implies both storage and curator working groups can use this. Should the cli make it clear only storage works?
> 
> Actually the `working-groups` command family is already build in such a way, that it should work for any working group in the future. Currently, because there's only one working group, there's a "shortcut", meaning that you can use any `working-groups` command without `--group` or `-g` flag, because it defaults to `storageProviders`, but this is made clear in all related commands help description (ie. `working-groups:overview --help`). I can log the current group in the console when executing `working-groups`-family commands to make it more clear.

That would be a nice touch!

> > Does the concept of Opening id exist on chain, or is it just the sum of the openingIds from storage and curator?
> 
> It exists in the `hiring` module on chain (which is a utility module, while `working-group` and `content-working-group` have their own "wrappers" for `hiring` module entities, so there are always two separate `Opening`s, `Application`s etc.)

Ok, then I understand. Although it may be useful to in some cases, I think it's more likely to cause confusion to display it.


Excellent work btw :)
It's a bit of a chore to create an opening atm, but I guess that's what the guides are for. Perhaps we can add a link to the helpdesk whenever help/usage is displayed? Not existing atm, but it would be:
`https://github.com/Joystream/helpdesk/tree/master/tools/cli`
