### ISSUE TITLE
Bug: weird listings on Pioneer opportunities page

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#1109]
The opportunities page shows a few curator opportunities listed as unknown. Their block number seems to update to the latest block number. As far as I know of there are no actual curator openings at the moment, nor was one started recently.

https://testnet.joystream.org/#/working-groups/opportunities
![image](https://user-images.githubusercontent.com/50830161/89275692-a78eba80-d653-11ea-8bf7-10f67ac9eff1.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703511860184) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
There seem to be 9 openings when querying via `contentWorkingGroup.curatorOpeningById` (https://testnet.joystream.org/#/chainstate) and 9 are also shown on https://testnet.joystream.org/#/working-groups/opportunities/curators

What changed recentlly is that previously openings that had invalid `human_readable_text` were just not displayed at all, but since this was a little confusing they are now displayed as `Unknown`, which means that those don't have to be new, they could have just been "hidden" before.

Perhaps from the UI perspective it looks kind of bad though and could definitely be imporved (ie. by setting some default headers/description)

**Comment by mochet** [comment]
Thanks, that clarifies the situation a bit more. I think the curator lead may have to begin review and then close them.

edit - the curator lead has closed all of these so this is now a non-issue
