### ISSUE TITLE
Prevent Layout From Jumping Around When Placeholders are replaced

### ISSUE THREAD

**Issue by fcescob** [Joystream/joystream#1504]

**Comment by kdembler** [comment]
Originally, this was a simple fix - layout jumps were happening because the height of the placeholder was slightly lower than the height of some loaded video previews so a carousel would gain height once loading finishes.

However, later on, an additional issue arose that can be described as the same behavior - the Carousel component fails to properly fit elements once the loading is finished. The error is visible only for a fraction of a second, and then it works okay. It seems as if the gliderjs tries to fit all the newly loaded elements into the old width of carousel (the sum of widths of the placeholders) so the widths can appear squeezed. This will need some further investigation.

The current remedy is `min-width: ${MAX_VIDEO_PREVIEW_WIDTH};` set for video previews in `VideoGallery.tsx` - thanks to that the change in width is minimal and the layout jump isn't as noticeable. After this issue is solved, the specified line of CSS should be removed.

<img width="497" alt="Screenshot 2020-11-09 at 12 32 00 PM" src="https://user-images.githubusercontent.com/12646744/98536150-97582e00-2287-11eb-862d-a59d235bb364.png">
