### ISSUE TITLE
update handle validation method to limit to: `^[a-z0-9_]+$`

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#17]
regex package from crates.io doesn't compile to wasm, so need alternative or roll our own.

**Comment by siman** [comment]
The safest regex for usernames/handles/slugs would be `^[a-z0-9_]+$`. They should be in lowercase because of the same reason why domain names are in lowercase.

Imagine all these domains are different:
apple
Apple
aPPle
APPLE
...

if they are handled as different names then we are in trouble with squatters.
