### ISSUE TITLE
Rename proposal engine variable

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#1827]
`current_constitutionality_level` currently is easy to confuse with actual constitutionality, got me lost for a while, better just make more direct into `nr_of_council_confirmations`.

**Comment by 96RadhikaJadhav** [comment]
@bedeho Could you please assign this issue to me and also direct me to the file path where it can be changed?

**Comment by bedeho** [comment]
Hi, this work would have to be on the `olympia`  branch in the proposal engine in the `runtime-modules` directory here

https://github.com/Joystream/joystream/tree/olympia/runtime-modules/proposals/engine

**Comment by 96RadhikaJadhav** [comment]
@behedo I might didn't get the question. Could you please explain a little more about it if possible. Because in the runtime modules directory I could not find anything as current_constitutionality_level.  My understanding was to rename current_constitutionality_level to nr_of_council_confirmations wherever mentioned in the files. Please correct me if I'm wrong.
