### ISSUE TITLE
Council - ensure rewards paid as expected over long run

### ISSUE THREAD

**Issue by ondratra** [Joystream/joystream#2012]
I created a new test that simply runs 1000 elections in a row, and it discovered a bug - after some number of cycles (13), something unexpected happens, and a cycle simulation fails. A test can be seen in a PR below.

The problem is probably not related to the recent move of business logic from `on_finalize()` to `on_initialize()`. Even old code failed after a couple of cycles, but it failed earlier (only 5 cycles).

Find a source of this bug. Also, ensure in the test that all rewards are paid for the elected council members properly (after 1000 elections).

**Comment by conectado** [comment]
From what I've gathered for now the failure in the test is the following 

```
---- tests::council_many_cycle_rewards stdout ----
thread 'tests::council_many_cycle_rewards' panicked at 'assertion failed: `(left == right)`
  left: `[CouncilMember { staking_account_id: 5003, reward_account_id: 5003, membership_id: 5003, stake: 11000, last_payment_block: 1001, unpaid_reward: 1000 }, CouncilMember { staking_account_id: 5000, reward_account_id: 5000, membership_id: 5000, stake: 11000, last_payment_block: 981, unpaid_reward: 0 }, CouncilMember { staking_account_id: 5001, reward_account_id: 5001, membership_id: 5001, stake: 11000, last_payment_block: 981, unpaid_reward: 0 }]`,
 right: `[CouncilMember { staking_account_id: 5003, reward_account_id: 5003, membership_id: 5003, stake: 11000, last_payment_block: 981, unpaid_reward: 0 }, CouncilMember { staking_account_id: 5000, reward_account_id: 5000, membership_id: 5000, stake: 11000, last_payment_block: 981, unpaid_reward: 0 }, CouncilMember { staking_account_id: 5001, reward_account_id: 5001, membership_id: 5001, stake: 11000, last_payment_block: 981, unpaid_reward: 0 }]`', runtime-modules/council/src/mock.rs:760:9
```

Where the difference is:

**Actual:**
```
CouncilMember { staking_account_id: 5003, reward_account_id: 5003, membership_id: 5003, stake: 11000, last_payment_block: 1001, unpaid_reward: 1000 }
```

**Expected:**
```
CouncilMember { staking_account_id: 5003, reward_account_id: 5003, membership_id: 5003, stake: 11000, last_payment_block: 981, unpaid_reward: 0 }
```

To understand this we need to understand that the `BudgetRefillPeriod` is 1000, the `ElectedMemberRewardPeriod` is 10, the `BudgetRefillAmount` is 1000, the `IdlePeriodDuration` is 27 and a full cycle is 84 blocks.

Also, the starting budget of the council is 0 and it's only refilled at the 1000th block and the test starts at block 1.

So when the firsts 12 election cycles everything works as expected since the budget is 0 no reward is paid and all unpaid reward is discarded upon council re-election. But the 12th iteration only works because the comparison between the expected and final council is done before the idle period pass, since here is the problem. 

This happens during the idle period of the 12th iteration, when it begins(block 981) all `last_payment_block` and `unpaid_rewards` are reset(the council has just been elected), in the block 991 rewards are meant to be paid but fails for the first time, so no update on the `CouncilMember`, in the block 1000 the budget is refilled to 1000 and in the block 1001 reward is meant to be paid again, here for the first council member 2000 (20 blocks with 100 reward per block) should be paid however we only have 1000 budget so only one councilor is paid half its reward and the `last_payment_block` and `unpaid_reward` is updated while this doesn't happen to the other councilors because reward is depleted again. And this fails in the 13th iteration because at the start of that cycle we check how the idle period of the last iteration finished.

To test this if we increase the `BudgetRefillPeriod` to something much greater than 1000 the test passes(although this is not the correct solution). Also, if we see the budget refill to 2000 the councilor that is not like we expected read as:
```
CouncilMember { staking_account_id: 5003, reward_account_id: 5003, membership_id: 5003, stake: 11000, last_payment_block: 1001, unpaid_reward: 0 }
```

**Comment by ondratra** [comment]
The problem was caused by bad test expectations. The test itself is now fixed, and elected members are rewarded as they are supposed to.
