### ISSUE TITLE
Multiple choice text proposals

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2177]
Currently a text proposal is made and it can either be approved or rejected. This is simple but effective since the outcome is effectively binding.

In situations that require very quick actions, it may be worth looking at the idea of a multiple choice text proposal. Although we can use the forum and other platforms to try and gather opinions, these have no immediate sense of urgency and it is unclear how you would prevent spamming/sybil attacks.

It may be that the council needs to take "one of `n`" actions in the immediate future. This may be the situation when it comes to things like urgent runtime upgrades. Before the runtime is coded and tested, it would need to have some guidance on what parameters/changes it actually has, and the `Multiple choice text proposal` might solve this.

**Comment by traumschule** [comment]
@bedeho @bwhm i second this suggestion. In the latest election of the [deputy council secretary](https://blog.joystream.org/sumer-kpis/#33.I-3) we saw a nearly 50:50 split between two proposals ([869](https://pioneer.joystreamstats.live/#/proposals/869), [867](https://pioneer.joystreamstats.live/#/proposals/867)) and it is likely that in the future we run into similar situations and lock-ups between two or more parties.

Incidentally for positions like these it can significantly delay work or lead to situations where it stays open until the end of a term. Since this issue did not receive attention yet and it is unlikely that the proposal system will support multiple-choice votes soon remedies are to either 
- fill the position in the previous term not knowing if the applicant will be elected to the council, or 
- resort to third-party decision making tools like a discord bot etc.

**Comment by bedeho** [comment]
I totally buy the need for this, in fact there was another idea for unlocking this kind of stuff by generalizing the proposal engine in #150 , however, the time for these kinds of deep changes have really passed at this point, we cannot execute on that in time for mainnet, so this will have to be one of those post-mainnet blue sky ideas.
