### ISSUE TITLE
Validator was rejected with empty session key after one era

### ISSUE THREAD

**Issue by podlodkin** [Joystream/joystream#2179]
My member name is "svdeshka" (Membership ID	590):
https://testnet.joystream.org/#/members/svdeshka

My Stash address is  5GHKN9YKah1zH16kd2Hm1LszZoLNNLXjDu671cEXMskqDEHt

My Controller address is 5Fy968cGEpNhBq5Rih22Gh8Hm9WADBxgWEVmEGXZyWcyPDmC

I created validator by this https://github.com/Joystream/helpdesk/tree/master/roles/validators instruction. 

My validator was added to waiting list. In next era (3536) I became a validator. After one era I was rejected from validators.
My session key was empty. I was setting session key again and I became a validator again (era nr = 3540). And again after one era I was rejected with empty (!) session key. 

I found, that after my account became as validator I had losing my session key and I need to recreate it. This is error.

Workaround: I set the session key at once after I became validator and after then I did not rejected from validators. Proof:  3548 - 3557 eras.

**Comment by bwhm** [comment]
Hey,

Sorry for the late reply here!
I can see that your session key is stored on chain now, but I can't confirm whether your session key has been/was injected to your node. I have never encountered this issue before...

> And again after one era I was rejected with empty (!) session key.
May I ask where you saw this error?

One option is be that your node wasn't yet fully synchronized when you started validating. Syncing would likely take >24h from when you started the node. Can this have been the case?

**Comment by podlodkin** [comment]
Hello!

> I can see that your session key is stored on chain now, but I can't confirm 
> whether your session key has been/was injected to your node. I have never encountered this issue before...

I have another interesting situaction now:
- I was validator for some epochs. 
- My node was running. 
- Unfortunately, I'm lost my Validator status. I think it was happening when validators count has increased by 10 - till 90.
I don't know - It is correct or no. Just info. 

> One option is be that your node wasn't yet fully synchronized when you started validating. 
> Syncing would likely take >24h from when you started the node. Can this have been the case?

Hm, I can't answer 100% correct - I didn't check this status before every trying. 
But, if my node was not fully synced, why I can get in Validators list for one hour? Is it possible?

**Comment by bwhm** [comment]
Hey,

> I have another interesting situaction now:
> 
>     * I was validator for some epochs.
> 
>     * My node was running.
> 
>     * Unfortunately, I'm lost my Validator status. I think it was happening when validators count has increased by 10 - till 90.
>       I don't know - It is correct or no. Just info.

I think you're right, I can no longer find you as waiting or validator.
If you lost your spot because someone staked more, that would have pushed you "out", so most likely you got kicked for one reason or another. If you go [here](https://testnet.joystream.org/#/staking/actions), you'll most likely see that next your accounts, you can again click `validate` (indicating that you have yourself, or been "forced" to, stop/stopped) instead of `stop`.

I'm not sure you actually need to delete/move and replace, but it's probably the safest.

> Hm, I can't answer 100% correct - I didn't check this status before every trying.
> But, if my node was not fully synced, why I can get in Validators list for one hour? Is it possible?

If it wasn't that is exactly what would happen. Since you announced your intention to be a validator through our endpoint (which is synced), the network wouldn't know that your node wasn't...

So if you are synced now (you can check for your node by name here (), you can start validating again! If not, wait until it is synced :)

Closing this now, as I'm fairly sure that was the problem :)

---

If that doesn't solve the problem, and you have injected multiple session keys to your node, try:

- stop your node
- clear the keystore of your validator node (if on linux, it will be in `~/.local/share/joystream-node/chains/joy_testnet_4/keystore` (ie. delete/rename(move) the directory, or all of the files inside it)
- start your node up again
- generate new keys (`curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "author_rotateKeys", "params":[]}' http://localhost:9933`
- then go to pioneer, change your session keys again there
- start validating again

(this is probably not necessary, but if all else fails...)

**Comment by podlodkin** [comment]
> I think you're right, I can no longer find you as waiting or validator.

It is interesting, because my actual statuss (for some hours or days) is "Waiting" (see screenshot):

![image](https://user-images.githubusercontent.com/23024800/108701366-87035080-7510-11eb-8694-b8d418fa0c6a.png)

**Comment by bwhm** [comment]
Yeah, now I see you under waiting!
I couldn't find you there earlier when I wrote, so I assumed you'd gotten "booted". If you've been there all this time, I guess it's "just" the load on the endpoint that made it so I couldn't find you :(

Regardless, it's (unfortunately) just a case of too little stake... Currently, almost 20k is needed...
