### ISSUE TITLE
Olympia metadata standards

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2245]
# Background

In the Olympia runtime there are numerous extrinsics where raw metadata is associated with some action, where the metadata is not validated or stored in the chain, but is supposed to comply with some social convention around its structure and off-chain semantics. Here are some examples

1. Council candidacy note: https://joystream.gitbook.io/joystream-handbook/governance/council#submit-candidacy-note
2. Working group opening description: https://joystream.gitbook.io/joystream-handbook/governance/working-groups#creating-an-opening-for-workers (it is here incorrectly described as human readable, it should be _structured off-chain metadata_).
3. Working group application description: https://joystream.gitbook.io/joystream-handbook/governance/working-groups#apply-on-opening (same issue here)
4. Working group status: https://joystream.gitbook.io/joystream-handbook/governance/working-groups#set-status
5. Membership metadata: https://github.com/Joystream/joystream/issues/2244

and probably many other places.

# Proposal

We require a clear way to describe, in a human readable way, what the standard is for this metadata, and we have settled for ProtocolBuffers so far, both because its easy to read, and also because its auto generates serialization/deserialization code which is very space efficient, unlike say JSON. We have already successfully done this for the content directory in `Sumer`, see resulting library in Typescript here

- https://www.npmjs.com/package/@joystream/content-metadata-protobuf/v/1.0.0

We need to come up with such a set of standards for all relevant fields in the Olympia runtime. Importantly, the the current Pioneer 2 design wireframe is the authoritative guide on what the designers so far have assumed should be in this metadata, so it should be used as the primary guide. In fact, using the Pioneer wireframes as the starting point for enumerating all metadata standards that are needed is probably best, as there may be a few different uses in Pioneer that have to be implemented using the same extrinsic in the runtime.

Once the all the formats have been proposed and reviewed, we need to figure out how the typescript code can be consumed by both CLI, Pioneer 2, integration tests, etc.

**Comment by Lezek123** [comment]
### Metadata structure

**Opening:**

I think some of the data that is part of the wireframes is no longer relevant for Olympia, ie.:

- Time to begin (we don't have `Waiting to begin` openings anymore)
- Applications limit (there is no enforcement of this by the runtime)

Other data that is part of the design and can be included in the schema:

- Expected opening duration (ie. in days)
- Hiring limit (as the above, it won't be enforced by the runtime, but can serve as a useful singal from the opening creator)
- Opening description
- Application process details (bullet points, I think it's useful to have them separated from description, so the design can be more flexible)
- Application form definition
   This one will define the questions that the applicants need to answer when applying to the opening.
    Previously for this purpose we had a json structure like:
    ```
    sections: [
        {
            name: "About you",
            questions: [
                {
                    "title": "What's your name",
                    "type": "text"
                },
                {
                    "title": "What makes you a good candidate?",
                    "type": "textarea"
                }
            ]
        }
    ]
    ```
    Which seems to be consistent with the wireframes

I think the protobuf messages in that case can be something like:
```
message OpeningMetadata {
  string description = 1;
  uint32 hiring_limit = 2;
  uint32 expected_duration = 3;
  repeated string application_details = 4;
  message ApplicationFormSection {
    string title = 1;
    message ApplicationFormQuestion {
      string question = 1;
      enum InputType = {
        TEXT = 1;
        TEXTAREA = 2;
      }
      InputType type = 2;
    }
    repeated ApplicationFormQuestion = 2;
  }
  repeated ApplicationFormSection application_form_sections = 5;
}
```

**Application:**
The metatada here will just consist of answers to the application form questions as deined by the opening.
It should be enough to have a message like:
```
message ApplicationMetadata {
  repeated string answers = 1;
}
```
The answers can be matched to questions by array indexes (excess answers can be ignored)

**Working groups status:**
According to the design we need a structure like:
```
{
    description: "Storage proviers are responsible for...",
    about: "Some more information...",
    status: "Scheduled downtime", // Possibly an enum?
    statusDetails: "We expect a storage infrastructure downtime between 1 PM and 8 PM CET due to...",
}
```
This is updateable metatada which implies optional fields, ie.:
```
message WorkingGroupStatusMetadata {
  optional string description = 1;
  optional string about = 2;
  optional string status = 3; // Can also be an enum if we only want a limited set
  optional string status_message = 4;
}
```

**Candidacy note:**
Based on wireframes it should be something like:
```
{
    // "Candidates" page (box)
    coverImage: "http://example.com/image.png",
    header: "Make Joystream great again",
    bulletpoints: [
        "More JOY for everyone",
        "Stop the censorship",
        "Uploads without limits"
    ],
    // Candidate preview
    description: "
        # H1
        Lorem ipsum dolor sit atmet

        # H2
        Lorem ipsum dolor sit atmet
    "
}
```

**_The `coverImage` should probably be an asset instead of an uri, but I think we would need some special handling for this in the runtime?_**
This one is also updateable, so the example protobuf message may be:
```
message CouncilCandidacyNoteMetadata {
  optional string header = 1;
  optional repeated string  bullet_points = 2;
  optional string cover_image = 3; // or uint32 - asset index
  optional string description = 4;
}
```

**Membership:**

```
message MembershipMetadata {
  optional string name = 1;
  optional string avatar_uri = 2; // or uint32 - asset index
  optional string about = 3;
}
```

### Reusability

I think for this purpose we can temporarly recreate a library similar to https://www.npmjs.com/package/@joystream/content-metadata-protobuf/v/1.0.0 on Olympia branch and then merge it with/into the Sumer's protobuf library

**Comment by bedeho** [comment]
Lol, flawless, great job!

**Comment by Lezek123** [comment]
I noticed later that there is a working group opening creation form wireframe which assumes slightly different metadata structure, ie.:
- `Application details` are an md-formatted text instread of array of bullet points
- There is an additional `shortDescription` field
- The structure of application form does not include the division into `sections`

Therefore the **Opening** metadata that would be more consistent with the wireframes would be:
```
message OpeningMetadata {
  string short_description = 1;
  string description = 2;
  uint32 hiring_limit = 3;
  uint32 expected_duration = 4;
  string application_details = 5;
  message ApplicationFormQuestion {
    string question = 1;
    enum InputType = {
      TEXT = 1;
      TEXTAREA = 2;
    }
    InputType type = 2;
  }
  repeated ApplicationFormQuestion application_form_questions = 6;
}
```
