### ISSUE TITLE
WIP: Council Secretary

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2322]
WIP.

**Comment by mochet** [comment]
One usage of this role could maybe be to give privileged access to some sort of on-chain document that allows them to provide a log of significant events + future events.
This would be especially useful during upgrade events, so that there is a trusted voice providing updates from off-chain sources regarding any downtime of services. Though proposals or the forum could theoretically be used for coordinating this, this could be one use of the council secretary role if it is ever reconsidered in the future.

This could also be used in scenarios where there is some data loss or any unpredictable event.

I would say that this role should be elected via some proposal type so that it can't easily be abused.

~This could be very similar to the depreceated Alert system from Bitcoin: https://en.bitcoin.it/wiki/Alert_system~ (the council blog can already perform this far better, so this example is needless, however maybe some possibility of recording prominent events would still be useful.
