### ISSUE TITLE
Channel Payouts

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2365]
# Background

We will have large number of channels when in production, on the order of 1-10M. These need to be paid out regularly on the basis of judgements about the value they bring to the system, for example informed by how much traffic they drive to Gateways. Let us leave aside the question of what method will be used to determine what each channel should be paid, and just focus on the question of how to make such payments of given quantities of JOY to given channels.

Specifying the full set of payments through one or more extrinsics will be infeasible, due to the sheer size, and also because of the tremendous computational cost of making all the payments in anything like a timely manner. This means we must instead consider some sort of pull based payment scheme.

# Proposal

Let `{c_1,...,c_N}` denote the ids of all channels that are owed some reward outstanding, and let `p_i` denote the `JOY` payment to the channel with id `c_i`.  Let `m_i` denote some hash commitment over some report or manifest which explains, in terms of some standard, the basis for the relevant `p` value on `c_i` . Let `commitment` be some sort of [accumualtor](https://en.wikipedia.org/wiki/Accumulator_(cryptography)) over the set `F = {(c_1, p_1, m_1), ...., (c_N, p_N, m_N)}`. It just needs to allow efficient membership proofs in terms of `N`, so Merkle trees could perhaps be a good starting point. Now, payments are made by having a value for `commitment` placed in the content directory, and the full set `F` placed in the storage of the council or the relevant working group. This `F` will allow any channel to construct the full proof required to cash out. There should probably also be some runtime value `S` which bounds how much can be cashed out for, so as to prevent an attack from introducing absurdly large `p_i` values. When the cumulative cashout amount for a given commitment reaches `S`, no further cashout is allowed until the value is raised. 

To prevent a channel from cashing out more than once on the same commitment and in order for the process of setting `p` values from one commitment to the next not having to take account of who has cashed out or not at what time, we do as follows.

- the semantics of this value `p` should be `total amount of money earned by this channel`
- each cashout is for the maximum allowed amount, and the cumulative value `v` of all prior successful cashouts in a given channel is stored in the channel
- it is only possible to cashout if  `v <= p-MIN_CASHOUT`, where `MIN_CASHOUT>0` is some runtime constant for the smallest value cashout allowed, at which point the cashed out value is `p-v` and the new value of `v` is set to `+= p-v`.

Note that nothing prevent `p` from actually decreasing from one commitment to the next, something which would reflect the channel having previously gotten credit for fraudulent activity.

_Note: this explanation is quite rough, but it gives a good idea for how one can proceed._

**Comment by dobertRowneySr** [comment]
# Proposed solution

-   Payment request is delegated to channels owners (that is every channel is responsible for claiming his own rewards).
    Channel `c` claiming `p` `JOYs` will query runtime providing `(c, p, m)` with `m` hash
    commitment of some human-readable text justifying the amount `p` for `c`.
-   Runtime is tasked only with verifying that the amount claimed by every channel is truthful and allowing
    the transfer of value towards the channel to happen only once.


<a id="orgd803ef0"></a>

# Implementation


## Payment information

Suppose payments element `c, p, m` are in a set `F = { (c_1,p_1,m_1), ..., (c_n, p_n, m_n) }`. Responsibility
for modifying `F` is left to the Council who will notify (via transaction) the Runtime with a commitment value
on `F`, obtained by means of merkle trees. 
What is left for the Runtime is update its on-chain value for such commitment using the following extrinsic:

    pub fn update_commitment (
    	origin,
    	new_commitment: // new value for the commitment
    ) -> DispatchResult;  

So that after making sure that `origin` is one of the council members' accounts the new value for the commitment will
be updated to `new_commitment`.



## Channel cashout

In order for a channel `c` to successfully claim amount `p` on the basis of `m` he will need to provide
Runtime with a merkle path and element `el = (p,c,m)` so that membership of `el` to `F` can be correctly
verified.
In order to do so we add a field `v` to `ChannelRecord`. Information is then stored on chain and can be accessed using `ChannelById` map.
It can be only updated by the following extrinsic: 

    pub fn update_channel_reward (
    	origin,
    	el: &PullPaymentElement, // element (p,c,m) 
    	merkle_path: &[Hash], // merkle path 
    	index: usize // index at which el is expected to be found
    ) -> DispatchResult;  

Suppose channel c is claiming payment `p,c,m`. In order for a channel to cashout use the following steps:

1.  The current total cashed out value for c can be accessed by `prev_v = <ChannelById>::get(c).v` . Let `x = p - prev_v` the amount owed to the channel `c`.
2.  Verification step:
    -   check that `origin` is the reward account for the channel `c`
    -   `p < S` In order to prevent attacks
    -   `x >=MIN_CASHOUT`
    -   proof membership of `el` by using the `merkle_path` provided and the commitment on F stored on chain
3.  After the verification process has been successful a new cr = CannelRecord\`   is created with the `v` field augmented by `x` and `cr` is placed back into the `ChannelbyId` map
4.  Transfer of `JOY` s is made toward `origin` with value `p - v_prev`



# Progress status

-   [X] implement code that verifies membership of `el` to `F`
-   [x] implement origin verification for both extrinsics
-   [x] testing
-   [ ] Implement final transfer of value from mint account to channel owner

**Comment by dobertRowneySr** [comment]
@bedeho, Is the threshold value `S` specific for the particular channel `c` ? Because if that is true then it makes sense to add an extra field to the `ChannelRecord` struct for the value for `S` and also an extra extrinsic in order to raise it. 

As for the final transfer of value I would proceed as follows: 
1. create new mint with capacity `S`
2. transfer `p` to the channel reward account
3. delete the mint

Any problem with this approach?

**Comment by bedeho** [comment]
>  Is the threshold value `S` specific for the particular channel

No, it is global.

> As for the final transfer of value I would proceed as follows:

What do you mean by _mint_ in this context?

**Comment by dobertRowneySr** [comment]
> What do you mean by mint in this context?

The way `p` is financed is by minting new tokens. I looked into the token_mint pallet and it seems to me that the way tokens are minting is create a new pallet_token_mint::Mint first, mint the desired quantity and then transfer value to the reward account.

The value for `S` is stored on chain, I have added an extrinsic in order to raise it.
Should also the value for `MIN_CASHOUT` be stored on chain too? Should it also be a predefined constant?

**Comment by bedeho** [comment]
>  looked into the token_mint pallet and it seems to me that the way tokens are minting is create a new pallet_token_mint::Mint

These mints are going away - so lets avoid introducing a new one, also, they are meant to be long lived, so they would not be created and destroyed on a per token creation basis. I suggest you instead look into introducing a new function for doing this minting on the module trait (called `Trait`) in the content directory. It should be able to fail, for example because some high level budget constraint prevents the minting. Then we can later in the runtime decide how to implement it. One option would be to constraint the minting by the council mint.

> The value for S is stored on chain

By stored on chain, I assume you mean in storage, so its mutable. If so, that is fine.

> Should also the value for MIN_CASHOUT be stored on chain too? 

Same answer as prior one.

**Comment by dobertRowneySr** [comment]
>  One option would be to constraint the minting by the council mint.

I didn't fully understand this part. Does it mean that I need to use the `council_mint` (in the governance pallet) in order to mint the token and then proceed with the transfer?

**Comment by dobertRowneySr** [comment]
Like in the `governance::council pallet` I added a mint just for reward minting purpose.
The code is basically the same as in the council runtime module I have just added a non zero initial capacity in order to successfully run the unit tests

**Comment by bedeho** [comment]
No, we do not want a new mint, read above.
 - mints are going away.
 - `I suggest you instead look into introducing a new function...`
 
 > I didn't fully understand this part. Does it mean that I need to use the council_mint (in the governance pallet) in order to mint the token and then proceed with the transfer?
 
 Yes, but you dont need to consider this now, because this would be in the runtime itself, not the content directory module specifically.

**Comment by dobertRowneySr** [comment]
So this means that for the moment I can add a function like `transfer_reward` to the  `Module<T>` implementation and leave it unimplemented?

**Comment by bedeho** [comment]
Yes.
