### ISSUE TITLE
Broken channel 0

### ISSUE THREAD

**Issue by igrexac** [Joystream/joystream#2388]
All videos from the channel 'Channel(0) - uBqMC_MffqCLg-aWm8jSo' (https://play.joystream.org/video/0) are not played. 
I am the leader of content curators. When i try to hide videos and channels, messages are displayed:

![image](https://user-images.githubusercontent.com/83884918/117553112-3653bc00-b058-11eb-8897-a78846ad9aa5.png)
For example inside page https://play.joystream.org/video/1789 in the video code: 

`<video class="vjs-tech" id="vjs_video_19863_html5_api" tabindex="-1" role="application" playsinline="playsinline" poster="https://eu-central-1.linodeobjects.com/joystream/1.png" src="https://rome-rpc-endpoint.joystream.org/asset/v0/5FyzfM2YtZa75hHYCAo5evNS8bH8P4Kw8EyXqKkC5upVSDBQ"></video>` , the video tag leads not to the video, but to the message: _invalid ipfs path: invalid path "/ipfs/undefined": invalid CID: expected 1 as the cid version number, got: 31965309853_

Since the channel with ID 0, I believe that the error is related to the new network.

**Comment by Lezek123** [comment]
After some investigation I found out that:
- There is no actual entity of id `0` in the current runtime, the channel with id `"0"` seems to have been created via direct insert to query node database (probably during some custom initialization)
- Videos that have been added to this channel (in the query node database), like video `1656`, are actually part of a failed `Transaction` extrinsic (https://testnet.joystream.org/#/explorer/query/32678). Those videos don't have any actual schema support added (which is correctly shown in the CLI), because this part of the batch transaction was never executed by the runtime.

It seems to me that Channel `0` only exists in the query node database to faciliate the handling of batch (`Transaction`) content directory operations by the query node.

When such transaction is handled by query node, all entities are initially created with some default, meaningless values. In case of videos, those include relationship to channel with id `0`: https://github.com/Joystream/joystream/blob/master/query-node/mappings/content-directory/default-schemas.ts#L220

When `AddSchemaSupportToEntity` part of the transaction fails - those default values (including relationship to channel `0`) are never overriden, that's why there are a few videos "assigned" to this channel.

Also if the channel `0` didn't exist in query node database, the processor would fail to insert the initial, "dummy" videos because of database constraints, that's probably why the channel had to be inserted manually to the database during query node initialization.

The issue doesn't seem to be related to the CLI then, but the way query node handles transactions.
Perhaps @mnaamani or @metmirr can shed some more light on this issue.

**Comment by Lezek123** [comment]
While investigating the failed transaction in https://testnet.joystream.org/#/explorer/query/32678 I actually noticed another issue.
Because the video title is in Russian, the number of bytes in the title is different from the number of characters, ie.:
```
console.log(api.createType('Text', 'Келколовский карьер. Вейксёрфинг. 24 июня 2020').toU8a().length)
```
Results is: `81`

While
```
console.log(api.createType('Text', 'aaaaaaaaaaaa aaaaaa. aaaaaaaaaaa. 24 aaaa 2020').toU8a().length)
```
_(same number of characters, but only ASCII ones)_
Results in: `47`

This is probably the reason why the validation of this title passed in the CLI, but failed in the runtime.

**Comment by mnaamani** [comment]
We now store video title in protobuf metadata so I think this issue is resolved in new runtime.
