### ISSUE TITLE
Editable and non-editable threads/posts inconsistencies

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2393]
In the current Olympia forum runtime implementation there seems to be some incosistencies with editable/non-editable forum posts/threads functionality:

1. Posts can be made non-editable be either using `add_post` extrinsic with `editable` set to `false` or by creating editable post and removing it with `hide` flag set to `false` (implying the post should still be visible after removal), while threads and thread initial posts can only be made non-editable when deleted (which requires sending at least 2 extrinsics).

**The issue:** We cannot create a thread (along with its initial post) that is non-editable to begin with, like we can with regular posts (added through `add_post`)

1. Posts that were made non-editable through `delete_posts` with `hide` flag set to `false` are substracted from thread's posts counter (`thread.number_of_posts`), while posts that are non-editable from the beginning are still counted and **cannot be removed**.

**The issue:** `thread.number_of_posts` represents neither the number of editable posts, nor the number of non-editable posts in the thread. It also doesn't represent the sum of both. It represents the _number of posts minus the number of posts "removed" via `delete_post` extrinsic regardless of `hide` flag_

1. Making a post or thread non-editable effectively prevents it from beeing hidden (removed) or censored.

**The issue:** Non-editable posts will stay visible forever as there would be no way to censor or remove them. They also won't risk any slashing, which overall seems like a good oportunity for spammers.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201710956221949) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
> We cannot create a thread (along with its initial post) that is non-editable to begin with, like we can with regular posts (added through add_post)

Keep in mind that the reason non-editability exists as a concept is because we want to represent that something is no longer mutable in the chain, since that is the only way to keep the state size managable over time. Hence, being a non-editable thread means there is no footprint of it in the storage of the chain. This further means that one could not make posts to the thread, because the runtime would not be able to check whether the thread was in an archvid category, or itself properly deleted, etc. As a result, there is no meaningful reason to allow creating a thread which is non-editable out of the gate, this would be a thread no-one could post to.

> The issue: thread.number_of_posts represents neither the number of editable posts, nor the number of non-editable posts in the thread. It also doesn't represent the sum of both. It represents the number of posts minus the number of posts "removed" via delete_post extrinsic regardless of hide flag

This is precisely correct, but is not a real problem. There is a case for renaming it and having better comments I guess, but the actual number of posts in a thread is something the query node will be able to represent.

> The issue: Non-editable posts will stay visible forever as there would be no way to censor or remove them. They also won't risk any slashing, which overall seems like a good oportunity for spammers.

This is a good observation. I think blockchain history spamming is not so problematic, but it is problematic for the consumer experience on the forum. Rather than removing ability to create non-editable posts, as that raises the cost of a critical platform feature, we could allow moderation to also operate on non-editable posts. So the chain would basically no try to validate the correctness of hiding non-editable posts, it would just do a basic check that the hiding action refers to to a post id which is within scope of the given thread, and then the query node would opt to update its visibility status based on this.

What do you think?

**Comment by Lezek123** [comment]
> Keep in mind that the reason non-editability exists as a concept is because we want to represent that something is no longer mutable in the chain, since that is the only way to keep the state size managable over time. Hence, being a non-editable thread means there is no footprint of it in the storage of the chain. This further means that one could not make posts to the thread, because the runtime would not be able to check whether the thread was in an archvid category, or itself properly deleted, etc. As a result, there is no meaningful reason to allow creating a thread which is non-editable out of the gate, this would be a thread no-one could post to.

That seems reasonable, but considering the `create_thread` extrinsic also creates the initial post, perhaps there should be at least a way to make this first post non-editable?

> So the chain would basically no try to validate the correctness of hiding non-editable posts, it would just do a basic check that the hiding action refers to to a post id which is within scope of the given thread, and then the query node would opt to update its visibility status based on this.
What do you think?

I did have something similar in mind, but since we can leave it up for the query node to validate whether the post can actually be hidden/removed then why would we need to distinct between editable/non-editable posts to begin with? We could leave it up for the query node to validate other actions like post update or post reaction too and we wouldn't need to keep any information about posts in the runtime state at all.

**Comment by bedeho** [comment]
Lets wait and see until someone cries.
