### ISSUE TITLE
WIP: Sumer feedback for Atlas

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#2408]
ref issue #2062 

Not sorted in terms of priority as of now. I assume many of these can, will and should be done in flight (or even dropped entirely), if fixing it would delay the release.

#### Channel View
1. Channel description not visible.
2. No support for channel categories. Is this out of scope, or WIP?
3. No options in general to "order by":
   - Category (if supported)
   - Followers
   - Popularity (total vid views, or average views pr vid?)
4. Underneath the channels, the number of uploads (eg. `4 uploads`) is displayed. This includes unsuccessful uploads, and (I assume) hidden and censored videos. When you click that channel, less than 4 will appear.
5. Channels without videos should be put at the bottom of the list by default, or just not visible. (Including channels where all vids are hidden or censored)
6. Show creation date (somewhere)
**EDIT**
I realized the query node is still logging the time an extrinsic is processed, rather than the blocktime, so I guess that's a good reason not to show that.

#### Video View
1. More options to "order by":
   - Most viewed
   - Allow toggling more than one category?

#### Studio
1. `Joystream Studio` button is a bit hidden away. Consider making it more accessible.
2. No category support in Channel creation.
3. When sending transactions via Atlas studio
	- `External signer app` - `0.2 JOY trasaction Request` - JOY doesn't have decimals and there is no transaction fee.
![Screen Shot 2021-05-02 at 15 58 05](https://user-images.githubusercontent.com/35237943/118664641-ee6c2c00-b7f1-11eb-8003-9bc3abd33e37.png)
4. When starting a new upload, the page is scrolled down *after* the title of the video, you have to scroll up to see/edit the title.
   - Having "default" title say `New draft` makes it unclear that this is not just what you are doing, but where you edit the title.
5. Once the video has been added, and page moves to `Step 2` it is not immediately obvious that there is a video successfully chosen.
   - Consider showing a thumbnail from the video, the full size of the uploaded file, or something else to indicate what you have started.
![Screen Shot 2021-05-18 at 14 19 27](https://user-images.githubusercontent.com/35237943/118664246-9a614780-b7f1-11eb-839c-eaece334b7d9.png)
6. After sending the upload transaction, you get (great) helpers (see below):
   - If possible, say asset 1/2 (thumbnail) completed...
   - If possible, provide the user videoId (or "just" the URL) right away. It's not obvious that it'll work well due to processing delays, but worth considering
<img width="417" alt="Screen Shot 2021-05-18 at 14 24 43" src="https://user-images.githubusercontent.com/35237943/118665241-72261880-b7f2-11eb-9fed-13471bdf0377.png">

7. **EDIT** These helpers don't expire, and the lost/regained network connection is hard to "click away"
8. No error messages beside `Asset upload failed`. All this is probably only needed if it fails, but some of it _could_ be useful regardless.
    - Display the ID and/or URL of the SP you tried uploading to
    - Display which assets failed, and perhaps also their `contentId`
9. Is the re-upload feature planned for Atlas?
    - I was able to re-upload the video with the CLI, but not the other assets. I assume it's due to cropping, so it won't be possible for users to do this manually.
    - A temporary solution could be to give the user instructions for how to re-upload with the CLI:
         - Save (or ask to save) the cropped images, and a new .json with the correct paths.
         - Say that the command `joystream-cli content:reuploadAssets -i=/path/to/generated.json` will do the trick

#### Signup
1. Handle validation only triggers after first fail
   - trying `Some-handle` doesn't trigger a warning first. After it fails when you submit, it will then trigger immediately

Finally, I should have added that studio is really great!

**Comment by kdembler** [comment]
Thanks for a comprehensive list!

**Channel View:**

2: Channel categories were decided to be out of scope for the release

3: We could add some sorting/filtering there but we would need to have something to filter by. Currently we cannot do queries regarding channel views/follows as the data is fragmented and not available in the query node (only in Orion). So for the time being I guess we should ignore that and come back once we can sort/filter based on something

4: Good catch, created https://github.com/Joystream/atlas/issues/640 for that

1,3,5,6: Those refer to the viewer side, and aren't really a part of this release. The points are valid though, so created an issue for the designers to take a look at: https://github.com/Joystream/atlas/issues/641

**Video view**
Like with channel follows/views, video views are only available in Orion as well so we won't be able to use that for now. Regarding toggling more categories, I think that makes sense but that's also something the designers are working on atm so I guess let's see what they come up with.

**Studio:**
1. Yep, that's a good point, we already have an issue for that: https://github.com/Joystream/atlas/issues/538
2. Yep, we don't support that
3. That's just an illustration in the background. However, @mnaamani pointed that out as well so I reached out to the designers for an updated illustration and we will show something different there
4. Could you elaborate a bit more on that? I don't think I understand. When I open the video drawer, I can see `New draft` right away. Regarding your other point on whether `New draft` is a good choice, if you don't change it and select a video file, the title will automatically update to that so I think it possibly solves the problem? Let me know what you think
5. I see your point. We used to display the video title there in the first iteration but got rid of it since we wouldn't be able to display that for edited videos. Unfortunately we don't have any thumbnail to show there. Created https://github.com/Joystream/atlas/issues/642 for that
6. I don't think we will be able to solve that completely right away, but created https://github.com/Joystream/atlas/issues/644 for now. We will later make some changes to how we handle those notifications that should enable us to do more
7. https://github.com/Joystream/atlas/issues/644 and https://github.com/Joystream/atlas/issues/645
8. We'll try to add some details for that: https://github.com/Joystream/atlas/issues/646
9. Reuploading should work in general. Videos for sure, regarding images, it's more complicated, as you said. We currently have cropping handling in progress. We plan to save crop data and automatically crop the image for the user again once they re-select it. If you start an upload and for example refresh the page before it finishes, you should be able to reupload in `My uploads`

**Signup:**
Yep, our validation strategy is to only validate once user hits submit, to not show errors prematurely. It may be a bad UX to show you errors while you're still typing. We use that app-wide, so I think let's leave it as it is for now

Glad you like Studio, I love it too!

**Comment by bwhm** [comment]
>> When starting a new upload, the page is scrolled down after the title of the video, you have to scroll up to see/edit the title.
>> Having "default" title say New draft makes it unclear that this is not just what you are doing, but where you edit the title.


> Could you elaborate a bit more on that? I don't think I understand. When I open the video drawer, I can see New draft right away. Regarding your other point on whether New draft is a good choice, if you don't change it and select a video file, the title will automatically update to that so I think it possibly solves the problem? Let me know what you think

Yes, so the issue was when you are in your channel, and click the "new upload" button (side note: the url `edit-video` may be a little confusing), I was saying that you get this view:
![Screen Shot 2021-05-20 at 12 00 35](https://user-images.githubusercontent.com/35237943/118959905-07e0b580-b963-11eb-98b5-f8daa4de2bd3.png)

However, when I tried reproducing it now, I realized it only applies if you've started an upload, and scrolled down, then cancelled it (possibly also if you complete an upload, and starts a new one) in that session. If you log out of studio, and back in, or open a new tab, it "starts at the top" again.  So with that in mind, NVM :)

> Regarding your other point on whether New draft is a good choice, if you don't change it and select a video file, the title will automatically update to that so I think it possibly solves the problem? Let me know what you think

I noticed that - and it certainly takes it from a _very_ small issue to an even smaller. The shading also helps, but perhaps it would be better to add a white frame around it, so it's in line with the other fields that requires, or takes, inputs from the user.

I'm happy to leave it as is, it is a minor thing at best!

> Reuploading should work in general. Videos for sure, regarding images, it's more complicated, as you said. We currently have cropping handling in progress. We plan to save crop data and automatically crop the image for the user again once they re-select it. If you start an upload and for example refresh the page before it finishes, you should be able to reupload in My uploads

That's great to hear! I'll make sure to try that :)

---

Wrt to the rest of your comments, I agree and have no further comments.

This really is a giant leap for us!
