### ISSUE TITLE
Channel Payouts - extended

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#2420]
This issue is an extension of issue #2365.
Let 
* `c_i` = channel id that is owed some reward outstanding 
* `p_i` = cumulative amount of JOY owed to channel with id `c_i`
* `m_i` = hash commitment that justifies the amount `p_i` for `c_i` 

## GOALs
* pull based payment scheme 

## TO RESOLVE
1. full `F` stored Off-Chain ?
2. is `F` of fixed size ? Can it be augmented/reduced (eg. channel `c_{N+1}` claims payments)?
3. I didn't understand why using large values for p can cause problems
4. p increased whenever a channel is owed some JOYs ?
5. Shouldn't also v_i for channel `c_i` be into `F = {(c_i,v_i, p_i, m_i)} i = 1..N`?

## PROPOSALs
1. I would add `v` to the struct Channel to keep track of cumulative value of
	all successful cashout for the Channel.  
2. hash commitment of F stored On-chain (practically speaking I would modify the 
	Store trait for the Content module in order to store for example the Merkle root)
4. every cashout `x` must be in the interval `[MIN_CASHOUT, S]`
5. when a channel cashes out x JOYs `v += x`
6. When `v == p` channel doesn't claim payments any longer

**Comment by bedeho** [comment]
> full F stored Off-Chain ?

Yes, F is very large and not constrained. If we could process it on-chain directly, we could just iterate it and do all of the payouts. For the sake of simplicty, you do not need to make assumptions about how exactly `F` comes about, or how people who want to claim payouts will recover F and reconstruct their merkle branch.

> is F of fixed size ? 

No, F will most likely grow monotonically in size, and most likely each new version will be a subset of the next, as a channel will keep getting referenced in every F if it is ever first included. However, you should not need to make an explicit assumption about this last point for your proposal to work.

> why using large values for p can cause problems

The way `p` is financed is by printing new tokens when a channel tries to cash out. This issuance is at the expense of all other token holders, and if a mistake or attack is made, it could badly compromise the system if someone picked a sufficiently large value. So we must constrain this.

> p increased whenever a channel is owed some JOYs ?

Yes, for the same channel, the value will likely increase over time as a result of them earning more. However, the blockchain cannot enforce this on every new `F` set, because it precisel cannot iterate through this large data set and verify that all ps are not decreasing. There is some benefit to this, because you may in fact want to reduce the p for a channel which is found to have used some fradulent activity, like faking views or something.

> Shouldn't also v_i for channel c_i be into F = {(c_i,v_i, p_i, m_i)} i = 1..N?

No, you will have to think a bit more about this.
