### ISSUE TITLE
Query node - test scenarios

### ISSUE THREAD

**Issue by ondratra** [Joystream/joystream#2448]
The list of query node tests:

- [ ] general
  - [ ] check that `createdAt`/`updatedAt` values corresponds with block timestamp in (all) tests
  - [ ] check that all entities have their IDs deterministic (every time the processor restarts, they stay the same)
  - [ ] check weird UTF-8 characters (e.g. null character) in places where it could cause problems (probably only membership module)
  - [ ] check at least one scenario with invalid metadata (should be gracefully overcome)
  - [ ] check at least one scenario with an inconsistent state (should throw an error)

- [ ] channel category
  - [ ] CRUD
  - [ ] cover photo & avatar
    - [ ] add
    - [ ] change
- [ ] channel
  - [ ] CRUD
- [ ] video category
  - [ ] CRUD
- [ ] video
  - [ ] CRUD
  - [ ] license & language
    - [ ] create
    - [ ] update
    - [ ] remove
  - [ ] thumbnail & media
    - [ ] add
    - [ ] change
  - [ ] change video metadata (`mediaMetadata`)
- [ ] curator group
  - [ ] CRUD
  - [ ] group status change
  - [ ] add curator to group
  - [ ] remove curator from group
- [ ] membership
  - [ ] CRUD
  - [ ] membership buy
  - [ ] screened member add
  - [ ] set root account
  - [ ] set controller account
  - [ ] sudo calls
    - [ ] for CRUD
    - [ ] for MemberUpdatedAboutText/MemberUpdatedAvatar/MemberUpdatedHandle
    - [ ] for UpdateMembership
- [ ] storage
  - [ ] content added; the owner is:
    - [ ] member
    - [ ] channel
    - [ ] council
    - [ ] working group
  - [ ] content accepted
  - [ ] content removed
- [ ] bootstrap
  - [ ] members
    - [ ] check proper entry method
  - [ ] workers
  - [ ] check no duplicates are created when the processor restarts

**Comment by bedeho** [comment]
Thanks for this!

1. I think the `createdAt` & `updatedAt` are going to be deprecated, and should not be relied on. I thought we already had moved away from this. At any rate, don't test for this. Otherwise the  `general` section looks good.
2. What does it mean when you say `CRUD`, which I assume stands for create-read-update-delete, but then you ahve other specific actions listed that already would be covered by this?
3. Drop coverage of `membership` & `storage`, they are not part of replaced in upcoming releases, and they seem to be working well enough now.
4. I did not understand `bootstrap`, what code are you testing here, and what do each case mean?

**Comment by ondratra** [comment]
Ok.

ad 2) Yes, I used `CRUD` for general create-read-update-delete. The specific actions mentioned are meant to test edge cases that made a problem in the past. For example, `Video` has generic `CRUD` and then operations for `License` and `Language` that are extracted from protobuf. Thus, typically updating and deleting is a bit more complex and can use regression prevention.

ad 4) When the processor is started for the first time, initial sets of members and workers that are present in runtime at genesis/runtime upgrade (I don't know the exact workings of this, but in general, there are records that don't come from events).

**Comment by bedeho** [comment]
Ok, so lets skip 4) for now, because we have already done it, and the code will 100% change for the next testnet.
