### ISSUE TITLE
Requirements: Video NFT

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2481]
A video NFT, or vNFT, refers to the ownership relationship between a member and a video. These requirements are meant to be the basis upon which a specification can be made.

- A video either has a single edition vNFT issued, or not, and it is issued by the channel owner.
- One can only issue a vNFT if one is not already issued for the same video.
- A vNFT issued through an auction, specifically a open ascending-bid auction (english auction), which starts at some predefined time in the future. If the auction fails, the issuance of the vNFT fails, and the channel owner is free to try again in the future.
- An issuance auction which is not yet active, or for which there are no active bids, can be cancelled by the channel owner.
- A vNFT can be issued to any member directly, at no cost, including to the channe owner him or herself.
- A vNFT has rich metadata, announced during issuance, which will follow some social standard that the chain does not validate.
- A vNFT may have a royalty condition set at the time of issuance, which states what % of secondary market transactions will go to the channel revenue.
- A vNFT owner can give, at no cost, transfer ownership to any other member.
- A vNFT owner can start an auction, in the same way as described above, and proceeds from this auction may be subject to the royalty condition above.
- There can be an unlimited number of bidders in any action, so no iteration should be needed.
- There can be an unlimited number of total active auctions at any time.
- There can be an unlimited number of vNFTs.
- Must be compatible with some promising NFT standard that attempts to work with Polkadot interop.
- Must be possible to move vNFT ownership into third party parachains which have their own business logic for managing the owner, and thus possibly updating the ownership

**Comment by mochet** [comment]
Do auctions have a minimum price or a fixed fee? For example, if I have a video I want to auction as a vNFT, do I need to pay the network some predefined fee (or to be held as stake) -- like 100 JOY? I ask because without this I would assume the auctions would be filled with very low quality, spammy submissions and requiring some reasonable fee (preferably one that burns the tokens) would help to ensure some minimum quality of submissions is upheld.

Also, would a working group be responsible for moderating this area? I can see one method of spamming being putting videos up for auction with stupidly high prices repeatedly so that the videos get views or attention. Maybe one way of solving both potential issues is to have the stake required be proportional to what the auction is set at, for example a 10% stake might be required of whatever the auction value is.

**Comment by bedeho** [comment]
> Do auctions have a minimum price or a fixed fee? For example, if I have a video I want to auction as a vNFT, do I need to pay the network some predefined fee (or to be held as stake) -- like 100 JOY? I ask because without this I would assume the auctions would be filled with very low quality, spammy submissions and requiring some reasonable fee (preferably one that burns the tokens) would help to ensure some minimum quality of submissions is upheld.

There has to be an opening price yes, which acts as the floor. I def. think there should be a platform fee, independent of this, which is tunable by governance, hard-coding 0 is sort of silly.

 > Also, would a working group be responsible for moderating this area
 
I think having platform wide discovery based on highest min-price does not make sense, which is sort of what you are alluding to. You may want to look at things by highest bid, or even highest sale, but moderation won't solve the fundamental problem of fake buying in that case anyway, so I think its best to just leave that out, and trust that discovery will primarily be driven by creators driving traffic through their calls to action.

**Comment by iorveth** [comment]
Closed https://github.com/Joystream/joystream/pull/2512
