### ISSUE TITLE
Forum: clean-up pay-off storage inconsistency 

### ISSUE THREAD

**Issue by iorveth** [Joystream/joystream#2540]
Clean-up pay-off for both threads and posts stored inside each individual struct instance, but currently it's effectively the same "default" - `ThreadDeposit`, `PostDeposit` values for all threads and posts across `forum` and there are no means to change it via extrinsic, proposal, etc.

```rust
pub struct Thread<ForumUserId, CategoryId, Moment, Hash, Balance> {
    ....
    /// Pay off by deleting
    pub cleanup_pay_off: Balance,
   ...
}
```

### Question
 Is it reserved for that kind of additional features or we should remove `cleanup_pay_off` on entity level?

**Comment by bedeho** [comment]
I think this was a mistake.

**EDIT**
Now I recall, the reason for this was that if the deposit amounts would be changed with a runtime upgrade, then it was important to keep track of what was used as deposit for old posts, otherwise the module account would not have the correct amount of funds if people started to clean up, either too much or too little. I think we still need this for this reason.
