### ISSUE TITLE
Unsafe forum polls

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2546]
# Bugs
It seems that polls in the forum involve unbounded iteration over votes during cleanup of a thread

https://github.com/Joystream/joystream/blob/olympia/runtime-modules/forum/src/lib.rs#L1608

and also there is no state bloat bond for votes on the poll

https://github.com/Joystream/joystream/blob/olympia/runtime-modules/forum/src/lib.rs#L452

# Todo

1. Verify claim
2. Propose solution
3. Implement

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202454071072068) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Not severe enough to deal with in Olympia due to `MaxPollAlternativesNumber`.

**Comment by dobertRowneySr** [comment]
line of interest:
``` rust
<PollVotes<T>>::remove_prefix(thread_id, None);
```
`PollVotes` is a private double map `ThreadId x ForumUserId` used in order to prevent double voting. 
- We cannot have a `votes: BTreeSet<ForumUserId>` inside `Thread` because   `votes` element will be still removed from the DB during thread deletion, so the operation is still `O(#voters)`
- We can't escape the problem a vector commitment scheme either, since they assume membership to a _static_ set, while the voters set at any block during a poll is a dynamic one (assuming that the poll is active).

We remove this map and we remove the unbounded iteration on thread deletion.

# Possible solutions
a. allow for double voting (possibly making each voter pay an amount proportional to the # of votes already outstanding for the pool the vote is intended to). Thus the map `PollVotes` is no longer needed.
b. Add a map `ForumUserId => UserPolls` with `UserPolls` being a `vec` of fixed size `MaxPollPerUser` (state variable that can be updated by a proposal). Now any user willing to participate in a voting poll either:
- has `UserPolls.len() < MaxPollsPerUser` in this case the user can still participate in another voting poll
- has `UserPolls.len() == MaxPollsPerUser` in this case he can participate in another voting poll only if 
 the new poll is not already present AND (at least one of the element in `UserPolls` refers to a poll that is already ended OR that poll thread is non-existing). If that is the case the ended poll participation will be replaced with the new one.

``` rust
struct PollVotes(Vec<ThreadId>);

impl PollVotes {
    // thread id refers to an existing thread with an active poll
    // There can be at most 1 poll during a thread lifecycle
    fn ensure_can_participate_in_poll(&self, thread_id: ThreadId) -> DispatchResult {
        // catch double voting attempts
        ensure!(self.0.iter().find(|t_id| t_id == thread_id).is_none(), Error::<T>::AlreadyVoted);
        if self.0.len() < Self::MaxPollsPerUser::get() {
            return Ok(());  // first case
        }
        let candidate = self.0.iter().find(|t_id| {
            if let Ok(thread) = Self::ensure_thread_exists(t_id) {
                !thread.poll.is_active()   // if poll is ended then it can be replaced
            } else {
                true   // thread doesn't exist anymore
            }
       };
       ensure!(candidate.is_some(), Error::<T>::MaxNumberOfPollsReached);
    }
}
```

**Comment by dobertRowneySr** [comment]
I have also realized that votes are accessed during `vote_on_poll` and `delete_thread` only. So in order to deal with 
bloat bond for votes we have to:
- add an extra extrinsic `claim_bloat_bond_from_expired_polls` that allows users to get back theirs bloat bond if they have voted on a poll which is now ended. This is pretty straightforward and it goes well with solution (b) above. If
we use solution b above than bloat bond refund can also be done when we are replacing an expired poll vote with a new one

**Comment by bedeho** [comment]
Thanks for the review here. I think that none of these solutions are really bullet proof, and some are quite complex. Long term, we are killing this pallet, as described here 

https://github.com/Joystream/joystream/issues/2931

So I think we should opt for a simple fix here that removes security risk. So the really cheap alternatives are

a) Remove polls entirely from threads. This is also fine w.r.t. the forum in Pioneer, as its not used.
b) Make number of votes per forum thread limited, and just add `Thread::votes: BTreeMap<userid>`. Your comment on this is not entirely correct, with an inline representation, there is not linear overhead in database operations, as its just one single database object. There is some penalty as the object gets bigger, but this is sublinear, however, it must be capped.

**I think realistically, its not even worth doing b) for now, so lets just kill it. This means remove storage map and extrinsics associated with voting entirely.**
