### ISSUE TITLE
No featuring in content directory

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2570]
Currently there are a few different ways that curators can select content as being featured, which effectively is nothing but a signal for products to present certain kinds of content a more prominent. This unlikely to be the way featuring and curation really works once we have Gateways, as being curated is intimiately tied to the characteristics of particular products experiences, even in such a deep way that it may involve particular requirements on additional assets and metadata. The current hero section of the home page is an excellent example of this. Since product experiences fundamentally are not obligated to follow these, nor should they be constrained to, we are better of entirely discarding the idea that curators in the content directory are actually involved in featuring content. We should instead make this part of the configurations of operating a gateway node powering our Atlas version. 

The immediate implication of this is that we no longer rely on the runtime and query node to surface this for new things we want to be subjected to featuring and curation in Atlas, and eventually we should probably remove the existing parts of this in the runtime and the query node metadata formats.

**Feedback welcome.**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201958576081065) by [Unito](https://www.unito.io)

**Comment by mochet** [comment]
Gateways could agree to show the featured video's on the basis of an additional reward agreed on by the council/WG. This allows featured videos to retain a high value throughout the platform. This is a social contract, but if the Gateway misbehaves and does not put the featured video in enough of a prominent place then they can be slashed or punished.

This could be extended by having a few different standards of featured videos being shown on an individual gateway... As an example:
- `large hero section of gateway homepage (minimum size = 250px tall / 80% page width` - `+3500 JOY/week` (or a number that depends on the traffic of the gateway)
- `small hero section of gateway homepage (minimum size =250px/250px` - `+1750 JOY/week`
- `shown with priority in the gateway's home page carousel` - `+1000 JOY/week`)
- `a toggle on/off featured video section, that defaults to off` - `+750 JOY/week`)

I am not a big fan of the featured video process in its current implementation, simply because it doesn't involve users spending/staking/burning tokens to choose a video they want to get featured... nor does it distinguish between categories (and since it looks like we may be catering to quite an international audience, maybe featuring an English language video on gateways that do not use English as their language may reduce the value of the feature significantly.

Obviously there are going to be restrictions in what can/can't be developed before mainnet, but maybe starting with the system I've described can bring additional, strong incentives to gateways. Especially since we have no picture of what the initial incentives a new/unknown gateway will have on mainnet, if the financial incentives are not there it would be hard to attract significant users of the gateway feature.

In order to prevent abuse of the incentive system, the Gateway WG may require that a Gateway is operational for a 1 week/2 week/4 week period before it is eligible to recieve rewards for utilizing the featured video feature on their gateway. It may also be that if we have enough data about how popular a gateway is, then we can tailor the incentives based on that.

More importantly, the featured video feature is highly important (maybe it is not ideal in its current implementation since it is one person controlling it) simply because it allows for a single creator/channel to potentially massively benefit from widespread, prominent placement throughout the platform. In financial terms this may be a huge bonus in attracting users to the platform (as well as giving them a significant number of views, subscribers and engagement from users). 

Additionally to all of that, if the featured video is of significant value to multiple gateways, it would be expected the community can create a suitable/fair way in which the featured videos are selected. We don't currently have enough on-chain features to accomplish this, but I am sure with enough value + imagination something is possible to remedy this (or alternatively, after mainnet better tools are implemented for these kind of community decisions (vs council decisions, which seem inherently less flexible when it comes to creative decisions vs business/governance decisions)

**Comment by bedeho** [comment]
> Gateways could agree to show the featured video's on the basis of an additional reward agreed on by the council/WG. This allows featured videos to retain a high value throughout the platform. This is a social contract, but if the Gateway misbehaves and does not put the featured video in enough of a prominent place then they can be slashed or punished.

I agree this policing could work, the question is really whether the decision about what to feature and how is best made by the curators vs the gateway. If the future is gateways being very diverse, in terms of audience and product form factor, then I think this heavily favors gateways controlling this, if they are all equivalent, then it might as well be done by curators. I don't see why the long term should look like a bunch of identical gateways, why would you just start a new gateway without targeting some new niche in terms of language, region, content or product form factor?

**Comment by mochet** [comment]
> > Gateways could agree to show the featured video's on the basis of an additional reward agreed on by the council/WG. This allows featured videos to retain a high value throughout the platform. This is a social contract, but if the Gateway misbehaves and does not put the featured video in enough of a prominent place then they can be slashed or punished.
> 
> I agree this policing could work, the question is really whether the decision about what to feature and how is best made by the curators vs the gateway. If the future is gateways being very diverse, in terms of audience and product form factor, then I think this heavily favors gateways controlling this, if they are all equivalent, then it might as well be done by curators. I don't see why the long term should look like a bunch of identical gateways, why would you just start a new gateway without targeting some new niche in terms of language, region, content or product form factor?

I think this feature may be far more useful for early stages of mainnet. I can imagine gateways will be taking some form of risk, and allowing them an extra "guaranteed" payment for incorporating featured videos (_if_ agreed on by the council) may give gateways the starting point that they need. Some time after an initial set of "strong" gateways become financially viable without this additional payment, it could be reduced.

Offering early adopters of the gateway system rewards tied to views and other metrics (everything outside of featuring the featured videos) is maybe flawed as it could open the door to manipulation of views etc.

So I definitely think in the medium/long term of the mainnet this function will be not particularly useful. But in the short term after the launch of mainnet there may be benefits to leaving it in (in my mind, its already a feature and its already done, but I'm not aware of what costs are associated with not removing the feature)

**Comment by bedeho** [comment]
> I think this feature may be far more useful for early stages of mainnet.

I think we dont need to couple the idea of DAO based featuring and subsidising gateways, these are in principle unrelated, and can be tackled orthogonally. Gateways operators are after all workers in a working group, and may have a base salary just by virtue of that.

> Offering early adopters of the gateway system rewards tied to views and other metrics (everything outside of featuring the featured videos) is maybe flawed as it could open the door to manipulation of views etc.

This should not be possible, because you have to burn JOY in proportion to media consumption quantity, so its really incumbent on you as a gateway to find a way to capture real value from this consumption, or at least finance that outlay as part of a plan to grow your consumer base. You would have to start doing more complex collusion attacks with infrastructure providers to do this, which when done at scale starts to generate risk of leaks and detection.

**Comment by mochet** [comment]
I'm sold on removing featured videos then (:
