### ISSUE TITLE
 On-chain content dispute and resolution

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2760]
# Question for Lezek123 
Does this proposal fully address this?
https://github.com/Joystream/joystream/issues/2911

# Background
It must be possible to have an orderly way to 

* allow curators remove content/videos: meaning its both gone from the chain, the storage and content delivery infrastructure, and query nodes.
* allow creators to contest
* allow for the dispute to be settled, on the record.

# Proposal
Here is a high level specification.

## Membership
> Assuming membership integration has happened.

* The membership lead can delete any data object from any dynamic _membership bag_ with instant effect, and only needs to provide a rationale. Deletion opens a linear discussion thread where any member can participate.
* Each membership worker has a boolean flag `can_delete_data_objects`, which allows the worker to delete any data objects from any membership bag, with a rationale. It opens up a linear discussion thread where any member can participate.

## Content Directory
* Any member, or curator, can open a complaint on any video or channel, which allows any member to participate. Has no effect on anything except alerting the relevant parties and starting the conversation. There can only be one such conversation simultaneously per entity.
* All channels are given _privilege level_, which is basically a non-negative integer identifier without any semantics. There is a default initial level for all channels, this default is updatable by the lead, and only the lead can update the level of a given channel.
* All curation groups have _permissions_, which is a (partial) map of permission level to _level permissions_, defined as a description of which of the following actions a curator belonging to a group which has permissions which for the privilege level of a given channel has the corresponding level permissions
  1. **DELETE_CHANNEL**: instantly delete a channel, with a corresponding list of data objects from the same channel bag.
  1. **DELETE_NFT_FREE_VIDEO**: instantly delete a video without an NFT, with a corresponding list of data objects from the same channel bag.
  1. **DELETE_ANY_VIDEO**: instantly delete any video, with a corresponding list of data objects from the same channel bag.
  1. **DELETE_OBJECT**: instantly delete a data objects from the channel bag.
  1. **PAUSE_CHANNEL_FUNCTION**: block, or unblock a subset of the following by channel owner
    * transfer of funds from channel account to any other account.
    * creator cashout
    * issue an NFT
    * create a video.
    * update videos.
    * update channel.
    * issue creator token.
       Critically, an invocation of this pause command does not need to block _all_ of these, it can be issued to only block a subset, as needed.
  1. **HIDE_CHANNEL**: stop/start distributors from distributing any data objects from channel bag. This means in practice all query infra should not surface it also, otherwise experience will be bad.
  1. **HIDE_VIDEO**: stop/start distributors from distributing any data objects used by video. This means in practice all query infra should not surface it also, otherwise experience will be bad.

    Critically, its fair to assume that there will only be something like 5-10 relevant levels active at any given time, and assume that if the permissions of a group does not have a mapping for a given level, then the group does not hold any permissions for a channel with this level. Thus, when a channel is given a new level never described before in any curator group, there is no need to have the runtime automatically attempt to update all permissions, the default is that noone holds any permissions relevant to this channel until further notice. Hint: read this as advice to represent permissions as a `BTreeMap` in each group.* All actions require a rationale, and opens up a linear discussion thread where any member or content directory roel (lead+curator) can participate.
* The old notion of a curator _censoring_ a channel or video is dropped.
* Content lead should be able to act as if part of any curator group. <-- already the case?
*  ~Removal of videos must be possible, _even if an NFT has been issued_, otherwise this becomes an attack vector for people to publish malicious content which cannot be removed.~ 
* When channels are deleted, all funds that may exist in the channel reward account are burned.
* Removal of a channel still works the same way as before: it has to be empty of videos.

# Note
* All discussion here should be implemented using https://github.com/Joystream/joystream/issues/2919.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201958707464579) by [Unito](https://www.unito.io)

**Comment by bwhm** [comment]
I think this makes sense, and is the curator permission concept is basically the same as a very early design, that was never fully implemented.

Question:
>   - transfer of funds from channel account to any other account.

I may be out of sync here, but what is a channel account in this context? Is it the `memberControllerAccount`, or is the key hierarchical key structure being rolled out before this? Does it affect channel collaborators in any way?

> All actions require a rationale, and opens up a linear discussion thread where any member or content directory roel (lead+curator) can participate.

I assume there's no appeal in the true sense of the word (eg. could get reversed), nor any direct risk to the curators stake? It would get very complicated very quickly, so it's probably a more realistic solution to opt for this "simple" one. 

> HIDE_*: stop/start distributors from distributing any data objects from channel bag. This means in practice all query infra should not surface it also, otherwise experience will be bad.

HIDE_* will affect argus "only", or would colossus also stop distributing them to other storage OR distributor nodes?

For i. -> iv. I would suggest it automatically blocks re-uploading the same object (by ipfs hash). We already have the functionality (but doesn't work retroactively now at least), so it wouldn't be a problem to batch the two, although it would of course only require changing a pixel to get around.

**Comment by bedeho** [comment]
> I may be out of sync here, but what is a channel account in this context? Is it the memberControllerAccount, or is the key hierarchical key structure being rolled out before this? Does it affect channel collaborators in any way?

Channels have a dedicated reward account:

```Rust
pub struct ChannelUpdateParametersRecord<StorageAssets, AccountId, DataObjectId: Ord, MemberId: Ord>
{
    /// Asset collection for the channel, referenced by metadata
    assets_to_upload: Option<StorageAssets>,
    /// If set, metadata update for the channel.
    new_meta: Option<Vec<u8>>,
    /// If set, updates the reward account of the channel
    reward_account: Option<Option<AccountId>>,
    /// assets to be removed from channel
    assets_to_remove: BTreeSet<DataObjectId>,
    /// collaborator set
    collaborators: Option<BTreeSet<MemberId>>,
}
```

> I assume there's no appeal in the true sense of the word (eg. could get reversed), nor any direct risk to the curators stake? It would get very complicated very quickly, so it's probably a more realistic solution to opt for this "simple" one.

There is no appeal per say, was thinking of that. The best way to do it is for the curators to follow a rule of basically first hiding the channel, then starting a conversation with the owner explaining the problem, and warning that there is X time before stuff can get deleted, and then the deletion itself can happen later in an irriversible way. Staking just started getting really complicated and messy, not worth it.

> HIDE_* will affect argus "only", or would colossus also stop distributing them to other storage OR distributor nodes?

Only Argus.

> For i. -> iv. I would suggest it automatically blocks re-uploading the same object (by ipfs hash). We already have the functionality (but doesn't work retroactively now at least), so it wouldn't be a problem to batch the two, although it would of course only require changing a pixel to get around.

I disagree, the upload blocking thing is expensive on chain weight over time, has to be used sparingly.

**Comment by Lezek123** [comment]
> Does this proposal fully address this?
> https://github.com/Joystream/joystream/issues/2911
> ...
> All curation groups have permissions, which is a (partial) map of permission level to level permissions, defined as a description of which of the following actions a curator belonging to a group which has permissions which for the privilege level of a given channel has the corresponding level permissions
>
> DELETE_CHANNEL: instantly delete a channel, with a corresponding list of data objects from the same channel bag.
> ...
> DELETE_ANY_VIDEO: instantly delete any video, with a corresponding list of data objects from the same channel bag.

In https://github.com/Joystream/joystream/issues/2911 under _**Change permissions model to allow Curators and/or Lead to remove channel/video assets**_ I was considering the implications of a single actor having such permissions, which I concluded with:

> However this has a major drawback, because it means the entire content directory can be wiped out by a single actor.

It seems like this is still the case under the model described here (ie. the lead can wipe out the entire content directory)

This would obviously be a very costly operation, considering:
- The lead will most likely lose the entire stake
- The lead will have to pay a considerable amount in transaction fees

But:
- The cost of this operation could be partially reduced if some funds (like `deletion_prize`) are returned to the sender (which is the case currently)
- Unless there is always an up-to-date backup of all existing content somewhere, there's going to be a huge & irreversible damage done to the platform

I think this model can still work, but only if the cost (leader stake, tx fees) is high enough to discourage any potential bad actor, which could mean anyone with such permissions will probably need to have a **very high** stake.

In https://github.com/Joystream/joystream/issues/2911 I suggested that this problem could be solved by introducing a minimum period for which a video / channel must remain hidden/censored before it can be removed. Only after this period is finished and noone with sufficient permissions objects to the removal, the video / channel can be removed _for good_.

Do you think that's a viable solution? Or do you think the problem I described isn't severe enough to even try to address it in the first place?

**Comment by Lezek123** [comment]
Now that I think about this, it's probably unavoidable in the long run, storage lead can do similar damage by sacrificing its stake and the best way to address it (when it comes to assets) would probably be to:
a) have sufficient replication among distinct storage providers
b) make it storage providers responsibility to have a "reasonable" removal policy (ie. don't drop objects immediately, but keep them in some temporary location for some time before deleting them permanently)

**Comment by bedeho** [comment]
- I agree this is a real issue.
- I think it's better to have some sort of limit, rather than making everything more expensive all the time, even for good actors.
- Like max x deletions per day? at least this would limit the risk of a totally hosticle/wreckless lead, or set of curators. The limits could also be per actor, to be more granular. The bad side of this is that it opens up an attack vector of someone creating tons of non-compliant content quickly, exceeding these limits. This can be countered by for example being sensitive to when content was created, and/or allowing council to instantly lift limits through a proposal as needed.

Any better idea?

> make it storage providers responsibility to have a "reasonable" removal policy (ie. don't drop objects immediately, but keep them in some temporary location for some time before deleting them permanently)

I think this is a very good idea in general, can you make an issue for storage providers about adding this sort of policy?

**Comment by mochet** [comment]
Very late to reading this but it seems very well thought out.

A few questions:
> Any member, or curator, can open a complaint on any video or channel, which allows any member to participate. 
* How much does opening a complaint cost? Is the cost stored in the runtime?
* The reason I ask: What's to stop spamming of complaints? There should be some reasonable cost affixed and it may need to be adjusted at times. These types of systems are prone to disruptive behavior and I would not say it is unlikely that someone may target it (probably someone who has had action taken against them and doesn't think its fair!)

Also:
> can open a complaint on any video or channel
* Am I correct to assume that even if a complaint is made against a video that the actions availble include not only video actions but channel actions?

**Comment by Lezek123** [comment]
> Like max x deletions per day? at least this would limit the risk of a totally hosticle/wreckless lead, or set of curators. The limits could also be per actor, to be more granular. The bad side of this is that it opens up an attack vector of someone creating tons of non-compliant content quickly, exceeding these limits. This can be countered by for example being sensitive to when content was created, and/or allowing council to instantly lift limits through a proposal as needed.
> Any better idea?

I like the idea of taking the lifetime of the content into account, but I'm not sure if enforcing a limit of deletions per day is a good solution for this issue. There is obviously more and less valueable content, one can do a lot of damage deleting, for example, 1000 "most valueable" videos, along with the associated nfts etc. and on the other hand, as you mentioned, one can take advantage of that and create a ton of spam content, that may then become harder to clean up.
  
What do you think about the idea I mentioned w.r.t. enforing a period for which a channel / video has to remain hidden (inaccessible) before it can be removed? I think it goes well with the idea of the "dispute resolution" and having a discussion thread beeing automatically opened per each moderator's action. I feel like opening such thread once the content is already completely removed from the platform may be a bit _too late_ in some cases.

So to combine the idea of beeing sensitive to content lifetime with my initial idea of enforced pre-removal period, I can suggest the following model:

There are two periods that apply to content like channels and videos (and can possibly be adjusted by the council):
- `fragilityPeriod` - begins when the content is created and lasts `X` blocks (ie. 1 day)
- `quarantinePeriod` - begins when the content is hidden by a moderator and lasts `Y` blocks (ie. 1 day)

And:

- Any content can be removed instantly during its `fragilityPeriod` by either lead or a curator with sufficient permissions. This should prevent attacks where some actor / a group of actors try to upload a batch of outright inapproperiate content.
- Any content after `fragilityPeriod` can only be hidden / locked / made temporarly inaccessible (which will trigger `quarantinePeriod`), but cannot be removed.
- During content's `quarantinePeriod` it still cannot be removed (but remains inaccessible). This is the period when the dicussion can take place. Any actor (curator) with sufficient permissions can cancel the `quarantinePeriod`.
- Once content's `quarantinePeriod` is over, it can be safely removed by any actor with sufficient permissions.
- To address some rare edge-cases where we'd want to skip `quarantinePeriod` and remove content older than `X` instantly, a proposal can be created with a set of channels / videos to be removed (I'm not sure if this is really necessary though)

**Comment by bedeho** [comment]
This is a nice design, but things are starting to get really complex at this point, I do wonder whether its worth adding all of this in here at this stage, in particular when trying to now map out what should or should not be allowed as actions on a channel, video while in qurantine. This idea of not deleting right away is something that can be enforced as a matter of process by the content directory WG members, it does not have to be the runtime.

**Comment by traumschule** [comment]
> allow curators remove content/videos: meaning its both gone from the chain, the storage and content delivery infrastructure, and query nodes.

> first hiding the channel, then starting a conversation with the owner explaining the problem, and warning that there is X time before stuff can get deleted, and then the deletion itself can happen later in an irriversible way

> > HIDE_* will affect argus "only", or would colossus also stop distributing them to other storage OR distributor nodes?
> Only Argus.

These are contradicting. Maybe best to branch out separate issues for mentioned attack vectors / conflict types?

Define `inapproperiate content`. One scenario is an online mob being able to pressure lead actors (#2870) into wiping content for political or whatever reasons over night. `Offensive` would be similarly vague and there is probably no final definition including all possible threats to the DAO itself that would justify deletion (eg. DMCA claims). Understandably JSG tries to avoid this question which means a WG / the council needs the final say (considering #144 for mass deletion / hiding).

Idea: Make it undesirable for both uploaders and leads to not resolve on-chain conflicts by putting their stakes (and maybe related accounts) at risk if no solution is found within X blocks and a third entity has to be invoked by the council. Also avoid creating an overwhelmed court system where assets get frozen for long periods and motivated actors (leads, creators) are turned off.

Personally i do not trust the `membership lead` approach (power corrupts + above reason) and prefer transparent processes with public review and appeal options (what i thought this issue is going to be about). Especially `membership lead can delete any data object from any dynamic membership bag with instant effect` seems too primitive of a governance model to be worth implementing on-chain or only as a last resort after council activated temporary crisis / dictator mode (with reason).

Important design decisions like these could also be opened up for community / FM discussion to realize the primary slogan *controlled, owned, and operated by its users*.  Or in case that was never meant for pre-mainnet, the resulting system should be flexible enough to allow different modes for the council to switch between / changing above suggested periods (without modifying runtime code).

Since this targets mainnet with less time pressure what about a model inspired by [WP:Deletion_policy](https://en.wikipedia.org/wiki/Wikipedia:Deletion_policy) / [WP:Wikipedia:Deletion_guidelines_for_administrators](https://en.wikipedia.org/wiki/Wikipedia:Deletion_guidelines_for_administrators):
- mark for deletion with grace period (depending on content type)
- creator (or anyone?) can start discussion to raise concerns (`create thread` button for creator?)
- creator can mark thread as resolved (ie consenting) or one (or more?) curator(s) can un-quarantine content
- negative incentive for both parties if no resolution is found within grace period
- with consensus execute deletion and purge content from all providers (SP+DP)
  - OR more modern and complex: add consumption filters (in atlas/equivalent products) to let users disable [safe search](https://en.wikipedia.org/wiki/SafeSearch) which is enabled per default for all members and not logged in visitors
- without solution automatically create a proposal for the council to vote on

**Comment by mochet** [comment]
@traumschule 
I wanted to explain at least how I see our current governance features relating to some of the issues you mentioned in the context of the proposed design. The council has some limitations that make at least parts of what you mentioned highly infeasible. I also think there are scaling issues, particularly when it comes to individual decisions--because there may be many thousands of ongoing content disputes.
I don't think the proposed system is perfect, but I do think it is pretty good when considering it with everything else that is on the platform.

> Define inapproperiate content. One scenario is an online mob being able to pressure lead actors into wiping content for political or whatever reasons over night. Offensive would be similarly vague and there is probably no final definition including all possible threats to the DAO itself that would justify deletion (eg. DMCA claims). Understandably JSG tries to avoid this question which means a WG / the council needs the final say

* Defining inappropriate content is always tricky. What I believe will happen is that our `constitution` will define this--it will be the `definition` that people should use as the basis for judging the Curator Lead in the event of abuse. The `constitution` will be a highly expensive and slow moving part of the platform.
* The `constitution` could include very, very strict definitions or it could leave some areas or situations freely up to the decision of the lead. There's probably going to be some flexibility because the world changes quickly and our DAO is just like any government and will probably be slow to change.
	* Of course the lead has to then take the `constitution` and interpret it themselves, which they might have outlined with via their `application` and they will likely also choose to update people on their interpretation of it via the `forum` if it changes.
	* When the lead was hired--they were basically approved and entrusted with access to tools that can be used freely in exchange for a stake of tokens that was also approved and entrusted with being high enough to *try* and prevent abuse.
		* This is a risk the council took, which should ideally be based on a combination of the stake the lead put up, their application and their reputation combined. The council `agreed` that this lead had enough trust that the risk of them misusing their access was unlikely.
		* The risk of the trust given is that it allows the lead to delete things in an arbitrary way, which also automatically creates a discussion thread whenever this special access is used.
			* On this discussion thread any member can participate. In the event of abuse, known, unknown, trustworthy or even scammers may provide their own account of the problem and say the lead was incorrect and unfair or prove what is said by other participants is incorrect.
				* These discussion threads are what should form the basis of someone creating a `fire` proposal. It would be looking into the reputation and platform stake each member across multiple threads have said about the lead. The proposal author should include links to problematic chain events or some form of report showing the best proof they can.
		* The only counter to this level of risk the council took, is how quickly until someone notices the lead being erratic and actually creates a proposal to fire them. The proposal + voting process could take as little as an hour or more than 2-3 days. In that amount of time the lead would've been able to delete some number of videos.
			* If we have 10m+ videos and it is found the lead had "falsely" deleted 500 or even 20,000 that is the cost that comes with any kind of risk. But losing 500-20,000 videos isn't a showstopper.
				* Most importantly, the evidence of what the lead did and the decisions made in reaction to it will be recorded. They will always be available and it will form the basis of how future lead applications are considered as well as how future lead actions are judged. Every single aspect of it will become a part of the DAO's history and it will become a part of how people evaluate the DAO.

> Personally i do not trust the membership lead approach (power corrupts + above reason) and prefer transparent processes with public review and appeal options (what i thought this issue is going to be about). Especially membership lead can delete any data object from any dynamic membership bag with instant effect seems too primitive of a governance model to be worth implementing on-chain or only as a last resort after council activated temporary crisis / dictator mode (with reason).

I am pretty sure the only power the membership lead has is to delete user thumbnails (which I think are stored in the `membership bag`). AFAIK memberships can't be deleted or banned at all. Thumbnails are a really nice personalization feature to have, but creating a huge system just for thumbnails (which I'm pretty sure are only seen on Pioneer or maybe comment sections) seems like the cost of such a system would hugely outweigh the benefit.
The lead will be staked and so if they decide to arbitrarily start deleting user thumbnails they can easily get fired and lose their stake. If we lose a bunch of thumbnails it isn't as mission critical as other things IMHO and also the lead would've spent a lot on transaction fees.
On top of this `Deletion opens a linear discussion thread where any member can participate.` 
There may be users that are unhappy with their thumbnails being lost in a situation of abuse and ideally the DAO participants worked together to punish or fire the lead and can see and share proof that action was taken. They can even fund a way to pay the affected users a small amount as compensation for the inconvenience.

WRT the example you showed from Wikipedia:
> without solution automatically create a proposal for the council to vote on

The problem with it is simply bandwidth. We are already one of the most active DAOs on the governance side I have ever seen, but there are limits. If proposals were automatically created for single decisions like content disputes and lets say some world event resulted in many videos being uploaded that went against the `constitution` then there would be hundreds, thousands or even millions of proposals. Maybe the amount of uploads is far too high for the curator group to properly manage. Or maybe the lead or some amount of curators were sick and things temporarily slowed.

I do agree that an arbitration system could be interesting, but I think it would simply never work if the council had to be faced with judging decisions that were taken by an individual in an single situation.

The Council will hopefully be formed by people who know a lot about the DAO and how it works, aspects of economics, incentives, deciding whether to punish leads or not based on a situation (which would be a collection of several incidents) or what membership costs should be. If they were tasked with judging individual situations like this it would require significantly more attention and it'd make effectively managing the rest of the DAO's essential components extremely difficult, if not impossible.

It would be the same case on judging whether the firing of a single by a WG Lead was unfair or unwarranted. Judging something like that would mean requiring council members to pay attention to not only every element of the DAO but interpersonal relationships also.

The prospect of 100s of proposals being created in as short of a span as an hour for the council should never be possible, because it would be disastrous. The cost of proposals has to be paid by someone and the amount required for this needs to be sufficient enough to prevent the council's limited bandwidth being taken up by issues which are too minor. Users have to judge how minor or major an issue is when considering whether to propose something and I don't think they should be automatically created as part of any on-chain event.

I think to put it another way, the threshold for having a lead face a council vote on possibly firing them is that a sufficient number of actors have to demonstrate unhappiness and someone has to see what they're saying and decide to put their own tokens at risk to put the proposal forward. Or it could really just be someone who is rich and decides to make a firing proposal based off a single decision a lead made.

> Idea: Make it undesirable for both uploaders and leads to not resolve on-chain conflicts by putting their stakes (and maybe related accounts) at risk if no solution is found within X blocks and a third entity has to be invoked by the council. Also avoid creating an overwhelmed court system where assets get frozen for long periods and motivated actors (leads, creators) are turned off.

I think this is a cool idea, but I can only imagine how highly complex it would be to implement. Plus the scale may be way too high for this to be economically possible--tens of thousands of videos being disputed at once may happen from time to time. I have seen some interesting examples of other DAOs and web3 projects that already exist that offer judgement systems. I suppose they could be utilized to try and help in situations like these--but as with everything, it's some amount of risk being entrusted to some person using some definition that is subject to differing interpretations when they provide a judgement.

I get a lot of where you're coming from when you say "power corrupts". While we don't have a super active testnet where the governance system is really pushed hard on a lot of these topics, we do have what is a system that does have accountability built in.

For example, I think that some of Wikipedia's governance policies are really interesting, but I also know that they came from a very different era because:
- there are people you can pay to manipulate their governance decisions
- admins and certain users on Wikipedia are allowed to permanently delete things and records can be completely wiped.
So while we may have situations where users accept payments to manipulate things, we will always have records (thumbnails or videos may be lost, but the paperwork won't). The discussion threads that are automatically created or the `rationale` field that is filled each time actions are taken will be permanently recorded.

A lot of people on internet communities are super passionate and participate freely, they find things they are obsessive about and probably never imagine a world in which you would have to put up a sum of money as collateral/stake when doing it and they also usually don't get paid for doing so.
They're also very often built entirely from social relationship and while finances may be involved too, there are always questions of accountability that have limited answers.
The Wikimedia foundation only does financial reports on a yearly basis that are more of a summary, but Joystream will record how much the richest and poorest person are being paid, who decided those payments, who was responsible for creating proposals as well as who voted to approve, reject, abstain or slash--which will also have a `rationale` field that is recorded. I'm not certain, but I think our council being able to include a `rationale` for why they voted the way they did on each proposal is a pretty unique feature and it creates a high level of accountability. It makes understanding exactly how a particular Council member has acted in the past far easier and can be utilized to inform voting decisions.

What exact rules and policies we do actually end up with, how they are defined, decided, interpreted and enforced in a system with stake, punishment, openings, applications and proposals is going to be really interesting to see develop, because none of those features (that I know of) exist anywhere else and no community I'm aware of was built with access to these tools. How each and every one of them is actually utilized is really impossible to predict. It seems like it will be like humans usually are, unpredictable and undergoing a constant process of evolution (but unlike evolution it will have a very accurate record keeping system).

**Comment by bedeho** [comment]
# Doing a 180°: deleting assets is a nono

After some additional contemplation I think that deleting _assets_ like NFTs or Creator Tokens is just a not something we can allow. Just the possibility of this happening, or if it ever actually happened in a case which was even mildly contentious, then this looming risk would end up undermining the value of all assets regardlss.

It also is actually unlikely to be required to achieve our goal. The main problem we want to avoid is someone locking in content which is out of policy for the DAO, and this mainly really refers to data objects which correspond to heavy assets like audio, images or video media. Hence, simply reserving the right to delete data objects in the storage bag of a channel should be sufficient.

**Comment by Lezek123** [comment]
Implemented in https://github.com/Joystream/joystream/pull/3366
