### ISSUE TITLE
Increase video title length limit

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2765]
By popular demand

https://discord.com/channels/811216481340751934/813361923172335648/898273768726757416

seems easy enough to do, requires trivial changes in query node and Atlas.

**Comment by kdembler** [comment]
Is there actually anything we need to change on the query node side? The current limit for new uploads in Atlas (40 characters) is pretty arbitrary and I think was picked semi-randomly when we were first doing Studio and just never changed since. So if I'm not mistaken this is a matter of lifting this limit and just changing this to something else, although I'm curious on how we should pick this value

**Comment by bedeho** [comment]
Ok, in that case lets just bump it then, 60? if people compain again, we change it again ;)

**Comment by olewko1989** [comment]
> Is there actually anything we need to change on the query node side? The current limit for new uploads in Atlas (40 characters) is pretty arbitrary and I think was picked semi-randomly when we were first doing Studio and just never changed since. So if I'm not mistaken this is a matter of lifting this limit and just changing this to something else, although I'm curious on how we should pick this value

Hi, I think it will be very useful to increase the limit. for example this is very useful in Audiobooks. When the title needs to indicate the author and the title of the book, then a lot of characters are needed. For example, audiobook on Russian:  Невилл Годдарт - Сила сзнания, от мечты к реальности. There are 50-52 characters.

**Comment by olewko1989** [comment]
> Ok, in that case lets just bump it then, 60? if people compain again, we change it again ;)

Great, 60 should be enough
Thank you!)
