### ISSUE TITLE
Questions about the new storage system from Atlas perspective

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#2803]
I did my first deep-dive into Giza storage system based on the code from [distributor-node CLI](https://github.com/Joystream/joystream/blob/giza_staging/distributor-node/src/commands/dev/batchUpload.ts) and [joystrem-cli](https://github.com/Joystream/joystream/blob/giza_staging/cli/src/commands/content/createChannel.ts) and this resulted in a couple of questions. Some of those are genuine questions, some just ask for confirmation and others are more forward-thinking about integration with Atlas.

1. How is `bagId` determined? Does it follow some pre-defined naming scheme? What's the general policy for determining a bag? Each channel will have a separate bag that will hold all assets for his channels? So both channel-specific assets but also assets for videos uploaded by this channel?
2. Given a `bagId`, a query can be made to the query node to determine list of storage nodes that will be able to accept the upload. Is this correct?
3. To be able to upload, a token needs to be generated with a given storage node? Is this mechanism described somewhere? I guess the reason for it is so that only person that created the data object can start an upload? Is the token a JWT or something similar? How long-living is it? I guess a separate token will be needed for each separate storage node we will be uploading to?
4. I'm curious about this event that's being accessed here - [https://github.com/Joystream/joystream/blob/giza_staging/cli/src/commands/content/createChannel.ts#L67](https://github.com/Joystream/joystream/blob/giza_staging/cli/src/commands/content/createChannel.ts#L67) The event's name is `DataObjectsUploaded` but this happens before the upload even starts? Is this actually relating to data objects being registered on-chain? Seems like an unfortunate name in that case? 😅
5. Is it correct that the `content_id` isn't generated by the uploader anymore but by the storage node (or even some other entity) and returned via `DataObjectUploaded` event? Also, the unused `type_id` got dropped? If correct, then the only asset-related data that needs to be sent as part of the extrinsic is `size` and `ipfs_content_id`?
6. Given a data object, for example a channel avatar, how do we determine the list of distributor nodes that the asset can be downloaded from?
7. Once we know the data object id and the URL of the distributor node, is accessing the object just a matter of request to `/api/v1/asset/{objectId}`?
8. How do we know when an asset is ready to be fetched from the distributor node? Previously we would upload asset to a storage node and once it was accepted and this was reflected in the query node, we could fetch the asset right away from the storage node that accepted the upload. How do we know asset has already been replicated by distributor nodes and is ready to download? I hope there is some better mechanism than "keep trying until it is available"
9. As a followup to the above point, previously we would by default fetch the asset from the same storage node it was uploaded to. This created a guarantee that the asset would be available for download immediately after the upload was finished. If I understand the new system correctly, after upload, asset will need to be replicated by the distributor nodes first before it can be downloaded. Assuming we will be dealing with big video files sometimes (say 5 gigs) I guess this can take tens of minutes to complete? If so, this will make the publisher UX much worse.

**Comment by Lezek123** [comment]
> How is bagId determined? Does it follow some pre-defined naming scheme? What's the general policy for determining a bag? Each channel will have a separate bag that will hold all assets for his channels? So both channel-specific assets but also assets for videos uploaded by this channel?

`BagId` in the runtime is an algebraic type (Rust `enum`), see: https://github.com/Joystream/joystream/blob/giza/runtime-modules/storage/src/lib.rs#L565

When interacting with the runtime (ie. sending extrinsics) the `bagId` for a channel can be represented as:
```typescript
const bagId = { Dynamic: { Channel: channelId } }
// Then it can be used inside a tx like:
api.tx.storage.sudoUploadDataObjects({
  bagId,
  // ...
})
```

When interacting with storage node / query node / CLIs, the `bagId` is often represented as string following a format described here: https://github.com/Joystream/joystream/tree/giza/storage-node-v2#storage-node-devverify-bag-id

So for example:
```typescript
const storageNodeTokenRequestData = {
  bagId: `dynamic:channel:${channelId}`,
  // ...
}
```

The channel bag holds both channel assets and video assets for videos that belong to the channel.

> Given a bagId, a query can be made to the query node to determine list of storage nodes that will be able to accept the upload. Is this correct?

Yes, this is the query that the CLI uses: https://github.com/Joystream/joystream/blob/giza_staging/cli/src/graphql/queries/storage.graphql#L8

When a new channel is created (along with the channel bag), it will take ~3 blocks time before the query node will have this data available.

> To be able to upload, a token needs to be generated with a given storage node? Is this mechanism described somewhere? I guess the reason for it is so that only person that created the data object can start an upload? Is the token a JWT or something similar?

The token is generated by sending a `POST` request to [`/authToken` endpoint](https://github.com/Joystream/joystream/blob/giza_staging/storage-node-v2/src/api-spec/openapi.yaml#L151) and then included in `x-api-key` header when sending an upload request (`POST /files`)

It is signed by member controller key, an example implementation of the request can be found here: https://github.com/Joystream/joystream/blob/giza_staging/cli/src/base/UploadCommandBase.ts#L211

I think @shamil-gadelshin is working on improving the documentation.

> How long-living is it?

Current expiration time of the token is 30s: https://github.com/Joystream/joystream/blob/giza_staging/storage-node-v2/src/services/helpers/tokenNonceKeeper.ts#L4

> I guess a separate token will be needed for each separate storage node we will be uploading to?

Yes. And also for each separate data object upload request (the token is only valid for uploading an object of `DataObjectId` specified in the token request)

> I'm curious about this event that's being accessed here - https://github.com/Joystream/joystream/blob/giza_staging/cli/src/commands/content/createChannel.ts#L67 The event's name is DataObjectsUploaded but this happens before the upload even starts? Is this actually relating to data objects being registered on-chain? Seems like an unfortunate name in that case?

Correct, I made the exact same remark in the [query-node mappings code comment](https://github.com/Joystream/joystream/blob/giza_staging/query-node/mappings/storage/index.ts#L240) :sweat_smile: 

> Is it correct that the content_id isn't generated by the uploader anymore but by the storage node (or even some other entity) and returned via DataObjectUploaded event?

If by `content_id` you mean `DataObjectId`, then yes, this is just an "auto-incremented" number, like `ChannelId` or `MemberId`, assigned by the runtime.

> Also, the unused type_id got dropped?

The `type_id` got dropped, but data object type is determined by the query node in the moment of creation and can be retrieved with a query like:
```graphql
  storageDataObjects {
    type {
       # ...
     }
  }
```

> If correct, then the only asset-related data that needs to be sent as part of the extrinsic is size and ipfs_content_id?

Yes, this is actually the exact data that is part of [`DataObjectCreationParameters` struct](https://github.com/Joystream/joystream/blob/giza_staging/runtime-modules/storage/src/lib.rs#L551)

> Given a data object, for example a channel avatar, how do we determine the list of distributor nodes that the asset can be downloaded from?

It's easier to use `bagId` than `dataObjectId` for this purpose, then this can be done with a query like:
```graphql
  distributionBuckets(where: {
    bagAssignments_some: { storageBagId_eq: "dynamic:channel:2" }
  }) {
    operators {
      status
      metadata {
        nodeEndpoint
      }
    }
  }
```

Unfortunately you'd need to apply some client-side filtering by operator status (`ACTIVE`) in this case, because Hydra does not support such deep relationship filtering.

> Once we know the data object id and the URL of the distributor node, is accessing the object just a matter of request to /api/v1/asset/{objectId}?

Yes, but you may want to use some mechanism to choose a closest distributor node depending on its distribution family metadata as described [here](https://github.com/Joystream/joystream/blob/giza_staging/distributor-node/docs/node/index.md#distributionbucketfamilymetadata).

> How do we know when an asset is ready to be fetched from the distributor node? Previously we would upload asset to a storage node and once it was accepted and this was reflected in the query node, we could fetch the asset right away from the storage node that accepted the upload. How do we know asset has already been replicated by distributor nodes and is ready to download? I hope there is some better mechanism than "keep trying until it is available"

As soon as an asset is accepted by any storage node the distributor node should be able to serve it.
The distributor node does not replicate any data unless it is requested.
When the data is requested it tries to find a storage node that can provide this data and then caches it (in the local filesystem).
You can find an in-depth documentation of the distributor node inner workings [here](https://github.com/Joystream/joystream/blob/giza_staging/distributor-node/docs/node/index.md).

> As a followup to the above point, previously we would by default fetch the asset from the same storage node it was uploaded to. This created a guarantee that the asset would be available for download immediately after the upload was finished. If I understand the new system correctly, after upload, asset will need to be replicated by the distributor nodes first before it can be downloaded. Assuming we will be dealing with big video files sometimes (say 5 gigs) I guess this can take tens of minutes to complete? If so, this will make the publisher UX much worse.

See the answer above. Besides that you actually can still use the storage node, because the `GET /files/:id` endpoint is currently public, but it's probably not adviseable, as this may change in the near future.

**Comment by kdembler** [comment]
@Lezek123 thanks for all the answers, that was very insightful. Sorry for late response, got carried away with other stuff, but coming back to this now. I think almost everything is clear at this point however I have one concern left, regarding figuring out which distributor nodes should be used for a given asset. You've mentioned that the best course of action may be to do a query like this:
```graphql
distributionBuckets(where: {
    bagAssignments_some: { storageBagId_eq: "dynamic:channel:2" }
  }) {...}
```
That makes sense, however my concern is that it seems we may need to run this query for each separate `bagId`? Given that we can easily display content from 30+ different channels on home page, does that mean we will need to run a separate request for each channel just to resolve distributor nodes that can serve assets? Seems a bit excessive, would it be possible to aggregate this in some way?

**Comment by Lezek123** [comment]
Of course there are many ways to fetch distributors for multiple bags in an aggregated way

Single query:
```graphql
distributionBuckets(
    where: {
      bagAssignments_some: {
        storageBagId_in: [
          "dynamic:channel:1",
          "dynamic:channel:2",
          "dynamic:channel:3"
          # ...
        ]
      }
    }
  ) {
    bagAssignments {
      storageBagId
    }
    operators {
      status
      metadata {
        nodeEndpoint
      }
    }
  }
```

Or you can fetch distributor bucket ids grouped by bag ids and then execute separate query to fetch distributor buckets:
```graphql
  storageBags(where: {
    id_in: [
      "dynamic:channel:1",
      "dynamic:channel:2",
      "dynamic:channel:3"
    ]
  }) {
    distirbutionAssignments {
      distributionBucketId
    }
  }

  distributionBuckets(where: { id_in: [
    # ...
  ] }) {
    operators {
      status
      metadata {
        nodeEndpoint
      }
    }
  }
```

**Comment by kdembler** [comment]
Okay I guess I still need to better understand storage bags and distribution buckets. Will be studying and will let you know if I still have some questions. Thanks!

**Comment by kdembler** [comment]
I think everything is clear at this point, will close for now and possibly reopen later if needed. Thanks for your help again Leszek!
