### ISSUE TITLE
Idea: Emergency Council Mint

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2810]
What if the council had 2 mints:

* the `regular_mint` that gets filled by however the new budget stuff works (the one for spending proposals, council member payments)
* a secondary `emergency_mint` that gets filled by say, `3%` of whatever `regular_mint` is filled with. So if the `regular_mint` gets `1000 JOY per day`, `3%` of that (`30 JOY per day`) is put into the `emergency_mint`.

Over time, the `emergency_mint` would naturally fill up. And lets say something happens where emergency funding is clearly required. And since `emergency_mint` should only be accessible for actual emergencies, lets say there's a new proposal type called `emergency_mint_proposal` that has similar stake/quorum requirements to a runtime upgrade proposal.

In such a situation, even if the budget isn't great, the council would be able to vote to approve the `emergency_mint_proposal` which would transfer tokes from `emergency_mint` > `regular_mint` thus allowing the council to fund any "urgent" situation that might arise.

Example scenario:

* There are some problems on mainnet and it is clear we need a runtime upgrade ASAP, and its going to involve getting a lot more people on board to make it happen on time, the current budget simply doesn't allow for it, someone creates an `emergency_mint_proposal` and the council could approve it, which would transfer some amount of funds to the `regular_mint`

Notes:

* It could also maybe make sense that this `emergency_mint` can actually transfer funds to any of the Working Group's mints, maybe there is a mainnet scenario where storage costs suddenly double or some other emergency action is required. - The emergency funds shouldn't be payable to an individual's address. By only being transferrable to the council's regular mint or a working group's mint, this would reduce the likelihood of someone being able to attack the emergency mint.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201958578445048) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Thanks for the suggestion!

# Meta

I think for the future, it would be easier both to understand and evaluate the merits of a proposal, as well as brainstorm about alternatives and prioritize, if it started with a clearly stated problem i advance of the solution.

# Problem

As I understand it, the problem here is that the council may need to, in emergencies, spend outside of budget constraints of normal budget dynamics. I will continue under this premise.

# Proposed Solution

Introduce a second mint from which the council can finance expenses , which keeps getting filled at rate of 3% of whatever regular mint gets, and a new proposal with quite a high bar for spending out of this budget.

# Analysis 

The problem is certainly very plausible. I think the solution seems a bit overly complex, in that it requires two mints. To me it seems like the main value unlock is having a dedicated proposal that allows the council to escape normal spending constraints, not so much having to mints. I also see the 3% cut as being a bit too arbitrary as a way to constraint he spending. For example, it's not clear to me that you want the emergency budget to just grow perpetually as long as there are no emergencies?

A simpler solutions seems to me to just keep the single budget, as we do now, but allow the council to do an emergency financing where you increase the spending cap one time. The limit of this could be % of the normal budget replenishment amount. You could also make it so that this proposal could not get passed more than once every quarter or something. This would require no changes in Pioneer 2, the runtime, and keep everything conceptually quite simple.

**Comment by mochet** [comment]
@bedeho 
>The problem is certainly very plausible. I think the solution seems a bit overly complex, in that it requires two mints. To me it seems like the main value unlock is having a dedicated proposal that allows the council to escape normal spending constraints, not so much having to mints. I also see the 3% cut as being a bit too arbitrary as a way to constraint he spending. For example, it's not clear to me that you want the emergency budget to just grow perpetually as long as there are no emergencies?

Yes, the `3%` amount is totally arbitrary, could be anything. And yes, I intended the emergency budget to grow perpetually. Part of the reasoning for this is that due to the difficulty of accessing the emergency budget, it would feasibly increase the percieved value of the project and also provide some sense of security against the council being unable to fund urgent things in an emergency.

>A simpler solutions seems to me to just keep the single budget, as we do now, but allow the council to do an emergency financing where you increase the spending cap one time. The limit of this could be % of the normal budget replenishment amount. You could also make it so that this proposal could not get passed more than once every quarter or something. This would require no changes in Pioneer 2, the runtime, and keep everything conceptually quite simple.

Yes that would also work! also sounds like it would be much easier to do.

The only difference really between option A vs B is that the first option would gradually increase its funds over time, thereby cementing value in the governance system (hopefully). Having people aware the Council has access to a special mint just for emergencies, and knowing the value of that mint over time would hopefully give more value. Ideally, the less the council has to actually resort to using the emergency mint should signal that the governance system and budgets are being done effectively.

**Comment by bedeho** [comment]
Ok, adding this to backlog of proposals to do then ;)

**Comment by bedeho** [comment]
Covered with this: https://github.com/Joystream/joystream/issues/3663
