### ISSUE TITLE
Idea: disincentivize voter apathy

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#2845]
Currently, a user puts up stake when submitting a proposal, and this amount is returned to the creator if the proposal is approved. The amount might be diminished or `0` if the proposal is rejected or slashed... or if the council doesn't vote on it and it expires.

On mainnet council members will be paid a flat fee for their role, however there is no disincentive when proposals are not voted on. This creates a problem, as with an expected `50` proposal types on mainnet, there will be a steady/high volume of proposals on a daily basis.

One possibly solution to this is to have some sort of account/mint (we will call this the `proposal account`) within the proposal process that mints tokens in a way that cannot be accessed by users, nor governance.

(for the example, we will completely ignore the user side of proposal stake/fees, as we are only focusing on 

For example
* if a `text proposal` is created by a `user` the `proposal account` would mint some amount of tokens--these are actual tokens minted into `issuance` (and not just some form of capacity). We'll say `25000` in this example.
* if the proposal is voted on (regardless of outcome, if it at least it is executed, or rejected/slashed/approved) this amount of `25000` is burned...
* otherwise, if not sufficiently voted on the amount remains (permanently), which would increase inflation (minorly, depending on the amount)

Some benefits of this system would include:
* Having a measurable performance indicator of each council/the overall proposal system
* Having some form of financial impact if proposals are not voted on
* Doing so in a way which has no immediate time impact (as in, there is no incentive to spam votes 2 minutes after a proposal is announced, since the entire timeframe of the proposal is allowed before it expires)

Negatives:
* It may increase usage of the `abstain` vote

**Comment by bedeho** [comment]
I totally see this problem, but I think it's actually slightly deeper, it's about getting the council to do quality work, when measuring it is very difficult, this is difficult for voters in a country monitoring their elected reps., and it's even hard for shareholders trying to monitor a board or CEO. At least in the latter you have a market pricing your shares, but it's still a difficult problem. So, and I think you know this really, it's about quality of work - which will largely result in voting, rather than just voting.

I am actually not convince that this change would do much about voting, even `abstain` voting. You list 

> Having a measurable performance indicator of each council/the overall proposal system

Here the only measure is % of council members showing up to votes, but we really don't need to do any burning to achieve this, it's something Pioneer would just need to surface directly, perhaps Pioneer v2 even does this? (don't recall now)

> Having some form of financial impact if proposals are not voted on

There is no impact on the relevant party: the council members, so there is still no reason to think they will really change their behavior. Their exposure to the dilution will be insignificant.

**Comment by mochet** [comment]
> There is no impact on the relevant party: the council members, so there is still no reason to think they will really change their behavior. Their exposure to the dilution will be insignificant.

This is true, but it does maybe have an impact on the community at large (provided the amount was significant enough)--which would in turn hopefully affect who is and isn't voted for in elections.
