### ISSUE TITLE
Giza: Storage bucket to bag assignment runtime - explanation

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#2895]
The issue was on the content module (so on my end). 
The `upload_assets_to_storage` helper function does the following:
1. Checks if a dynamic bag for the channel exists, if not it **creates a new one** accordingly
2. construct the `UploadParametersRecord` struct needed for the `upload_data_objects`
3. calls the `upload_data_objects` functions which can throw
4. if all the aboves succeed the `upload_assets_to_storage` helper returns `Ok(())`

If the assets objects size or number exceeds the storage bucket limits then the `upload_data_objects` function throws and so does the `upload_assets_to_storage` helper, leaving the bag created at step 1 dangling.
In a successive attempts to re-upload storage assets for the channel with the same id, the
`upload_assets_to_storage` helper checks at step 1 the existence of a bag for the channel and finding the previously created dynamic bag (referencing the same low-limit bucket) it still attempts to use it as designated bag for the channel.

**Comment by mnaamani** [comment]
Thanks for writing this up. Based on the current implementation of the storage module, I think that is the only approach that made sense by the content module. Because the content module does not have ability to interrogate the storage system to know if creating a bag and uploading some assets atomically would work. ie. The bag must be created first, and allocated to storage buckets before that can be known, with a call to `storage:can_upload_data_objects()`

A simple fix in content module is in `content:create_channel()`  on error adding assets to bag, call `storage:delete_dynamic_bag()` to delete the bag that was just created. This is sub-optimal (because storage module is causing events to be emitted as well as additional side affects related to deletion prize). It would be better to have an atomic operation in the storage module to `create_bag_with_assets()`

The root problem however should be address, which is touched on here is the fact that bucket allocation by storage module does not take into account required capacity. This is described in details here: https://github.com/Joystream/joystream/issues/2883
