### ISSUE TITLE
Governance blacklisting

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2927]
# Background

There are many early backers, FMs and Jsgenesis affiliates who are subject to vesting, and they may want to be able to provide a credible signal that they will not use their stake to influence governance, but while retaining their $JOY stake which is locked.

# Proposal

Add new extrinsic `blacklist_my_account` in election pallet that adds an account to a new map of type `AccountId => ()` , provided this account is signer origin and the account has some minimal  amount of $JOY, which also gets burned. Later, in voting, an account cannot be used if it is in this map, and there is no way to remove an account from this map.

If there is a cleaner approach, feel free to suggest.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202171668012554) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
# Goal
prevent certain accounts that have vesting to use their stake for influence council election

# Logic
- the council election is governed by the referendum pallet
- any account for which the `can_vote` guard returns `Ok(())` is allowed to vote
- adding a blacklist map `AccountId => ()` and modify teh `can_vote` guard accordingly will prevent certain accounts from voting
- an account will become blacklisted voluntarily with `blacklist_my_account` which will update the map with account
- no extrinsic will remove an account once blacklisted

# Questions
- we should allow only those account with min stake to be blacklisted (otherwise anyone can just pollute our storage with arbitrary number of account) ?

**Comment by bedeho** [comment]
> we should allow only those account with min stake to be blacklisted (otherwise anyone can just pollute our storage with arbitrary number of account) ?

No I don't think so.

**Comment by bedeho** [comment]
Done in Ephesus.
