### ISSUE TITLE
One-time staggered runtime rollout

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2948]
Most chains launch with limited functionality, and allow it to be updated in stages through proposals, I suggest we do the same. I propose the following stages, each one requiring some sort of proposal and some state variables that block relevant functionality.

# Sudo based
1. Enable membership module extrinsics & module calls.
1. Enable council & election extrinsics & module calls.

# Proposal based
1. Enable working group extrinsics & module calls. <- uses
1. Enable forum extrinsics & module calls
1. Remove Multisig Sudo key: does Sudo still break query node?
1. Enable token transfers.
1. Enable bounty module extrinsics & module calls.
1. Enable storage directory extrinsics & module calls
1. Enable content directory extrinsics & module calls.

_Note: any crowdloan claiming like code needs to be introduced here._

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201958630488698) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201958687417145/1201958630488698

**Comment by mochet** [comment]
Interesting reading on this topic: https://polkadot.polkassembly.io/referendum/59
`However, during the progressive launching process, the team noticed that there's no way to upgrade the runtime due to the misconfiguration in the genesis runtime. Specifically, the genesis runtime has both sudo and democracy disabled. Without the help from the relaychain side, the parachain will be "bricked" forever -- all the functions need to be enabled by runtime upgrades which is infeasible due to the problem.`

**Comment by bedeho** [comment]
Wow, that is .... pretty poor planning?
