### ISSUE TITLE
Add metadata to the create_bounty extrinsic

### ISSUE THREAD

**Issue by jodator** [Joystream/joystream#2961]
The `create_bounty` [extrinsic](https://github.com/Joystream/joystream/blob/273a6240b14d5c7cd9e234a227510e7b69c77ec3/runtime-modules/bounty/src/lib.rs#L727) parameters are missing `metadata` field:

[https://github.com/Joystream/joystream/blob/273a6240b14d5c7cd9e234a227510e7b69c77ec3/runtime-modules/bounty/src/lib.rs#L212-L240](https://github.com/Joystream/joystream/blob/273a6240b14d5c7cd9e234a227510e7b69c77ec3/runtime-modules/bounty/src/lib.rs#L212-L240)

The `metadata` should hold description-like fields for bounty, similarly to other entities like `Member` or `Proposal`. [https://github.com/Joystream/joystream/blob/273a6240b14d5c7cd9e234a227510e7b69c77ec3/runtime-modules/membership/src/lib.rs#L196-L197](https://github.com/Joystream/joystream/blob/273a6240b14d5c7cd9e234a227510e7b69c77ec3/runtime-modules/membership/src/lib.rs#L196-L197)

The `metadata` structure will be provided by @thesan while implementing the bounties schema for query-node.

**Comment by shamil-gadelshin** [comment]
The `create_bounty` extrinsic contains the metadata separated from the `BountyParameters` structure:         

https://github.com/Joystream/joystream/blob/273a6240b14d5c7cd9e234a227510e7b69c77ec3/runtime-modules/bounty/src/lib.rs#L727

We use separated parameters in order to reduce storage size because we don't need the metadata for the smart-contract logic - so we keep it externally in the form of the QueryNode data. @jodator

**Comment by jodator** [comment]
@shamil-gadelshin Thanks for the clarification. I don't know how, but I missed that on the `create_bounty` signature.
