### ISSUE TITLE
Are unsettled English auctions safe?

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2969]
I could not determine this off the top of my head, but we should ensure that the current owner cannot do anything malicious to the new winner who has yet to settle outcome of englis auction.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202207142926390) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
#### Scenario
1. Alice starts an english auction
2. Bob makes a english auction bid and the bids becomes the auction top bid
3. auction expires making Bob the effective winner
#### Potential conflicting transactions
Any of the following has the potential to change the nft on-chain state:
- `cancel_english_auction`: fails since we auction has Bob's bid
- `start_english_auction`: fails since nft status is not `Idle` but `EnglishAuction`
- `make_english_auction_bid`: fails since no longer possible since auction duration is expired
- `destroy_nft`: fails since nft status is not `Idle` but `EnglishAuction`
- `issue_nft`: fails since nft is already issued
- `delete_video`, `delete_video_as_moderator`: fail since nft for video is issued
- `update_video`: cannot be used to issue new nft since it requires the video not to have outstanding nft
- `delete_video_assets`: **this might be a problem** since owner can allow moderators to delete video assets even when nft is issued for that video
- `delete_channel`: fails since `channel.num_videos` has to be 0

#### Potential attacks
- Alice can delete video asset corresponding to the NFT while Bob is winner but has not  yet settled the english auction

**Comment by bedeho** [comment]
Nothing severe.
