### ISSUE TITLE
Merges Giza -> Olympia

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/joystream#3024]
* [x] #3025
-- Permission module has changed, in order to account for the new collaborator feature. Need to integrate permission for comments & reaction (should be easy).
-- Mainly refactoring in order to integrate old tests with current Fixture-based unit testing framework
* [x] #3026
-- Permission module has changed, in order to account for the new collaborator feature. an explicity guard for managing nft has been introduced so I presume it should not be too complex
-- Also the main `lib.rs` module should not represent a problem. Since most of the work is done on separate extrinsics.
* [x]  #2891

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703461475663) by [Unito](https://www.unito.io)

**Comment by ignazio-bovo** [comment]
ACK.
I just want to point out that basically:
```
Combine new content directory into Giza runtime  = Merge: Giza -> scalable channel payouts & Video Comments Creation + Merge: Branch1 -> Video NFTs => Output
```
So point 3 might be redundant

**Comment by dobertRowneySr** [comment]
Just for reference:
- starting branch `giza` (hopefully it will be merged with the staging branch soon). I have to use `giza` since it contains all the new fixes and it is well tested.
- `giza_feauture_VideoCommentsReaction` = `giza` + `video_comments_feature` branch
- `giza_feature_NewContentFeatures` = `giza_feature_VideoCommentsReaction` + `channel_payouts` branch
- `base_branch` = `giza_feature_NewContentFeatures` + `post_giza_content_dir` (nft branch)
- `olympia_giza` = `base_branch` + `olympia`
