### ISSUE TITLE
Question: Significance of missing storage side-effects as content directory event payload

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3084]
The content directory makes call to the storage system, however the side-effects of these calls, namely what data objects where created or dropped, or what bags were created or destroyed, and in what buckets, is not returned from the storage pallet, and thus also not part of content directory events.

This makes it harder to write correct mappings, as a single mapping cannot pickup everything needed to bind entities across content<-> storage boundary, you will need to do it across distinct mappings. In so far as this is correct, we should fix this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202000874282720) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
I think the only issue I faced when writing the mappings was w.r.t. to processing new assets created during channel / video creation/update, [where I had to make an assumption that `x` most recently created storage data objects correspond to the objects specified in `ChannelCreationParameters` / `VideoCreationParameters` / `ChannelUpdateParameters` / `VideoUpdateParameters`](https://github.com/Joystream/joystream/blob/e16937f1bb28a18630089472db84ea3107709fc7/query-node/mappings/content/utils.ts#L326), which due to some hydra limitations (ids are strings) required keeping track of the last inserted `dataObjectId` separately and making the processing logic a bit more complex and fragile in case of the runtime implementation changes.

**Comment by bedeho** [comment]
Ok, I think this comment literally says what I was saying

`// FIXME: Ideally the runtime would provide object ids in ChannelCreated/VideoCreated/ChannelUpdated(...) events`

**Comment by bedeho** [comment]
We need to discuss this and come up with an overall conclusion, but my current assumption is that the world would be much simpler for the query node mapping author if there were no events in utilty modules (i.e. modules only invoked inside the runtime), and instead have much richer events in the relevant subsystem (council, content, membership, etc.), where the relevance of a dataobjects is directly related to some high level concept like a proposal, membership, channel or video.

**Comment by Lezek123** [comment]
I believe there was only one issue that the current content-storage integration caused for the query node, which was about no object ids included in `VideoCreated`, `VideoUpdated`, `ChannelCreated`, `ChannelUpdated` events (as mentioned before). This was fixed in https://github.com/Joystream/joystream/pull/3454:
- `ChannelCreated` already included `Channel` struct as part of event payload, so it got fixed without any changes in the actual event (since `Channel` struct now contains `BTreeSet<DataObjectId>`).
- [fix for ChannelUpdated](https://github.com/Joystream/joystream/pull/3454/files#diff-530b6b5839302012b1dd920e330e8aed807c41206038f85b19bdf263ace7f349R2832)
- [fix for VideoCreated](https://github.com/Joystream/joystream/pull/3454/files#diff-530b6b5839302012b1dd920e330e8aed807c41206038f85b19bdf263ace7f349R2884)
- [fix for VideoUpdated](https://github.com/Joystream/joystream/pull/3454/files#diff-530b6b5839302012b1dd920e330e8aed807c41206038f85b19bdf263ace7f349R2890)

Other side-effects like removing data objects, creating/removing bags etc. can be handled independently through storage events:
- `DynamicBagCreated` is emitted on channel bag creation. The event includes all the necessary data to assign the bag to existing storage/distribution buckets.
- `DataObjectsUploaded` is emitted when new data objects are assigned to a bag. The event includes all the necessary data to assign the objects to an existing bag (we don't know what `type` of object it is at this point, but this field can be easily updated later during `(Channel|Video)(Created|Updated)` event processing).
- `DataObjectsDeleted` is emitted when data objects are dropped. Currently we're using [`unsetAssetRelations`](https://github.com/Joystream/joystream/blob/master/query-node/mappings/src/content/utils.ts#L475) to make sure all relations with video/channel are unset before we remove the object from the query node database. This is a bit suboptimal, but arguably the best solution for this is to have [`SET NULL on delete`](https://www.techonthenet.com/sql_server/foreign_keys/foreign_delete_null.php) clause on fields like `video.thumbnailPhoto`, `video.media`, `channel.coverPhoto` and `channel.avatar`. This is currently not supported in Hydra, but could be introduced in order to get rid of this workaround.
