### ISSUE TITLE
Forum bug: Posts can be moderated w/o category permissions

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3111]
[`ensure_can_moderate_post`](https://github.com/Joystream/joystream/blob/olympia/runtime-modules/forum/src/lib.rs#L1739) doesn't check whether the category provided as `moderate_post` extrinsic arg is actually the thread's (and post's) parent category.

Because of this a moderator can moderate posts in any category as long as (s)he has access to at least 1 category, by providing a valid `threadId` and `postId` and (possibly completely unrelated) `categoryId` of the category to which (s)he actually has the access.

**Example:**
There are 2 unrelated categories: `1` and `2`. The moderator has access to category `2`. There is a thread with id `1` in category `1` and a post with id `1` in thread `1`. The moderator can moderate post `1` even though (s)he doesn't have access to category `1` by sending  `moderate_post` extrinsic with `categoryId=2`, `threadId=1` and `postId=1`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202453799757161) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
# Background

There was an attempt to fix this issue in this PR, which generated a longer discussion

https://github.com/Joystream/joystream/pull/3125

# Summary 

Here is a summary of my view of the core set of problems in the `Olympia` branch.

## Primary Problem

Threads can be deleted, however, they are the link from posts to categories, and thus once a thread is deleted, there is no way to authenticate whether a given moderator genuinely is allowed to moderate a given post.

## Secondary Problem

As a means to sidestep this case, there are two parts of the codebase which temporarily as part of the codeflow injects a default constructed `post` 

```Rust
<PostById<T>>::get(thread_id, post_id)
```

, hoping to deleted it later. In one case, this is fine, in the other it allows for side-effects in a failed extrinsic, which is catastrophic.

### OK Case: `moderate_post` 

1. `moderate_post` is called on a post in a thread which has been deleted.
2. `ensure_can_moderate_post` will then be called.
3. Since `thread_exists` will fail, this `post` will be injected in storage
https://github.com/Joystream/joystream/blob/olympia/runtime-modules/forum/src/lib.rs#L1762
4. It is however guaranteed to get removed again in this mutation call, as there is no failure which can happen between the two points in the code path
https://github.com/Joystream/joystream/blob/olympia/runtime-modules/forum/src/lib.rs#L1467

### Bad Case: `delete_posts`

1. `delete_posts` is called on a post in a thread which has been deleted.
2. `ensure_can_delete_post` will be called _for each post provided_
3. Since `thread_exists` will fail, this `post` will be injected in storage https://github.com/Joystream/joystream/blob/olympia/runtime-modules/forum/src/lib.rs#L1783

What is obvious here is that there are two checks that can fail for the same or a subsequent post to be deleted in the extrinsic call
- caller can't sign for claimed owner: https://github.com/Joystream/joystream/blob/olympia/runtime-modules/forum/src/lib.rs#L1787
- claimed owner is not real owner and post is not in open season: https://github.com/Joystream/joystream/blob/olympia/runtime-modules/forum/src/lib.rs#L1791

# Way Forward

We simply 

1. block the ability to delete a thread if `Thread::number_of_posts > 0`. 
2. update `ensure_can_moderate_post` so that it does not accept the possibility that the thread does not exist due change in 1, thereby you can always authenticate whether a given moderator genuinely is allowed to moderate a given post.
3. make sure we never do this `<PostById<T>>::get(thread_id, post_id)`, which should not be needed

With rule 1, you can always figure out what thread a post lives in, and the primary moderation problem goes away. Likewise, since `thread_exists` will always pass,  (silent check, no failure needed), the two secondary problems go away. I was initially hesitant about this fix a while back actually, but that was because I thought that this would block moderation of a non-empty thread, which could be an attack, however, I forgot that the first post is not part of the core thread object, it is a separate post, like all others, so there is no moderation problem here 🎈 . 

No runtime migration is required if we just make sure that no threads are deleted in the interim, so better to go for that option.

**Comment by Lezek123** [comment]
Addressed by https://github.com/Joystream/joystream/pull/3992
