### ISSUE TITLE
Olympia: Update, and migrate, user guides

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#3179]
Will be partially delegated to the community.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201775418798107) by [Unito](https://www.unito.io)

Edit:
---
- [ ] Validators/nominators:
    - We will need to update validation and nomination tutorials to reflect that users must go to the new external apps instance which Leszek will try to prepare our ability to use.
- [ ] "General" Pioneer 2.0 
   - Accounts, membership, election/council, proposals, WG applications, etc.
   - Hopefully not that granular, as pioneer 2.0 should be easier to navigate. 
- [ ] Storage WG (from helpdesk)
- [ ] Distributor WG (from helpdesk)
- [ ] Curators WG  (from helpdesk, updates required)

**Comment by bedeho** [comment]
This needs more detail, what guides are we talking about? there is a new handbook now which should incorporate this

https://joystream.gitbook.io/testnet-workspace/

, no more helpdesk, so please outline a more granular plan on what needs to be done, and only take into account what is needed for you to do as a precondition for launching olympia.

**Comment by bedeho** [comment]
Since there is some free time early next week, perhaps you can take a stab at writing out scoring rules for these 

- [ ] **Content Directory:** https://joystream.gitbook.io/testnet-workspace/testnet/council-period-scoring/content-directory-score
- [ ] **Marketers:** https://joystream.gitbook.io/testnet-workspace/testnet/council-period-scoring/marketers-score
- [ ] **Distributors:** https://joystream.gitbook.io/testnet-workspace/testnet/council-period-scoring/distributors-score
- [ ] **Builders:** https://joystream.gitbook.io/testnet-workspace/testnet/council-period-scoring/builders-score

Using the following completed examples
- **Council:** https://joystream.gitbook.io/testnet-workspace/testnet/council-period-scoring
- **General:** https://joystream.gitbook.io/testnet-workspace/testnet/council-period-scoring/general-working-group-score
- **HR WG**: https://joystream.gitbook.io/testnet-workspace/testnet/council-period-scoring/human-resources-score
- **Storage WG:** https://joystream.gitbook.io/testnet-workspace/testnet/council-period-scoring/storage-providers-score
