### ISSUE TITLE
Solve BountyCreated and NftIssued event decoding problem

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3236]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201835891534474) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Related issue: https://github.com/Joystream/joystream/issues/3231

**Comment by Lezek123** [comment]
Turned out to be unrelated to `BTreeSet` type beeing nested inside `Enum`, which was prematurely assumed to be the cause of the `BountryCreated` and `NftIssued` event decoding errors.

Both events had independent type definition problems which were fixed in https://github.com/Joystream/joystream/pull/3268.
