### ISSUE TITLE
Tweak NFT open auction featuers

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3285]
Specifically

1. Allow multiple simultaneous bids, but at most one per member.
1. Allow a member to update the amount associated with their bid, either up or down. **Reducing the amount can only be done when the bid locking period period has passed, however increasing the amount can be done at any time.**
1. The owner can select _any_ active bid as the winner, regardless of the amount associated with the bid. Remember that when owner is accepting a bid, this acceptance must commit to the current bid amount, to avoid front-running type attack where the winning bidder races to reduce the bid amount.
1. It must be possible to cancel any non-winning bid even after the auction has been settled, this is how the losers get their money back. Bid locking period still applies to cancellations.
1. Drop minimal bid step for open auction.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201899819496282/1201900104475634) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
Quick thought that popped into my head wrt those changes. Previously, when new bid was placed we would [validate it](https://github.com/Joystream/joystream/blob/olympia/runtime-modules/content/src/nft/types.rs#L252) to make sure `(NEW_BID - LAST_BID) > MIN_BID_STEP`. However, I think this logic doesn't really apply anymore? Since we said we want members to be able to freely increase/decrease their bids in an open spirit, do we need any validation at all, other than making sure bid is bigger than min price? I would say no, consequence of that would be that `minimalBidStep` is unused in context of an open auction. Would it make sense to say this `minimalBidStep` exists only for an english auction then?

**Comment by bedeho** [comment]
Yes, this is not even optional, its a must if we are going to allow arbitrary bid amount changes, like reductions.

**Comment by kdembler** [comment]
I'm not fully sure I understand your comment, are you saying that you agree we move `minimalBidStep` to English auction details and remove it in context of an open auction?

**Comment by bedeho** [comment]
# Yes <3

**Comment by kdembler** [comment]
How do we handle withdrawing from past auctions? It's possible that since I placed my bid, the auction have already ended and a new one has started. Will we need some way to identify an auction when requesting bid withdrawal?

**Comment by bedeho** [comment]
> How do we handle withdrawing from past auctions? It's possible that since I placed my bid, the auction have already ended and a new one has started. Will we need some way to identify an auction when requesting bid withdrawal?

Ah, very good point, you are saying if a new auction starts, I should not have my bid be open to being accepted for that auction? I did not think of that indeed. This will require us to introduce a nonce, or just an auction counter, field in the NFT, and then bid have to be locked not only to a specific video, but also auction ID. When the owner tries to accept the bid, the runtime will verify that the bid corresponds to the current auction. Lastly, bids are stored in a map where the key space is `MemberIdxAuctionId`. This allows for efficient verification of whether a given member already has an active bid in a given auction, something we want to restrict to 1. `AuctionId` space is global, so all auctions for all NFTs use the same value range.

**Comment by kdembler** [comment]
> you are saying if a new auction starts, I should not have my bid be open to being accepted for that auction?

I haven't suggested that exactly, but indeed seems to be one of possible solutions.

Let's assume NFT `X` is put on an open auction `A1` and member `M` places their bid. `X` owner picks a winner but it's not `M`, so `M` have a bid to withdraw. Let's say the new `X` owner, that won `A1`, starts a new auction `A2`, for the same NFT `X`. At this point I think we could follow two approaches:
1) `M` is not allowed to place a bid on `A2`, until they withdraw their bid from `A1`
2) `M` is allowed to place a bid on `A2`, and can withdraw bid from `A1` at a later point

If we pick 1), then I guess runtime will need to be able to check whether `M` has an active bid on any past auction for `X`. If it can do that, then when withdrawing a bid, `M` wouldn't need to identify an auction, because that creates a constraint of one bid per member per NFT, not per auction.

If we pick 2), then during withdrawal, `M` would need to specify which bid they want to cancel, the one from `A1` or `A2`.

From my product perspective, I'm fine with both so I would suggest we do the lowest-effort thing from runtime perspective. 1) would require slightly more design changes

**Comment by bedeho** [comment]
- In terms of user goals, I don't see any utility in having multiple outstanding - but expired, bids for an NFT, hence 1) seems to make most sense, however, I think I would just interpret it as replacing (which we already want to allow), rather than withdraw+insert. I would assume this would be _less_ design work, not more, as you don't need to show a range of bids, or have the ability to select one among many bids. So I'm hoping that was a typo. The main change to my prior solution would just be to have key space `MemberIdxVideoId` instead of `MemberIdxAuctionId`.
- I think it's still wise to solve the problem I was concerned about: your bid getting accepted in a much later auction you did not intend, for example if you just forgot to withdraw.

**Comment by kdembler** [comment]
> as you don't need to show a range of bids, or have the ability to select one among many bids

We already have this design, for this case that's why I said it would be less design work. You can see it [here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1247%3A107861). 

> I think it's still wise to solve the problem I was concerned about: your bid getting accepted in a much later auction you did not intend, for example if you just forgot to withdraw.

Yes, fully agreed

**Comment by bedeho** [comment]
> We already have this design, for this case that's why I said it would be less design work. You can see it [here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1247%3A107861).

But this is going even further, this is allowing multiple bids being possibly valid in the same auction, I don't think that really makes sense, that is why I suggested 1). Anyway, regardless of the marginal design cost, 2 should still be very low (basically dropping screens and alternatives entirely).

**Comment by dobertRowneySr** [comment]
> > you are saying if a new auction starts, I should not have my bid be open to being accepted for that auction?
> 
> I haven't suggested that exactly, but indeed seems to be one of possible solutions.
> 
> Let's assume NFT `X` is put on an open auction `A1` and member `M` places their bid. `X` owner picks a winner but it's not `M`, so `M` have a bid to withdraw. Let's say the new `X` owner, that won `A1`, starts a new auction `A2`, for the same NFT `X`. At this point I think we could follow two approaches:
> 
>     1. `M` is not allowed to place a bid on `A2`, until they withdraw their bid from `A1`
> 
>     2. `M` is allowed to place a bid on `A2`, and can withdraw bid from `A1` at a later point
> 
> 
> If we pick 1), then I guess runtime will need to be able to check whether `M` has an active bid on any past auction for `X`. If it can do that, then when withdrawing a bid, `M` wouldn't need to identify an auction, because that creates a constraint of one bid per member per NFT, not per auction.
> 
> If we pick 2), then during withdrawal, `M` would need to specify which bid they want to cancel, the one from `A1` or `A2`.
> 
> From my product perspective, I'm fine with both so I would suggest we do the lowest-effort thing from runtime perspective. 1) would require slightly more design changes

Nonce for the auction is required in both cases, since `complete_auction` utility function used in the runtime sets the `Nft::<T>::transactional_status` to `Idle`, effectively losing all the previous bids history. So it is not possible to withdraw funds after an auction is closed.

One simple but costly way to overcome the extra storage space is to release all the bids for the auction upon completion but that jacks up weights for the extrinsic of `O(#bids_for_auction)`.
@bedeho @kdembler

**Comment by bedeho** [comment]
> Nonce for the auction is required in both cases

Correct.

> One simple but costly way to overcome the extra storage space is to release all the bids for the auction upon completion but that jacks up weights for the extrinsic of

This is not feasible.
