### ISSUE TITLE
Idea: User selects buckets

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3289]
There is a lot of complexity around trying to do random sampling of both storage and distribution buckets, and it also leads to more expensive interactions with the storage system. What if the user would provide the buckets to use, and the runtime simply verified that the selection was compatible with current constraints? For example that there is sufficient redundancy in storage buckets.

I can't see any serious issue security risks of doing this, and it would open up the opportunity for clients to exercise some judgement about what storage hosts act as good liasons.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1201871056332439) by [Unito](https://www.unito.io)

**Comment by bwhm** [comment]
@bedeho 

For storage: 
- Are we talking about new bags only, or for adding data to existing bags?
- Are we talking about which bucket you want upload to only or which bucket(s) will hold your bag? 

There are many potential pitfalls here, so let's see if we can narrow it down first...

Do you want this to apply to distribution as well?

**Comment by bedeho** [comment]
> Are we talking about new bags only, or for adding data to existing bags?

New only.

> Are we talking about which bucket you want upload to only or which bucket(s) will hold your bag?

This is already the case, no change, user already picks this.

> Do you want this to apply to distribution as well?

Yes.

**Comment by bwhm** [comment]
As discussed briefly in person:

### Storage
There are at least two clear constraints you'll have to adhere two:
- the bucket status of all the buckets you select must allow new bags
- the `StorageBucketsPerBagLimit`, ie. the maximum number of buckets a single bag can be in, is not violated

Depending on how this is implemented, the dynamic bag policy **may** also be a constraint here. By that, I mean it's not clear to me whether this would count as a dynamic bag policy, in the sense that it isn't the runtime assigning this, but the users themselves. This can be solved in one of (at least) two ways.

1. Selecting buckets yourself is constrained by the dynamic bag policy:
   - Suppose the dynamic bag policy is `n`, and the user selects `m` buckets.
   - The user selects `m = n` buckets themselves, and all is well.
   - The user selects `m < n` buckets, and the runtime selects the remaining `n-m`.
   - The user selects `m > n` buckets (while not  exceeding the `StorageBucketsPerBagLimit`). This imposes an extra cost on the system, and if we allow it, they should arguably pay more to store their data. However, the Lead may at any point remove this bag from some buckets, so it wouldn't necessarily impose significant costs on the storage system. There's arguably more work for the Lead though, so I'd say we don't allow setting `m > n`.

If this approach sidesteps the whole dynamic bag policy, they can select `1 <= m <= StorageBucketsPerBagLimit`. In any case, this puts some extra workload on the Lead, as they might "need" to update the bag, by adding or removing it from/to some buckets. Simply because the Lead wants some specific redundancy. 

#### Conclusion
I don't know what's more work on the runtime side, but it seems preferable to let the user choose any number of buckets smaller or equal the current dynamic bag creation policy. 

I've avoided the issue about filling up a bucket, as this would apply equally to the dynamic bag creation as is.

### Distribution
For distribution, it seems a little more fragile. I can't really explain why in a succinct way `*`, but I honestly can't understand how a user is supposed to select anything reasonable here. I guess it can't really hurt assuming they're made to follow the dynamic bag policy anyway.

`*` Example:
A dynamic bag policy alone will have to be rather restrictive, as most (>99%) of new videos will not get "many" views. For a very popular channel, a new video will of course get lots of views when uploaded, but that doesn't mean that the old videos in their channel will get anywhere near the amount of views over that same time period. I guess this is where caching comes in to play, as all video/bucket configuration happens with bags as a middleman.

**Comment by shamil-gadelshin** [comment]
The code was merged.
