### ISSUE TITLE
Introduce Channel/Video -> BTreeSet<DataObjectId> association in the runtime state

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3380]
To solve https://github.com/Joystream/joystream/issues/2936 we need to introduce some state in the content directory to map data objects to specific channel/video in order to determine whether the actor is trying to remove a data object associated with a video that already has an nft issued (or channel that has some creator tokens issued).

The initial idea is to add `objects: BTreeSet<DataObjectId>` to `Channel` / `Video` entity and initialize/update the set on:
- `create_channel`
- `create_video`
- `update_channel`
- `update_video`

**_Note that this will only work if there are no other extrinsics (especially outside of the content pallet) through which it is possible to remove data objects that live inside a channel bag (not counting extrinsics that remove the entire `Channel` / `Video` entity along with all it's data objects, ie. `delete_video`, `delete_channel`)_**

Then we validate the existence of data object ids provided as `assets_to_remove` arg for:
- `update_video`
- `update_channel`

In given `Channel` / `Video` `objects` set.

We could also change the signature for `delete_video` to take `num_objects_to_delete` instead of `assets_to_remove` in order to:
- Be consistent with `delete_channel`
- Make sure all video assets are always removed along with the video
- Reduce the size and complexity of the parameters that need to be provided to the extrinsic

Introducing this state opens the door for preventing the removal of data objects associated with the video / channel depending on:
- video's nft status
- channel's creator tokens status
- whether the object is associated with a video (video media / thumbnail) or a channel (avatar / cover photo)

And (optionally) for introducing separate curator permissions (see: https://github.com/Joystream/joystream/issues/2760) for removing data objects depending on those conditions, for example:
- `DELETE_VIDEO_DATA_OBJECT_NO_ASSOCIATED_ASSETS` (allow deleting video data object in case channel has no creator tokens issued and the video has no nft issued)
- `DELETE_VIDEO_DATA_OBJECT_NFT` (allow deleting video data object in case video has an associated nft issued)
- `DELETE_VIDEO_DATA_OBJECT_CREATOR_TOKENS` (allow deleting video data object in case channel has creator tokens issued)
- `DELETE_ CHANNEL_DATA_OBJECT_NO_ASSOCIATED_ASSETS` (allow deleting channel data object in case channel has no creator tokens issued)
- `DELETE_CHANNEL_DATA_OBJECT_CREATOR_TOKENS` (allow deleting channel data object in case channel has some creator tokens issued)

**Comment by bedeho** [comment]
> Note that this will only work if there are no other extrinsics (especially outside of the content pallet) through which it is possible to remove data objects that live inside a channel bag

I guess the `storage` pallet would be the other natural candidate, I don't remember whether it has a deletion extrinsic.

**Comment by bedeho** [comment]
Question, do you really need to update the new `objects` on calls to

- `delete_channel`: if this works, no videos exist, and the channel is gone, so no `objects` exist for this channel
- `delete_video`: if this works, the video is gone, hence `Video::objects` is gone, and `Channel::objects` should not be affected?
- `delete_channel_as_curator`: same
- `delete_video_as_curator`: same

**Comment by bedeho** [comment]
> Then we validate the existence of data object ids provided as assets_to_remove arg for:

For `update_video` I assume this is to prevent someone from deleting a dataobject by doing a deletion via a different video? 

For channels I guess it is automatically ensured, isn't it? because data objects from different channels live in distinct bags?

**Comment by Lezek123** [comment]
> Question, do you really need to update the new objects on calls to
> delete_channel: if this works, no videos exist, and the channel is gone, so no objects exist for this channel
> delete_video: if this works, the video is gone, hence Video::objects is gone, and Channel::objects should not be affected?
> delete_channel_as_curator: same
> delete_video_as_curator: same

Good point, there's no need to update the set in case of channel/video deletion, I'll update the description.

> For update_video I assume this is to prevent someone from deleting a dataobject by doing a deletion via a different video?

Yes

> For channels I guess it is automatically ensured, isn't it? because data objects from different channels live in distinct bags?

Data objects associated directly with a channel and data objects associated with all videos in this channel live in the same bag, so one could potentially use `update_channel` to remove assets associated with a video that has an nft issued (which should not be possible) if we didn't perform this check. Besides that I think it's a good idea in general to prevent the removal of video assets using `update_channel` extrinsic, as this just seems "out of scope" of what the extrinsic was meant for.

**Comment by bedeho** [comment]
> so one could potentially use update_channel to remove assets associated with a video that has an nft issued

Oh snap, missed that one, well done sir :)

**Comment by bedeho** [comment]
At the risk of going in circles on this topic:

Perhaps we need to be a bit more nuanced here.

- Unconditional prevention of asset deletion for issued NFTs makes a ton of sense for when we are talking about the issuer, they have to be constrained post-issuance.
- Unconditional prevention of moderators makes much less sense, because now we have the old problem of issuing an NFT becoming an attack to force hosting of assets. Even if we imagine distributors not distributing it, I don't think that is really good enough.

Now I still think the iron clad guarantee that _digital assets_ (both fungible and not) cannot be destroyed by non-owners is important, but this is different from saying that the storage assets (i.e. data objects) will be hosted by the system. So how about we introduce, as originally planned

- **DELETE_CHANNEL_OBJECT**: instantly delete a data objects from the channel bag.
- **DELETE_VIDEO_OBJECT**: instantly delete a data objects from the channel bag which corresponds to a given video.

These actions and maintain the data object mappings we already introduced.

I grant that its sort of a weird middle point, who cares about an NFT without its pivotal metadata? But it just seems strictly better than the only two other options I can imagine:
a) storing **_anything_** anyone wants in perpetuity.
c) allowing of whole sale deletion of the core NFT itself, which then causes weird issues when an NFT perhaps has been teleported to some other chain/CEX and other interoperability cases.

**Comment by mochet** [comment]
> c) allowing of whole sale deletion of the core NFT itself, which then causes weird issues when an NFT perhaps has been teleported to some other chain/CEX and other interoperability cases.

I think the teleported part is important, as well as the fact the record of the NFT having been created will also remain (which effectively allows for recreation of an NFT in some way).

Deleting the NFT itself seems pointless in light of these 2 factors.

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/3454
