### ISSUE TITLE
Finalize genesis token supply and $JOY denomination

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3389]
# Background
So far, we have not pinned down the token supply, and actually operated with a denomination where $JOY was the base currency unit (i.e. Satoshis of Joystream).

# Proposal
* **Token Asset Name:** $JOY
* **Base Unit Name:** BDH (joking :rofl:  ... seriously we need a name here...! ask Atlas God-King kdembler or ask community?)
* **$JOY Token Denomination:** 10,000,000,000 (ten Billion) BDH
* **Initial $JOY supply:** 1,000,000,000 (1 Billion) $JOY
* **Initial BDH supply:** **Initial $JOY supply** x **Token Denomination** = 1e^19 BDH

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202170658944694) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Base Unit Name suggestions:
 `Hapi` ? Lots of `HAPI`s  you get `JOY` :D
 `Smile`s

**Comment by adovrodion** [comment]
MNT (minute)
MMT(a moment)

**Comment by narniec** [comment]
JOL (jollity)

**Comment by mrexpat** [comment]
`Bite` - take a bite of $JOY

**Comment by lionff** [comment]
Fun
STR

**Comment by mnaamani** [comment]
> Fun STR

STR as in "Stream" ?

**Comment by TCzechowski** [comment]
`XD`'s.
Lots of XD's = JOY

Or let's switch things around... call base unit a `JOY`, and `XD` as a token name. This way we also get the full scalability:

1000 `XD` = 1 `XDD`
1000 `XDD` = 1 `XDDD`
etc.

(I'm ofcourse joking, please don't take it seriously 🤣)

**Comment by blrhc** [comment]
`GDM` or `GAU` (_gaudium_ is "joy" in latin) ?
links to the ancient civilisation branding a bit, if we are keeping that

`GLI`(s) (as in glee)

**Comment by blrhc** [comment]
`GLAD` <- less intense than joy(ful), so maybe works as a sub-unit.

**Comment by Arsi44** [comment]
Stream-coin (STC)
"coin" word makes itself less important compared to Joy.
So Joy contains of Stream-coins

Moreover, it is combined with the name of the project.

**Comment by mnaamani** [comment]
`Giggle`s

**Comment by spatsochi** [comment]
My opinion is that the application is convenient for calculating tokens with a small coin issue and high capitalization  such as Btc , dash , zec . 1 billion joystream tokens is too much for this adoption , imagine if the capitalization reaches at best $ 1 billion , and what next? 1 joy will be equal to $ 1, and if we divide $ 1 by 10 times, we will get a very low figure, besides, if we are looking for a solution, then the name itself is not a ticker, let's say btc = satoshi, I have not met a ticker in satoshi, for Joy I would choose the name streams , votes or joynirium , daonirium ))

**Comment by yasiryagi** [comment]
1 Joy = 1000000 uJOY

On the Joy theme 
Grin
Bliss

**Comment by shtihmas** [comment]
Token Asset Name: $JOY
Base Unit Name: STREAM

**Comment by Xandrell** [comment]
Token Asset Name: $JOY
Base Unit Name: like

**Comment by jen4ph** [comment]
Base unit name:
1. Gene - from JSGenesis, also in biology gene is the basic physical and functional unit of heredity
2. Jolt - from nothing 😅

**Comment by igrexac** [comment]
I like version: **frame (FRM)** as the minimum video element

**Comment by leetjoy** [comment]
Token asset - $JOY
Base unit - LJOY (Lil joy)

**Comment by oleksanderkorn** [comment]
`nJOY` which sounds like `enjoy` but means `nano-joy`

**Comment by mmsaw** [comment]
JST

**Comment by bwhm** [comment]
> `nJOY` which sounds like `enjoy` but means `nano-joy`

It's hard to top that on in terms of how if sounds. Should work well wrt to fees as well.

**Comment by OIgnt** [comment]
Yeah, nJOY sounds really cool from different points of view :)

**Comment by kdembler** [comment]
Really like this idea, although it will force us to modify the token denomination, which we originally planned to be `10,000,000,000 (ten Billion)`, same as Polkadot. `nJOY` would force us to change that to `1,000,000,000 (one Billion)`, since that's what the `nano` prefix stands for. Maybe not a big issue, although we may need to re-run calculations to make sure this works.

**Comment by bedeho** [comment]
# Conclusion

We are going with the initial suggestion, but name will still be selected by @kdembler

**Comment by dmtrjsg** [comment]
Looks like we've arrived to a conclusion here, so closing in favour of actual work to commence on this ticket: 

- https://github.com/Joystream/joystream/issues/3390 (Runtime)
- https://github.com/Joystream/atlas/issues/2277 (Atlas)
- https://github.com/Joystream/pioneer/issues/2531 (Pioneer)

**Comment by bwhm** [comment]
https://github.com/Joystream/pioneer/issues/2540

**Comment by bwhm** [comment]
If we want to be added to `subkey`, we need to make a PR to [here](https://github.com/paritytech/ss58-registry). Examples etc. can be found in the repo.
Although it may take quite a while to get us included in the "official" `subkey`, they quite frequently update the registry in the [substrate repo](https://github.com/paritytech/substrate/search?q=ss58_registry&type=commits).

Assuming we go with @bedeho's suggestion:
```
   {
      "prefix": i,
      "network": "joystream",
      "displayName": "Joystream Mainnet",
      "symbols": ["JOY"],
      "decimals": [10],
      "standardAccount": "*25519",
      "website": "https://joystream.org"
    },
```

Where `i` is the address encoding, and determine its prefix. I've checked for the potentially "interesting" prefixes (with the lowest `i` if there are many), and found :
- `j.*` -> [126,127,129,130,132,133,134] //Only checked for the lowest available here -> 128 and 132 are claimed
- `J.*` -> not possible
- `js.*` -> [4997,5253,5509,6021,6277,6533,6789,7045]
- `jt.*` -> [7557,7813,8069,8325]
- `jn.*` -> [9092,9348,8580,8836]
- `jo.*` -> [11140,11396,11652,11908]

**Comment by bwhm** [comment]
@mnaamani 
I think we can [test this already](https://github.com/Joystream/joystream/blob/c57054eebe5da4f683134dbdaaecf50263ec7336/node/src/chain_spec/mod.rs#L187) by adding:

```
    properties.insert(
        String::from("ss58Format"),
        json::Value::Number(json::Number::from(126)),
    );
```
and changing the decimals.

**Comment by bwhm** [comment]
LOL! #181 
Didn't try to steal the credit here, hadn't seen this :D

**Comment by bwhm** [comment]
@Lezek123 
Can you please confirm my findings [here](https://github.com/Joystream/joystream/issues/3389#issuecomment-1157327600)? Namely;
1. Prefix `126` does indeed always give a `j.*` address
2. As a backup in case it gets picked while we are discussing, that this holds true for 127,129,130, and 132-134 as well.

If possible, it would be nice to also deploy a chain with these values for testing purposes, but that's not as urgent.

**Comment by bedeho** [comment]
@bwhm These posts seem like they are in the wrong issue, shouldn't this be in #3786 or somewhere else?

**Comment by bwhm** [comment]
#3786 was closed, so I didn't see it. Two of the inputs were already being discussed here.

**Comment by bedeho** [comment]
Ok, https://github.com/Joystream/joystream/issues/181 took over though, so can we move this there? its more orderly.

**Comment by Lezek123** [comment]
> Can you please confirm my findings https://github.com/Joystream/joystream/issues/3389#issuecomment-1157327600? Namely;
> Prefix 126 does indeed always give a j.* address
> As a backup in case it gets picked while we are discussing, that this holds true for 127,129,130, and 132-134 as well.

Short answer: Yes, it's correct

### The proof

#### Prefix = 126

If you take a look at the [implementation of address encoding in `@polkadot/util-crypto`](https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/address/encode.ts), you will notice that if the prefix `> 64` then the first 2 bytes of `base58Encode` input are deterministic, namely:
```typescript
  const input = u8aConcat(
    ss58Format < 64
      ? [ss58Format]
      : [
        ((ss58Format & 0b0000_0000_1111_1100) >> 2) | 0b0100_0000,
        (ss58Format >> 8) | ((ss58Format & 0b0000_0000_0000_0011) << 6)
      ],
    u8a
  );
```

In case of `126` prefix the first 2 bytes are: `[95, 128]`

You will also notice that the length of `base58Encode` parameter:
```typescript
  return base58Encode(u8aConcat(input, sshash(input).subarray(0, [32, 33].includes(u8a.length) ? 2 : 1)));
```
Is `36` provided that `encodeAddress` input is `32` bytes long (2 bytes prefix + 32 bytes + 2 bytes checksum)

The input for `encodeAddress` is always `32` if we're:
- encoding Sr25519 public key (since `Sr25519` public key is always 32 bytes)
- encoding Ed25519 public key (since `Ed25519` public key is always 32 bytes)
- generating a corresponding substrate address for `Ecdsa` public key (because although `Ecdsa` public key is > 32 bytes, `blake256(ecdsaPubKey)` is used as input when generating a substrate Ecdsa address, as described [here](https://github.com/substrate-developer-hub/knowledgebase/blob/master/current/integrate/subkey.md))

Now what remains is to prove that the result of `base58` encoding any 36 bytes sequence that starts with `[95, 128]` is always going to start with `j`.

In order to prove this it's enough to just understand than base58 encoding of a sequence of bytes is basically just a conversion from 256-base number to 58-base number, where `base58` specification provides the alphabet that allows convering each position in the 58-base number to a symbol (this is probably better explained in [this article](https://medium.com/concerning-pharo/understanding-base58-encoding-23e673e37ff6))

Thinking about it in the decimal realm: we could convert the input bytes to one huge decimal number and then convert this decimal number to a 58-base number and we'll get the base58 representation of the bytes.

The decimal representation of 36 bytes sequence that starts with `[95, 128]` is therefore:
```
decimalNumber =
  95 * 256^35 +
  128 * 256^34 +
  (0-255) * 256^33 +
  ... +
  (0-255) * 256^0
```
_(0-255) here represents a number between 0 and 255_

In order to convert this to 58-base number we'd basically do something like:
```
x = decimalNumber;
do {
  result.unshift(x % 58)
  x = x / 58
} while (x > 0)
```

So I went ahead and created a script in JS that basically:
- calculates the minimum value of `decimalNumber` (under the assumptions described above) - we'll call it `minNumber`
- calculates the maximum value of `decimalNumber` (under the assumptions described above) - well call it `maxNumber`
- keeps dividing `maxNumber / 58` and `minNumber / 58` until `minNumber == maxNumber`
- prints `minNumber` (which is same as `maxNumber` at this point)

This lets us find at which point the remaining base-58 positions (starting for them end) become a deterministic sequence, regardless of the value of other bytes after `[95, 128]`.

The script looks like this:
```javascript
import BN from 'bn.js'

let len = 36;

let firstByte = 95;
let secondByte = 128;

let minNumber = (new BN(256)).pow(new BN(len - 1)).muln(firstByte)
    .add((new BN(256)).pow(new BN(len - 2)).muln(secondByte));
let maxNumber = minNumber;
// Calculate the maxNumber - all remaining bytes are 0xff (255):
for (let i=len-3; i>=0; --i) {
    maxNumber = maxNumber.add((new BN(256)).pow(new BN(i)).muln(255))
}

do {
    minNumber = minNumber.divn(58);
    maxNumber = maxNumber.divn(58);
} while (!minNumber.eq(maxNumber));

console.log('min', minNumber);
```

And the printed out result is `2439`.

This means that is we keep dividing a decimal-number representation of 36-bytes sequence that starts with `[95, 128]`, at some point it just deterministically becomes `2439`.

If we follow from that point on, well get:
```
2439 % 58 = 3
result.unshift(3)
2439 / 58 = 42

42 % 58 = 42
result.unshift(42)
42 / 58 = 0

# end of the loop
```

So we can be sure that the `base58Encode` result is:
```
[42, 3, ...]
```

Which according to the [base58 alphabet](https://tools.ietf.org/id/draft-msporny-base58-01.html) is:
```
j4...
```

#### Other prefixes (127,129,130, and 132-134)

I ran similar proofs as described in the previous subsection for the other prefixes, using a slightly modified script:
```typescript
import BN from 'bn.js'
import { encodeAddress } from '@polkadot/util-crypto';

let prefixes = [127, 129, 130, 132, 133, 134];
let len = 36;

for (let prefix of prefixes) {
    let firstBytes = [(prefix & 0b0000000011111100) >> 2 | 0b01000000, prefix >> 8 | (prefix & 0b0000000000000011) << 6];

    let firstByte = firstBytes[0];
    let secondByte = firstBytes[1];
    
    console.log('prefix', prefix);
    console.log('fb, sb:', firstByte, secondByte);

    let minNumber = (new BN(256)).pow(new BN(len - 1)).muln(firstByte)
        .add((new BN(256)).pow(new BN(len - 2)).muln(secondByte));
    let maxNumber = minNumber;
    for (let i=len-3; i>=0; --i) {
        maxNumber = maxNumber.add((new BN(256)).pow(new BN(i)).muln(255))
    }

    do {
        minNumber = minNumber.divn(58);
        maxNumber = maxNumber.divn(58);
    } while (!minNumber.eq(maxNumber));

    console.log('min=max', minNumber);

    let alphabet = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
    let deterministicSeq = '';
    while (minNumber.gtn(0)) {
        deterministicSeq = alphabet[minNumber.modn(58)] + deterministicSeq;
        minNumber = minNumber.divn(58);
    }
    console.log('deterministic sequence:', deterministicSeq)
}
```

I'll just list the main results of each step:

| prefix | first 2 bytes of base58Encode input | min = max at | deterministic sequence |
|--------|-------------------------------------|--------------|------------------------|
| 127    | 95, 192                             | 2445         | jA                     |
| 129    | 96, 64                              | 2458         | jP                     |
| 130    | 96, 128                             | 42           | j                      |
| 132    | 97, 0                               | 2477         | ji                     |
| 133    | 97, 64                              | 2484         | jq                     |
| 134    | 97, 128                             | 2490         | jw                     |

**Comment by mnaamani** [comment]
I can confirm prefix `126` works.

```ts
import { cryptoWaitReady } from '@polkadot/util-crypto'
import { Keyring } from '@polkadot/keyring'

async function main() {
  await cryptoWaitReady()

  const keyring = new Keyring({
    ss58Format: 126,
  })

  const suri = '//Alice'
  const userAddress = keyring.addFromUri(suri, undefined, 'sr25519').address
  console.log(userAddress)
}

main()
```

outputs: `j4W7rVcUCxi2crhhjRq46fNDRbVHTjJrz6bKxZwehEMQxZeSf`

Sure I can update the chainspec, although there is also a place in the runtime trait implementation of `frame_system::Config` now to configure it as well.

**Comment by mnaamani** [comment]
Implemented in https://github.com/Joystream/joystream/pull/3928/commits/0a4e8f411e5a94dc4c2f926639a66e5686ac1764
