### ISSUE TITLE
Runtime: fix invalid storage access code in the content pallet.

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#3420]
The content pallet contains invalid storage access code:

```
let video = VideoById::<T>::get(video_id);
let channel = ChannelById::<T>::get(video.in_channel);
```

This code could lead to the default object creation by the Substrate Framework. We need to use `ensure_*` methods instead with explicit errors on absent objects and add related tests. We have such code in multiple extrinsics, mostly related to comments/reactions on videos and channels.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1201973399734040) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
The code was correct, the only occurrence of:
`let video = VideoById::<T>::get(video_id);` 
Was preceded by
`let post = Self::ensure_post_exists(video_id, post_id)?;`
So it was still safe, and an explicit check for ensure_video_exists was not necessary because of the invariant that if a post is found then the video must exist.
And finally `let channel = ChannelById::<T>::get(video.in_channel);` was therefore also safe.

I did however update code to have some consistency and more clarity, in some cases at the expense of doing a redundant check.

Done in https://github.com/Joystream/joystream/pull/3541
