### ISSUE TITLE
Reevaluate what parts of a channel must be frozen while in flight.

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3428]
# Background
Initial work was done here

https://github.com/Joystream/joystream/pull/3432

where the following actions are blocked in flight

* update_channel_censorship_status
* update_channel
* create_video
* update_video
* delete_video
* edit_post_text
* delete_post
* update_moderator_set
* claim_channel_reward

while at least the following are not

* update_video_censorship_status
* create_post
* react_to_post
* react_to_video
* start_nft_auction
* cancel_nft_auction
* cancel_offer
* cancel_buy_now
* make_bid
* cancel_open_auction_bid
* claim_won_english_auction
* pick_open_auction_winner
* offer_nft
* sling_nft_back
* accept_incoming_offer
* sell_nft
* buy_nft
* channel_owner_remark
* channel_collaborator_remark
* channel_moderator_remark
* nft_owner_remark

# Proposal
Review all extrinsics which exist to see where we possibly should add more blockers so as to not allow someone to try to swap a channel while draining it for value during the swap. But we also need to make sure someone cannot use this freezing feature as a sort of defense that blocks interactions that may be important, like curation, or people getting split payouts or whatever it would be. Its a complex question, so it requires taking a broad look and thinking very adversarially.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202414747088684) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
### NFTs

The relation between nft-related extrinsics and channel transfers is quite complex, as there are multiple ways to misuse this functionality during the course of a pending transfer, for example:
1. Current owner offering and buying the nfts himself, under-priced, in order to drain the channel from valuable nfts. This can happen through:
  - `start_open_auction` + `make_open_auction_bid` (at `buy_now_price`)
  - `start_english_auction` + `make_english_auction_bid` (at `buy_now price`)
  - `start_open_auction` + `make_open_auction_bid` + `pick_open_auction_winner`
  - `offer_nft` + `accept_offer`
  - `sell_nft` + `buy_nft`
2. Current owner bumping the perceived value of the nfts by making auctions, bidding himself and cancelling the auctions just before the transfer happens, for example:
  - `start_open_auction` + `make_open_auction_bid` (some very high amount) and then `cancel_open_auction` (just before the channel transfer is accepted)
  - `start_english_auction` + `start_english_auction` (some very high amount) and then `cancel_english_auction` (just before the channel transfer is accepted)
3. Current owner bumping the perceived value of the nfts by making open auction, bidding himself and cancelling his bid just before or **right after** the transfer happens

The last one can of course be mitigated if the channel transfer's receiving party is carefully tracking which bids are potentially cancelable during/right after the transfer.

I summarized those scenarios in a table below:

| Extrinsic                      | Drawbacks if not blocked                                                                | Drawbacks if blocked                                      | Should be blocked |
|--------------------------------|-----------------------------------------------------------------------------------------|-----------------------------------------------------------|-------------------|
| issue_nft                      | Can sidestep other blocked actions due to InitTransactionalStatus                       | Insignificant                                             | Yes               |
| destroy_nft                    | Destroying nft with a certain history may decrease the value of a channel               | Insignificant                                             | Yes               |
| start_open_auction             | Current owner selling valuable nft to himself at low price (if bids also enabled)       | Insignificant                                             | Yes               |
| start_english_auction          | Current owner selling valuable nft to himself at low price (if bids also enabled)       | Insignificant                                             | Yes               |
| cancel_english_auction         | Fake auction to bump perceived nft value, canceled right before transfer finalization   | Insignificant                                             | Yes               |
| cancel_open_auction            | Same as above                                                                           | Insignificant                                             | Yes               |
| cancel_offer                   | Insignificant                                                                           | Insignificant                                             | No(?)             |
| cancel_buy_now                 | Insignificant                                                                           | Insignificant                                             | No(?)             |
| update_buy_now_price           | Current owner selling valuable nft to himself at low price (if buy_nft also enabled)    | Insignificant                                             | Yes               |
| make_open_auction_bid          | Insignificant (unless start_open_auction also enabled)                                  | Prevening users from placing valid bids                   | No                |
| make_english_auction_bid       | Insignificant (unless start_english_auction also enabled)                               | Prevening users from placing valid bids                   | No                |
| cancel_open_auction_bid        | Fake bid to bump perceived nft value, canceled right before/after transfer finalization | Preventing users from valid bid cancellation              | No(?)             |
| settle_english_auction         | Insignificant                                                                           | Prevents winner from claiming the nft                     | No                |
| pick_open_auction_winner       | Owner picks his own, low bid and claims the nft right before channel is transferred     | Lost opportunity of picking high bid before it expires(?) | Yes               |
| offer_nft                      | Current owner selling valuable nft to himself at low price (if accepting also enabled)  | Insignificant                                             | Yes               |
| sling_nft_back                 | Insignificant currently (as channel cannot own another channel's video nft )            | Insignicicant                                             | Yes               |
| accept_incoming_offer          | Insignificant (unless offer_nft also enabled)                                           | Preventing user from accepting an offer                   | No                |
| sell_nft                       | Current owner selling valuable nft to himself at low price (if buy_nft also enabled)    | Insignificant                                             | Yes               |
| buy_nft                        | Insignificant (unless sell_nft or update_buy_now_price also enabled)                    | Preventing a member from buying nft on sale               | No                |

#### Alternative

Another approach to limit the possibility of exploitation would be to:
- allow channels to be transferred only if all video nfts are in the "Idle" state
- disallow any extrinsics that can change the nft state (from idle to any other) during transfers

The benefit of this approach is that it's the safest one and very simple to reason about, the drawback is that it would require iterating over all videos that contain nfts during a channel transfer.
This could be achieved either by including `Channel.owned_video_nfts (BTreeSet<VideoId>)` field and requiring the owner to provide `num_owned_video_nfts` as parameter to `transfer_channel`
or the other way around (keeping track of `Channel.num_owned_video_nfts` in the storage and requiring the owner to provide the ids set as a parameter).

Either way the number of storage reads would be proportional to the number of video nfts in the channel, which could be very high, and significantly increase the cost of `transfer_channel`.


### Creator tokens:

Here we can easily make transfers possible only if there is no unflinalized sale / revenue split
(as suggested here: https://github.com/Joystream/joystream/issues/3780#issuecomment-1134890793)

With that in mind and the fact that we will also block the extrinsic that could change this state, ie.:
- `init_creator_token_sale`
- `issue_revenue_split`

Some extrinsics will just have no possibility of being executed while the channel is "in flight", ie.:
- `update_upcoming_creator_token_sale`
- `finalize_revenue_split`
- `finalize_creator_token_sale`

For this reason I omitted the drawbacks of having them blocked/not blocked in the table below, with a comment "Not applicable": 

| Extrinsic                              | Drawbacks if not blocked                                                                                                    | Drawbacks if blocked | Should be blocked   |
|----------------------------------------|-----------------------------------------------------------------------------------------------------------------------------|----------------------|---------------------|
| issue_creator_token                    | Current owner issuing all tokens to himself, getting up to 100% of current and future channel revenue                       | Insignificant        | Yes                 |
| init_creator_token_sale                | Invalid handling of sale finalization due to changed ownership (ie. from member to curator)                                 | Insignificant        | Yes                 |
| update_upcoming_creator_token_sale     | Not applicable                                                                                                              | Not applicable       | No (Not applicable) |
| deissue_creator_token                  | Insignificant (supply has to be 0 in order to deissue anyway)                                                               | Insignificant        | No(?)               |
| creator_token_issuer_transfer          | Insignificant                                                                                                               | Insignificant        | No(?)               |
| make_creator_token_permissionless      | Allows current owner to make a significant, irreversable change of the token dynamics                                       | Insignificant        | Yes                 |
| reduce_creator_token_patronage_rate_to | Allows current owner to make a significant, irreversable change of the token dynamics (also potentially profitable for him) | Insignificant        | Yes                 |
| claim_creator_token_patronage_credit   | Possible race condition between `claim_creator_token_patronage_credit` and `accept_channel_transfer`                        | Insignificant        | Yes                 |
| issue_revenue_split                    | Current owner can drain channel revenue                                                                                     | Insignificant        | Yes                 |
| finalize_revenue_split                 | Not applicable                                                                                                              | Not applicable       | No (Not applicable) |
| finalize_creator_token_sale            | Not applicable                                                                                                              | Not applicable       | No (Not applicable) |

### Moderation

The possible moderation actions, executable by curators, include:
- `set_channel_paused_features_as_moderator`
- `delete_channel_assets_as_moderator`
- `delete_channel_as_moderator`
- `set_channel_visibility_as_moderator`
- `delete_video_assets_as_moderator`
- `delete_video_as_moderator`
- `set_video_visibility_as_moderator`

I think **none of them should be blocked** as this just opens a possibility for the channel owner to block any valid moderation of the content in his channel from occurring.

### Reward claiming and withdrawals:

| Extrinsic                                                                            | Drawbacks if not blocked                  | Drawbacks if blocked | Should be blocked   |
|--------------------------------------------------------------------------------------|-------------------------------------------|----------------------|---------------------|
| claim_channel_reward                                                                 | Insignificant if withdrawals are blocked  | Insignificant        | Yes(?)              |
| withdraw_from_channel_balance                                                        | Owner draining revenue from the channel   | Insignificant        | Yes                 |
| claim_and_withdraw_channel_reward                                                    | Owner draining revenue from the channel   | Insignificant        | Yes                 |
| claim_council_reward (should be unified with `withdraw_from_channel_balance` really) | Draining revenue from the channel         | Insignificant        | Yes                 |

### Metaprotocol

| Extrinsic                                                                            | Drawbacks if not blocked                  | Drawbacks if blocked | Should be blocked   |
|--------------------------------------------------------------------------------------|-------------------------------------------|----------------------|---------------------|
| channel_owner_remark                                                                 | Unknown                                   | Unknown              | Yes(?)              |
| channel_agent_remark                                                                 | Unknown                                   | Unknown              | Yes(?)              |
| nft_owner_remark                                                                     | Unknown                                   | Unknown              | Yes(?)              |

### Additional remarks

**Note that current implementation of channel transfers is unsafe(!)**

Currently the owner can sidestep any blocked features by preparing a batch call like:
- cancel pending transfer
- do some forbidden actions
- re-initialize the transfer

Because the commitment only contains the `price` and `new_collaborators`, as long as those parameters don't change, the old owner can front-run any of the blocked extrinsics right before the new owner accepts the transfer.

In order for this not to be possible, we probably need some unique, auto-incremented identifier like `channel_transfer_id` to be part of the commitment.

**Comment by bedeho** [comment]
Overall, this was just a phenomenally good breakdown, really well done. So many great obersvations here, in particular the whole `channel_transfer_id` was really perceptive. 

Note: The alternative approach of only allowing transfers if all NFTs are `idle` is not reall workable, quite apart from the computational issues, becuse it means third party NFT owners can block the ability of the channel owner to dispose of their channel.

I have some changes I would still like to request:

- **Metaprotocol:** Let us leave it to the higher level business logic to decide whether the features in question are impacted at all by being in transit. As concluded in the general overview, it has to be decided on a case-by-case basis, so let us not remove this alternatives for metaprotocol authors also.
- `update_channel_transfer_status`: This was not directly covered in the overview, but since you need to be able to cancel a prior transfer if you want to, this should not be blocked either.
- **Everything else:** All the other `No` cases seem to me to be borderline, and in some cases I disagree, so in the interest of making the runtime code simpler, and also making it easier for people to understand the functionality of the system, just making all of it blocked, seems like a better tradeoff.

**Comment by Lezek123** [comment]
> Note: The alternative approach of only allowing transfers if all NFTs are idle is not reall workable, quite apart from the computational issues, becuse it means third party NFT owners can block the ability of the channel owner to dispose of their channel.

Right, I think what I had in mind was just the nfts that are still owned by the channel itself (because those are the only ones beeing transferred to the new owner anyway).

> All the other No cases seem to me to be borderline, and in some cases I disagree, so in the interest of making the runtime code simpler, and also making it easier for people to understand the functionality of the system, just making all of it blocked, seems like a better tradeoff.

So one of the examples I marked as `No` is `settle_english_auction`. If we block it during channel transfers then the channel owner can indefinitely postpone the english auction winner from claiming the nft which he already paid for. Is this really a good idea to not differentiate between extrinsics that should vs should not be blocked?

**Comment by bedeho** [comment]
> Is this really a good idea to not differentiate between extrinsics that should vs should not be blocked?

I don't think this will be a problem, but if it does, we can make settling auctions open to anyone later, which is in general what we should be doing for all of these settlement things, even non-members.
