### ISSUE TITLE
graphql playground regression

### ISSUE THREAD

**Issue by traumschule** [Joystream/joystream#3540]
since olympia got merged to master

https://ipfs.joystreamstats.live/graphql
https://ca.joystreamstats.live/graphql
```
could not find config
(anonymous) @ graphql:548
load (async)
(anonymous) @ graphql:532
```

please check if https://query.joystream.org/graphql uses uncommitted changes.

**Comment by ondratra** [comment]
There seem to be slightly different issues on mentioned servers.
1) On the first server, the middleware URL returns http `error 404` 
https://ipfs.joystreamstats.live/graphql -> https://ipfs.joystreamstats.live/@apollographql/graphql-playground-react/build/static/js/middleware.js
2) On the second server, the middleware URL mistakenly servers the playground webpage (`index.html`) instead of the expected `.js` file. 
https://ca.joystreamstats.live/graphql -> https://ca.joystreamstats.live/@apollographql/graphql-playground-react/build/static/js/middleware.js

It is possible that three different git versions are deployed on the server as suggested, but I suspect the problem will actually be in the web host settings (`.htaccess`-like settings).

**Comment by traumschule** [comment]
Thanks for checking! Was an easy fix, just removed the `*` from `/@apollographql/*`:
```
# query node
    location /graphql {
      rewrite /graphql(/.+) $1 break;
      proxy_pass http://localhost:8081;
      proxy_set_header Access-Control-Allow-Methods "GET, PUT, HEAD, OPTIONS";
    }
    location /@apollographql/* {
      proxy_pass http://localhost:8081;
    }
```

**Comment by mnaamani** [comment]
A simpler approach could have been just:

```
    location / {
      proxy_pass http://localhost:8081;
      proxy_set_header Access-Control-Allow-Methods "GET, PUT, HEAD, OPTIONS";
    }
```

But at least you have a solution for future if you decide to have a different location such as

```
    location /another/path/graphql {
      rewrite /another/path/graphql(/.+) $1 break;
      proxy_pass http://localhost:8081;
      proxy_set_header Access-Control-Allow-Methods "GET, PUT, HEAD, OPTIONS";
    }
    location /@apollographql/* {
      proxy_pass http://localhost:8081;
    }
```
