### ISSUE TITLE
AMM questions

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3639]
Project AMM questions from Atlas team:

* Does AMM only count $CRT supplied by bonding curve? what about dynamics like burning and patronage, each of which in principle can be of arbitrary magnitude.
* What does issuer get to specify about AMM? curve shape? price at supply=0?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202156371512611) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
The question about how AMM price is affected by other supply dynamics events is complex and I need to investigate.
To answer (partially) to the questions above:
 I think it is best to use `TokenData::supply` into price AMM price accounting (and not only $CRT supplied by bonding curve).  
I am not sure if it makes sense to allow the issuer to specify the curve shape.  
Token issuer specifies CRT supply allocated and reserve in order to specify price. For example in the original Bancor protocol:
Bond curve pricing formula is: `price= JoyReserveBalance/(CrTokenSupply * CRR)` -> initial price = `f(JoyReserve, CrtTokenSupply)`. 


#### References
- https://cryptorating.eu/whitepapers/Bancor/bancor_protocol_whitepaper_en.pdf
- https://github.com/bancorprotocol/docs/blob/master/guides/deploying-a-standard-liquidity-pool.md

**Comment by bedeho** [comment]
> I am not sure if it makes sense to allow the issuer to specify the curve shape.

I agree.

> I think it is best to use TokenData::supply into price AMM price accounting (and not only $CRT supplied by bonding curve).

But this means that despite $CRT getting minted for some different reasons, e.g. patronage, the curve is _increasing_ the unit price? That seems very strange. Taking it too the extreme, it means if there if there is sufficiently large amount of such issuance, someone could subsuently easily drain all $JOY from the AMM for very little $CRT. Also over time the AMM will lose greater and greater portions of the lower part of its price range as the issuance is increasing long term. 

What is the upside of this approach?

**Comment by dobertRowneySr** [comment]
I reviewed the whitepaper with more attention and it we should make the AMM accounting limited only to the amount bonded by the curve (when considering the supply)

**Comment by bedeho** [comment]
I think that makes sense, but what about this Q: `What does issuer get to specify about AMM? curve shape? price at supply=0?`

**Comment by dobertRowneySr** [comment]
It seems to me that according to https://github.com/bancorprotocol/docs/blob/master/guides/deploying-a-standard-liquidity-pool.md you:
1. specify your curve shape or CRR 
2. specify both your CRT AMM initial supply and your JOY reserve 
This is sufficient for setting up the AMM state at initial time (initial price is automatically determined by the formula).

You transfer initial JOY to the AMM reserve and then you somehow specify its initial supply

**Comment by bedeho** [comment]
Ok, I think we need to discuss this on a call, then post summary later.

**Comment by bedeho** [comment]
We decided that this needs more research into how different curve shapes impact welfare in various scenarios.
