### ISSUE TITLE
Question: Issuance dynamics corrupting simultaneous revenue splits

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3687]
When a revenue split is initiated, there will be some specific totaly supply of tokens, and each member will have some balance of tokens which earns them a pro-rata share. While the split is ongoing, people will stake, and pro-rata shares of the channel balances devoted to the split will be distributed on an on-going basis. However, we also know that new $CRT can be minted continously during this process, through a possibly active AMM, or patronage, and that it can get burned. These actions change the supply, perhaps not radically, but to some degree. Would seem that when someone stakes interleaved with such actions, then the channel balance in the split will end up getting split incorrectly, and perhaps even either defaulting, so some people cannot get anything despite having tokens, or some tokens cannot be claimed by anyone.

 If this is true, it seems like those other issuance dynamics should just be paused while there is an active revenue split.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202207108750861) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
### shared variable
`TokenData::supply` read by `claim_revenue_split_amount` 
``` rust
    fn claim_patronage_credit(token_id: T::TokenId, to_account: T::AccountId) -> DispatchResult;
```
### Extrinsics racing against `claim_revenue_split_amount`
- `claim_patronage_credit`
- AMM`s `bond`/`undbond` OR Sale exitrinsics

I think one possible solution (besides pausing all burning/minting activities) would be to extend the above extrinsic to

``` rust
    fn claim_patronage_credit(token_id: T::TokenId, to_account: T::AccountId, supply_commit: Balance, slippage: Perbill) -> DispatchResult;
```
allowing the claimer to cash out only if the specified `(100 - slippage)% * TokenData::supply <= supply_commit <= (100 + slippage)% * TokenData::supply` given that `TokenData::supply > 0`. So that the user can avoid claiming if he thinks he's getting a raw deal

**Comment by bedeho** [comment]
- I take the answer here is basically `yes`, problem is real.
- I honestly could not comprehend this solution, but compared to just pausing some of the other features it seems worse
  -  its narrowly focused on patronage, which is not the full problem. You also have AMM and burning as sources of issuance changes, they will also cause various kinds errors. 
  -  its more complex
  -  if we ever wanted to add any new features which impacts issuance, we have to remember to consider this problem again.
  
Given that a revenue split does not take that long, the cost of pausing seems low.
