### ISSUE TITLE
Creator tokens: Unsafe JOY transfers

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#3759]
Currently there are a few instances in the creator token pallet where a call to `balances::Module::transfer` is unsafe and could sometimes result in unwanted mutation, because we're not checking if the transfer's reciever account balance after the transfer would be `>= ExistentialDeposit`.

* [`purchase_tokens_on_sale`](https://github.com/Joystream/joystream/blob/ephesus/runtime-modules/project-token/src/lib.rs#L392) - `<Joy::<T> as Currency<T::AccountId>>::transfer(&sender, &sale_source_controller, joy_amount, ExistenceRequirement::KeepAlive)` without previously checking if `sale_source_controller` account balance after the transfer would be `>= ExistentialDeposit`
* [`participate_in_split`](https://github.com/Joystream/joystream/blob/ephesus/runtime-modules/project-token/src/lib.rs#L535) - `<Joy<T> as Currency<T::AccountId>>::transfer(&treasury_account, &sender, dividend_amount, ExistenceRequirement::KeepAlive)` without previously checking if `sender` account balance after the transfer would be `>= ExistentialDeposit`
* [`finalize_revenue_split`](https://github.com/Joystream/joystream/blob/ephesus/runtime-modules/project-token/src/lib.rs#L1017) - `<Joy<T> as Currency<T::AccountId>>::transfer(&treasury_account, &account_id, amount_to_withdraw, ExistenceRequirement::KeepAlive)` without previously checking if `account_id` account balance after the transfer would be `>= ExistentialDeposit`
* [`dust_account`](https://github.com/Joystream/joystream/blob/ephesus/runtime-modules/project-token/src/lib.rs#L231) - `withdraw_from_treasury` call which under the hood does `<Joy<T> as Currency<T::AccountId>>::transfer(&treasury_account_id, &member_controller, amount, ExistenceRequirement::KeepAlive)` without checking if `member_controller` balance after the transfer would be `>= ExistentialDeposit`. **In this case this could actually cause unsafe mutation, since this call is done after `TokenInfoById::<T>::mutate`**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202294757647030) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
> because we're not checking if the transfer's reciever account balance after the transfer would be >= ExistentialDeposit.

I don't understand why this could be a problem? If the reciever account exists, then it must already be >= than this limit, and if we are adding new funds to it, that will certainly always be the case still after the transfer?

My assumption would be that only an account being spent _out of_ could get dusted?

**Comment by Lezek123** [comment]
> If the reciever account exists

This is only ensured if we send funds to `sender` and the fee is non-zero. In all other cases the reciever may not "exist" (in the sense of beeing part of the `balances` pallet state).

For example, we cannot be certain that a member controller account was not dusted at some point before we try to send funds into it.

**Comment by bedeho** [comment]
This was quite complex indeed.

# Conclusion

In summary, I think we should always just try to ensure that both source and destination always will be kept alive by transfer, that is the easiest. I was trying to reason about what exactly were cases where a real issue could occur vs. not, but I think its best to just be defensive in the validation here.

# A note on `init_token_sale`

While trying to understand this, I incidentally saw that a token sale involves removing taking the sales budget out of the supply of the creator token. Is this wise? This can be confusing, misleading or perhaps even abusable. Its a super simple approach, which is nice, but should we be more explicit leave `amount` alone? I can't actually think of a clean alternative though. Adding a second locking constraint to all accounts, which the `locked` method consutls, would work.

# A note on source of fund accounts

In your examples, you are omitting cases that the source of funds are depleted as possible problems, is this because `KeepAlive` will automatically block this?

[X] If so, am I to assume that `KeepAlive` does not protect the destination account? 

On that note:

**Do we actually know what happens in `balances` if you move less than `ExistentialDeposit` into a new account? Does it actually create the new account or not? does it actually deduct the amount from the old one? Does this depend on keeplive value?**

I read at some point such transfers actually fail, but not sure how keepalive impacts that.

# A note on channel state bloat bonds

Channel accounts, which will be source of funds for revenue splits, hold (or will hold) $JOY state bloat bonds. Are we making sure to not include those in the amount transferrable into a revenue split?

# `purchase_tokens_on_sale`

So here the issue would be that `sale_source_controller` dips below `ExistentialDeposit` because it was somehow empty, _and_ purchased $JOY < `ExistentialDeposit`, which then because of [X] the transfer would fail, or funds would be lost?

# `participate_in_split`

So here the issue is identical to prior point w.r.t. `sender` instead?

# `finalize_revenue_split`

I think this problem goes away when we no longer have reward accounts for channels, but instead have built in accounts that are protected by state bloat bonds.

_Note: I think we should be defensive here even if this is true._

# `dust_account`

So here the issue is identical to prior point w.r.t. `sender` instead?

**Comment by Lezek123** [comment]
> While trying to understand this, I incidentally saw that a token sale involves removing taking the sales budget out of the supply of the creator token

Initializing the sale does substract the `amount` from `account_data`, but it also sets `token_data.sale.quantity_left` (which is in the end recoverable by that account) to `amount`. This can seen as kind of a "transfer of funds from the account into the sale", and most importantly, the token supply is **not affected** by this.

> In your examples, you are omitting cases that the source of funds are depleted as possible problems, is this because KeepAlive will automatically block this?

This is one of possible problems but:
- In creator tokens pallet this was already either ensured before `MUTATION SAFE` or was an assumed property of a valid runtime (ie. in case we're transferring funds from the module account, it should never dip below `ExistentialDeposit` unless there's a bug in the implementation).
- In other pallets we're using `ExistenceRequirement::AllowDeath`, so this case just doesn't result in an extrinsic error and therefore cannot cause unsafe mutation.

> Do we actually know what happens in balances if you move less than ExistentialDeposit into a new account? Does it actually create the new account or not? does it actually deduct the amount from the old one? Does this depend on keeplive value?

Yes, that's the entire point of this issue. It results in an extrinsic error (`Error::<T, I>::ExistentialDeposit`), regardless of whether we're transferring the funds with `ExistenceRequirement::KeepAlive` or `ExistenceRequirement::AllowDeath`. No mutation is performed by the balances pallet itself, but since we're not ensuring that such transfer will not fail before `MUTATION SAFE`, there are cases where some of our extrinsics do some mutation first and then execute a transfer that could possibly fail.

> Channel accounts, which will be source of funds for revenue splits, hold (or will hold) $JOY state bloat bonds. Are we making sure to not include those in the amount transferrable into a revenue split?

Is this about https://github.com/Joystream/joystream/issues/3511?
I think that's not yet implemented, neither on `ephesus` nor on `audit3` branch, so we'll have to wait before addressing this fully, but for now I'll make sure that the amount allocated to a revenue split does not exceed `channel_account_usable_balance - existential_deposit`.

> purchase_tokens_on_sale
> So here the issue would be that sale_source_controller dips below ExistentialDeposit because it was somehow empty, and
> purchased $JOY < ExistentialDeposit, which then because of [X] the transfer would fail, or funds would be lost?

Yes, the transfer would fail, which shouldn't cause any real problem in this case, but since the transfer is done under `MUTATION SAFE` and no `ensure_` check for this scenario was done before `MUTATION SAFE` - this violates the `MUTATION SAFE` barrier and could be the source of issues in the future (ie. if someone introduced a new mutation before the said transfer)

> participate_in_split
> So here the issue is identical to prior point w.r.t. sender instead?

Yes

> dust_account
> So here the issue is identical to prior point w.r.t. sender instead?

That's what I initially though, but I double checked and the `withdraw_from_treasury` function which was used here actually ignored the result of `balances::transfer`, so it seems like unsafe mutation was not really possible. The only issue in that case was `bloat_bond` never making it from `treasury_account` into `sender` account in case `sender` account didn't exist. 

Anyway, all those issues were fixed as part of https://github.com/Joystream/joystream/pull/3761
