### ISSUE TITLE
Channel account features: was already han

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/joystream#3869]
Full description and accurate representation of scope will be provided later

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202405961072713) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@bedeho need some input here on the scope, the title seem to have been cropped at some point and I could not match it with corresponding Runtime tickets.

**Comment by bedeho** [comment]
Best I can muster from this title, this is about the fact that channels no longer have reward accounts that the creator gets to set, they instead have built in accounts, but not totally sure. I suggest we just close this, because if even if it was that, there is no clear action for this in this repo, nor even in Atlas, it would just be part of the routine work of updating to the new extrinsic signatures which will be trivial.
