### ISSUE TITLE
Runtime changes for Rome

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#388]
## General

- [Set](https://github.com/Joystream/joystream/blob/eb6e37043b37ef4e2ae8c18d5c2acaf2b3fd304a/runtime/src/lib.rs#L142) `EPOCH_DURATION_IN_BLOCKS = 60 * MINUTES`
- [Keep](https://github.com/Joystream/joystream/blob/eb6e37043b37ef4e2ae8c18d5c2acaf2b3fd304a/runtime/src/lib.rs#L343) `SessionsPerEra = 6`
- consequences:
  - Will change session/epoch from 100 to 600 blocks
  - Will effectively set era to 3600 blocks
  - In line with substrate/polkadot
  - Not really needed, but will also keep payouts more stable, by having all recurring rewards at same interval

## Staking
If change above is implemented:
- [Set](https://github.com/Joystream/joystream/blob/eb6e37043b37ef4e2ae8c18d5c2acaf2b3fd304a/runtime/src/lib.rs#L344) `BondingDuration = 4`
If change above is not implemented:
- [Set](https://github.com/Joystream/joystream/blob/eb6e37043b37ef4e2ae8c18d5c2acaf2b3fd304a/runtime/src/lib.rs#L344) `BondingDuration = 24`
- consequences:
  - Will set unbonding time for validators to 14400 blocks -> one day
  - Substrate/polkadot has this set to one month
  - The thinking here is to avoid locking the validators in for an unreasonable amount of time 

- [Set](https://github.com/Joystream/joystream/blob/eb6e37043b37ef4e2ae8c18d5c2acaf2b3fd304a/runtime/src/lib.rs#L331) `REWARD_CURVE` inputs from:
```
        min_inflation: 0_025_000,
        max_inflation: 0_100_000,
        ideal_stake: 0_500_000,
        falloff: 0_050_000,
        max_piece_count: 40,
        test_precision: 0_005_000,
    );
}
```
to:
```
        min_inflation: 0_025_000,
        max_inflation: 0_300_000,
        ideal_stake: 0_300_000,
        falloff: 0_050_000,
        max_piece_count: 40,
        test_precision: 0_005_000,
    );
}
```
- consequences:
  - First and foremost, this will increase the inflation and rewards given to validators. Not sure if this should be kept at mainnet, but needed to make the validator role profitable.
  - This also reduces the "ideal stake rate", ie. the percentage of tokens staked by current validators, to achieve the max inflation possible for them.
    - If one assumes polkadots 50% is "correct" for them, it makes sense for us to have a lower number here, as there are many other ways to stake on the Joystream network.

## Slashing

This one, I haven't tested, but I think the current slash rate is far too high. The risk just outweighs the returns, while the networking is still somewhat unstable, and it's not (yet) reasonable to enforce users to deploy an advanced setup, with backups, sentry nodes, etc.

**Comment by mnaamani** [comment]
Yes I see the thinking behind these changes. Closely matching to Kusama also makes sense.

For reference Kusama/Polkadot actually has the BondingDuration set to 7 days, but yes I can see in substrate it is set to 28 * 24 eras (with 10min per epoch, 6 session per era) -> 28 days. This is clearly too high for constantinople. 1 day seems reasonable.

I follow the logic behind reducing the ideal stake and the figure looks reasonable.

I'll try to make changes and test with a runtime upgrade to see if there are any side affects to changing the values inflight.

**Comment by mnaamani** [comment]
Just a note here on why we didn't implement changes to era/epoch was simply because with a runtime upgrade reading values of the "runtime constants" through polkadot-js/api would always return the initial values at genesis, and not the new ones, so it wasn't reflecting correctly in pioneer UI on the explorer app.

This has something todo with how `const` values on `decl_module!` are read by the api. Is it reading the values from the native runtime of the node, and not the wasm blob/metadata?

I confirmed that by changing the value (the `Get` type on the `Trait` trait was being reflected in the runtime itself) .. maybe this has changed in newer versions of substrate? experimented with [simple module](https://github.com/Joystream/joystream/blob/21529850cfa16beb004c2338ada5384c573071bd/runtime/src/constantine.rs) passing in different values in runtime configuration for `TheValue` at genesis and then doing a runtime upgrade with different value and observing the value in the emitted event.

**Comment by bwhm** [comment]
Closing this now.
