### ISSUE TITLE
POC: Can Hydra work with updated Substrate version?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/joystream#3883]
## Context
Substrate upgrade to v3 has some compatibility risks. The focus of this task is to do an exploratory work ahead of the new network deployment (carthage).

**Additional info:**
Corresponding upgrade of Substrate is handled here: 

* https://github.com/Joystream/joystream/pull/3875

## Scope
* [ ] Rollout new env with QN pointing to the empty Node template based on the upgraded version of Substrate pallets.
* [ ] Catch all exceptions and compatibility issues and list them as a BPs in comments to this ticket. 

This ticket will further inform our efforts on making QN work with the Upgraded runtime as part of Carthage.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202418962262360) by [Unito](https://www.unito.io)

**Comment by ondratra** [comment]
Polkadot version that can be used for testing is https://github.com/paritytech/substrate/tree/polkadot-v0.9.23 .

**Comment by ondratra** [comment]
After some testing, I think there won't be anything on QN side blocking us from updating Substrate version in Joystream.
We will need to update PolkadotJS version through Hydra and Joystream repository, update Joystream types, and slightly adjust the related code.

I tested that indexer properly indexes blocks. Since the processor only communicates with indexer it and some mappings would be needed to be created, I haven't tried that and assume it will work (I don't see why it shouldn't).

How I tested this:

1) get substrate template
```
git clone git@github.com:paritytech/substrate.git
cd substrate
git fetch origin polkadot-v0.9.23
git checkout polkadot-v0.9.23
```

2) setup rust & build the project
```
rustup update
rustup install nightly-2022-05-11
rustup target add wasm32-unknown-unknown --toolchain nightly-2022-05-11

cargo +nightly-2022-05-11 build --release
```

3) start node
```
./target/release/substrate --dev --pruning archive --unsafe-ws-external --unsafe-rpc-external --rpc-methods Safe --rpc-cors=all
```

4) prepare db and reddis - **run this in Joystream repo!** (you can use `master` or any other branch)
```
docker-compose up -d db redis
```

5) start indexer - **run this in Hydra repo!** (see below)
```
cd packages/hydra-indexer/
./tmp.sh
```

I've created a testing Hydra repository that can be used for this test https://github.com/ondratra/hydra/tree/temporary_substrate_upgrade_test .
