### ISSUE TITLE
Verify: no new proposals in runtime

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3891]
Last check for `Carthage`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202453992728834) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Current state (as of https://github.com/Joystream/joystream/commit/3f946c4e80cbfd319d56d366b1a3cf10a68d3c98):
- The only **new proposals vs `master`** are:
    - `UpdateGlobalNftLimitProposal`
    - `UpdateChannelPayoutsProposal`
- Proposals that were **removed**:
    - `CreateBlogPostProposal`
    - `EditBlogPostProoposal`
    - `LockBlogPostProposal`
    - `UnlockBlogPostProposal`

This is the expected state, to be confirmed just before launching `carthage`

**Comment by Lezek123** [comment]
State unchanged since last comment (w.r.t. new proposals introduced)

**There are some proposal validation changes worth noting however:**
- `MAX_SPENDING_PROPOSAL_VALUE` => `FundingRequestProposalMaxTotalAmount`, besides the fact that the constant is now exported, the validation logic is now different: this is no longer a max value per account, but per entire proposal (which may include many accounts to fund)
- `FillWorkingGroupLeadOpening`: opening id and application id is now validated during proposal creation
- `DecreaseWorkingGroupLeadStake`: leader worker id is now validated during proposal creation
- `SlashWorkingGroupLead`: leader worker id is now validated during proposal creation
- `SetWorkingGroupLeadReward`: leader worker id is now validated during proposal creation
- `TerminateWorkingGroupLead`: leader worker id is now validated during proposal creation
- `CancelWorkingGroupLeadOpening`: opening id is now validated during proposal creation
- `VetoProposal` - proposal id is now validated during proposal creation

**Additionally:**
- the new `UpdateGlobalNftLimitProposal` creation is disabled via `filter_stage_2`
