### ISSUE TITLE
working-groups:createOpening require leader increase staking

### ISSUE THREAD

**Issue by yasiryagi** [Joystream/joystream#4101]
Exciting command : joystream-cli working-groups:createOpening -g=storageProviders
Result : 

```
you need to increase your lead stake to xxxxx kJOY in order to create a new opening.
```

```
 ›   Warning: Extrinsic failed! Extrinsic execution error: BelowMinimumStakes (Staking less than the lower bound.)
```

[createOpening_issue.txt](https://github.com/Joystream/pioneer/files/9228910/reateOpening_issue.txt)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202697800725933) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@yasiryagi  which approx block was it on? trying to traige with @bwhm this info would help.. thank you!

**Comment by Lezek123** [comment]
> you need to increase your lead stake to xxxxx kJOY in order to create a new opening.

This is expected behavior

> Warning: Extrinsic failed! Extrinsic execution error: BelowMinimumStakes (Staking less than the lower bound.)

This is unrelated to the first message and is actually caused by `stakingPolicy.amount` being too low.
Minimum application stake has been changed to `20 DOLLARS` (~3,333,333,333,333 HAPI) in https://github.com/Joystream/joystream/pull/4025/files#diff-0ec06ea58bd455f09ce6b3bb4c2c1c0d37bda51c1e1be2151c560c9c973959ecR1087, but the CLI validation of this has not yet been updated

**Comment by yasiryagi** [comment]
Please attached documents, I keep increasing the stake and it keep asking again for a new number!

**Comment by Lezek123** [comment]
> Please attached documents, I keep increasing the stake and it keep asking again for a new number!

You don't need to increase the stake manually, because `create_opening` extrinsic will always try to top it up by `OpeningStake`, regardless of what's your current stake.

Let's say your current lead stake is 100k JOY and the opening stake is 2k JOY.
In order to create an opening at this point you will need to transfer 2k JOY to your staking account (but not stake it!)
Then `create_opening` will top up your stake to 102k JOY.
If you increase your stake to 150k JOY, you will still need to transfer 2k JOY and `create_opening` will top it up to 152k.

Essentially each `create_opening` call will require you to stake 2k **on top of your current stake**, increasing it with `increase_stake` does not help you in any way.

**Comment by yasiryagi** [comment]
Understood

**Comment by yasiryagi** [comment]
It will be good if we can make the unit clear.

**Comment by dmtrjsg** [comment]
@yasiryagi respective issue raised:
- https://github.com/Joystream/subcli/issues/7
