### ISSUE TITLE
Review codebase for all TODO remarks

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4194]
ssia.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202929481095649) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
| Todo name | Priority | Description | Runtime module name | Comment / Responsibility |
| --- | --- | --- | --- | --- |
| proposal encoder reference | medium | proposal encode should accept a reference in order to prevent cloning | Proposal codex | Old comment, but I think it’s still relevant, even though not urgent |
| refactor start referendum | low | disabled during sumer-olympia. refactor | referedum | Old comment by Leszek, Starting a refendum should be enabled now |
| change module comment | low | change module comment | working group | deprecated |
| todo related parameters to storage upload on token issuance | low | storage upload params interface for token issuance | project token| Need to figure out CRT - storage interaction still. Buit it will be eventually addressed |
| extra implementation on delete token | low | add extra implementatio on do deissue token | project token | Need to figure out CRT - storage interaction still. Buit it will be eventually addressed |
| Constraints on patronage rate | low | issue https://github.com/Joystream/atlas/issues/2728 warns about not constraining revenue split | project token | Project token parameters yet to be decided |
| set starting block number to 1 | low | set starting block number to 1 on tests | content - tests | basically irrelevant, it allows to avoid having run_to_block(1) during test |
| origin cloning | low | delete double origin after the Origin type supports clone | common | Very old comment (2+ years), origin.clone() should be supported by now |
| rename ensure post exists function | low | rename due to non being descriptive enough | forum | |
| adjust weight on invite_member | low | adjust extr weight | membership | Old comment that should be irrelevant, since pallet is already benchmarked |
| parameters config for amend proposal | low | remove configuration for staging and default | runtime proposal configuration | Mokhtar? |
| on runtime upgrade weight | low | on runtime upgrade weight implementation for custom on runtime upgrade trait | runtime - runtime_api | This is a very old comment 2+ years and we are not doing any custom runtime update at launch |
| ignore test set validator count prop | medium | ignore test on set validator count proposal succeeds that woulfd require constitutionality > 1 | runitme - integration - tests | Leszek? |
| ignore test increment budget prop | medium | ignore test on increment budget proposal that would require constitutionality > 1 | runtime - integration - tests|  Leszek? |
| ignore test on set councilor reward proposal succeeds | medium | ignore test on set councilor reward proposal that would require constitutionality > 1 | runtime - integration - tests | Leszek? |
| staking config reward curve| low | enable normal reward curve for mainnet configuration | runtime configuration | it would just clean up the code, bu the old reward curve can be dropped without affecting runtime behavior|
| adjust max # asset per {channel, video} and max # collaborators per channtel | low | ssia | runtime configuration| Should Martin provide correct values? |
| adjust max # operators per dist bucket | low | ssia | runtime configuration | Should Martin provide correct values? |
| max sticky threads | low | ssia | runtime configuration | Should Martin provide correct values? |

**Comment by traumschule** [comment]
According to code search there are still 59 `TODO` occurrences.

**Comment by bedeho** [comment]
In runtime code only? or all over?

**Comment by traumschule** [comment]
I didn't count by directory but there are some in `runtime` and `runtime-modules`. Anyway it's easy to search and check.
