### ISSUE TITLE
Question: `filter_non_essential` too permissive

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4255]
In our [rollout plan](https://github.com/Joystream/joystream/issues/3792) the initial `Frozen` stage is very restrictive in available functionality, but `filter_non_essential` appears to be quite permissive compared to the `Frozen` stage. 

```Rust
fn filter_non_essential(call: &<Runtime as frame_system::Config>::Call) -> bool {
    match call {
        Call::System(method) =>
        // All methods except the remark call
        {
            !matches!(method, frame_system::Call::<Runtime>::remark { .. })
        }
        // confirmed that Utility.batch dispatch does not bypass filter.
        Call::Utility(_) => true,
        Call::Babe(_) => true,
        Call::Timestamp(_) => true,
        Call::Authorship(_) => true,
        Call::ElectionProviderMultiPhase(_) => true,
        Call::Staking(_) => true,
        Call::Session(_) => true,
        Call::Grandpa(_) => true,
        Call::ImOnline(_) => true,
        Call::Sudo(_) => true,
        Call::BagsList(_) => true,
        // Disable all other calls
        _ => false,
    }
}
```

I am not sure because I frankly am just getting familiar with how the whole validation staking system maps on to this panoply of FRAME pallets, but seems to be worth clarifying if this is perfectly in synch. I also don't know how bad the consequences would be if we filtered in the wrong way.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202919653363179) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
As e have not yet configured the runtime to start with `PoA` mode, so we have lots of pallets related to `NPoS`

When we switch to PoA configuration for the rollout we will effectively be dropping the following pallets:
```
ElectionProviderMultiPhase
Staking
Authorship
Session
BagsList
ImOnline
```

**Comment by bedeho** [comment]
Alllow multisig pallet, rollout plans changed: https://github.com/Joystream/joystream/issues/3792

**Comment by dobertRowneySr** [comment]
| Pallet | Needed| 
|---------|-------------|
|Utility | :white_check_mark: |
|Babe  |  :white_check_mark:  | 
|Timestamp |  :white_check_mark:  | 
|Authorship | :white_check_mark:  |
| Election MultiPhase | :white_check_mark:  | 
| Staking | :white_check_mark:| 
| Session |:white_check_mark:| 
| Grandpa |  :white_check_mark:| 
| ImOnline | :white_check_mark: |
| Sudo | :white_check_mark: |
| BagList | :white_check_mark: |

- Grandpa, Babe requires the Session pallet, that requires the Staking pallet itself
- the Staking pallet will elect validation by orchestrating an election: this is achieved using the Election data provider:
the election provider will fetch candidates from `pallet_staking::Pallet as ElectionDataProvider` and it will use the `Election Multi Phase` engine to perform the actual election (see `impl pallet_staking::Config` in the runtime)
- authorship is used `on_initialize` for uncle management and give era reward, in particular it uses the Staking pallet to set the reward and the ImOnline to see if validator are online (for each session)
- sudo pallet will be needed to force a new era `api.tx.sudo.sudo` on the tests
- The Timestamp pallet allows the validators to set and validate a timestamp with each block, precisely on `pallet_staking::on_finalize` (in order to set the `active_era.start` field)
- pallet utiliy is used for the batch dispatch
*Addendum*:
I had some doubt about the Authorship & ImOnline pallets, polkadot mainnet launch uses both https://github.com/paritytech/polkadot/blob/efb82ef7b0a0f0a67b43b616471db5921f45a614/runtime/polkadot/src/lib.rs#L343
