### ISSUE TITLE
Argus: Expose QN connection status

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4256]
It's often an issue that a specific DP cannot serve an asset because their QN is out of sync and doesn't know about certain storage object. This is a bit hard to debug from DP lead perspective though, as the only way to notice is to get QN logs. For this reason, we've concluded that it would be nice for the Argus `/status` endpoint to expose:
1) Last indexed QN block, or some other indication whether QN is "up-to-date"
2) URL of used QN, so that it's easy to tell whether that's remote or local node.

**Comment by alexznet** [comment]
If there is just some flag saying that QN is up-to-date that would be the best option from usage perspective. 

In this case Argus could check the last block in the network in general on his own, last block in QN and give simple 'true' or 'false' indicating if QN is in sync or not. Because otherwise - if it would just expose the last QN block that would mean that some external tool would need to access chain itself to make such conclusion (and so each tool designed to monitor status). 
So it is better to put this logic behind status endpoint itself and just expose:

1. Is QN in sync - 'true' or 'false'
2. URL of QN

**Comment by bedeho** [comment]
Sounds like a great idea, should Colossus also have this?

**Comment by zeeshanakram3** [comment]
Addressed in #4560
