### ISSUE TITLE
The comedy of starting referenda

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4268]
In trying to configure `referendum::Config::MaxWinnerTargetCount`, I was warned by @mnaamani  that simply setting it to the council size would result in a problem if `<Runtime as council::Config>::MinNumberOfExtraCandidates > 0`. I could not reproduce this, but it did lead me to the following questions

1. Why do we have two functions for starting a referendum, where one is not used

```Rust
/// referendum/src/lib.rs

    // TODO: Disabled during the 'Olympia - Sumer' merge. Refactor on the next pallet change.
    #[allow(clippy::result_unit_err)]
    /// Start a new referendum.
    fn start_referendum(
        origin: Origin,
        extra_winning_target_count: u64,
        cycle_id: u64,
    ) -> Result<(), ()>;

    /// Start referendum independent of the current state.
    /// If an election is running before calling this function, it will be discontinued without
    /// any winners selected.
    /// If it is called with a bigger winning target count greated than the max allowed the max
    /// will be used
    fn force_start(extra_winning_target_count: u64, cycle_id: u64);
```

Former is not used, and should really be removed.

2. Why do we have _forceful_ referendum starts. Seems like this shuold never happen unless referendum & council pallets are incompatibly configured.
3. Why does council actually ask for one less winner than required!

```Rust
    // Change the council stage from the announcing to the election stage.
    fn finalize_announcing_period(candidates_count: u64) {
        let extra_winning_target_count = T::CouncilSize::get() - 1;

        // start referendum
        T::Referendum::force_start(extra_winning_target_count, AnnouncementPeriodNr::get());
```

4. and then, comically, refendum pallet adds an extra winner!

```Rust
    // Start referendum independent of the current state.
    // If an election is running before calling this function, it will be discontinued without any
    // winners selected.
    fn force_start(extra_winning_target_count: u64, cycle_id: u64) {
        let winning_target_count = extra_winning_target_count + 1;

        // If a greater than the max allowed target count is used the max will be used in its place
        let winning_target_count = winning_target_count.min(T::MaxWinnerTargetCount::get());

```

So this clearly needs an examination, and verifying whether there really ever is an issue like mnaamani was concerned about.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202940672873861) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
> Why do we have forceful referendum starts. Seems like this shuold never happen unless referendum & council pallets are incompatibly configured.

This was introduced in: https://github.com/Joystream/joystream/pull/1767
The method should be infallable, because it's called during `on_initialize`.
I guess we could optimize it a little by assuming it's never called during a running election, ie.:
```rust
        // We don't really need this:
        // if referendum_running {
        //     Self::deposit_event(RawEvent::ReferendumStartedForcefully(
        //         winning_target_count,
        //         voting_period_end_block,
        //     ));
        // } else {
            Self::deposit_event(RawEvent::ReferendumStarted(
                winning_target_count,
                voting_period_end_block,
            ));
        // }
```
And just rename to `start_election`, but that's basically cosmetics.

> Why does council actually ask for one less winner than required!

I think it's just a peculiar semantic, ie. the referendum assumes there must be at least 1 winner, so it only asks for the number of _extra_ winners (the total number being `1 (assumed) + n extra`), however it could also ask for the total number of winners and just force `1` in case `0` is passed (the same way it forces `winning_target_count = T::MaxWinnerTargetCount::get()` in case the provided number is too large).

> So this clearly needs an examination, and verifying whether there really ever is an issue like mnaamani was concerned about.

It appears to me that this particular issue is non-existent and it makes sense to me to just set `MaxWinnerTargetCount == CouncilSize`. There was some discussion about this in https://github.com/Joystream/joystream/pull/3462, but I couldn't find an exact reason as to why it was supposed to be `>= CouncilSize + MinNumberOfExtraCandidates`. Both my manual tests and the integration tests are passing even if this condition is broken (for example with `CouncilSize = 5, MaxWinnerTargetCount = 5, MinNumberOfExtraCandidates = 1`)

### Withdrawing candidacy stake

The only thing that I found quite confusing during my tests was the process of recovering the council candidate stake in case the candidate was not elected.

The only way I could find to do this was to:
- Wait until next `Announcing` period
- Add a new staking account to my membership (I couldn't reuse the one that was used during previous `Announcing` period)
- Announce candidacy again, using the new staking account
- Withdraw the new candidacy (before the `Announcing` period ends)

This seems like a bad design. For example, I need to have a least `MinCandidacyStake` of usable funds to be able to recover my old stake and I may no longer have that many funds available. The process itself is also very non-obvious (I'm not sure how Pioneer navigates through this for example)

I think this issue was also pointed out in https://github.com/Joystream/joystream/issues/2909
