### ISSUE TITLE
Bug: Execution Failed - Unable to query dispatch info

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#4296]
In PR https://github.com/Joystream/joystream/pull/4282 during CI tests https://github.com/Joystream/joystream/actions/runs/3037056560/jobs/4907571595#step:8:13437

We have seen a panic in the runtime processing a dispatch call:

    2022-09-13 14:28:30        RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: 1: Unable to query dispatch info.: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
    WASM backtrace:
    
        0: 0x3fe88e - <unknown>!rust_begin_unwind
        1: 0x4540 - <unknown>!core::panicking::panic_fmt::h0a20ba97f16cb738
        2: 0x2e1c0b - …
        RpcError: 1: Unable to query dispatch info.: Execution failed: Execution 
        aborted due to trap: wasm trap: wasm `unreachable` instruction executed
        WASM backtrace:
    
            0: 0x3fe88e - <unknown>!rust_begin_unwind
            1: 0x4540 - <unknown>!core::panicking::panic_fmt::h0a20ba97f16cb738
            2: 0x2e1c0b - …
        Code: 1
    "Needs investigation.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203021582570286) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
What I've been able to establish so far is:
1. The issue occurs when the CLI is trying to estimate transaction fee for `updateChannel` and `createVideo` transactions. It's not a panic during extrinsic execution, but an RPC api call panic, which should be safe (ie. it may happen if the transaction is encoded using the wrong types for example)
2. It only happens with `joystream/node:aa980a87b30d2b10e8efeeea9fad882a4d740c66`, if I run the tests directly on `carthage_flattenVideoCarthageField` or if I merge the latest `carthage` into it - they pass
3. In order to build `joystream/node:aa980a87b30d2b10e8efeeea9fad882a4d740c66` one needs to:
```bash
git checkout carthage_flattenVideoCarthageField
git merge 1f9b05aa365a3c21142a6aefdd5ee4a4a4f7ba03 # we need to specificaly merge outdated carthage head
```
4. The runtime logs show:
```
2022-09-16 15:09:17.901 ERROR tokio-runtime-worker runtime: panicked at 'Bad input data provided to query_info: Codec error', /joystream/runtime/src/runtime_api.rs:120:1
```

I suspect it may have something to do with the fact that `1f9b05aa365a3c21142a6aefdd5ee4a4a4f7ba03` is just shortly after https://github.com/Joystream/joystream/commit/53538a9fc9d58e271133834380ebf37d77fcc709 which changed all the runtime dependencies, but I didn't manage to find the exact cause

**Comment by bedeho** [comment]
TODO
- test hypothesis that error was due to type mismatch by injecting a transaction where one of the types in the param list is improperly encoded, that is some type which had the wrong typedef.

**Comment by Lezek123** [comment]
In the end it turned out it was actually a metadata types mismatch, although the explaination of how this mismatch was even possible in the first place is quite complex:
1. On Sept 12 [this PR](https://github.com/Joystream/joystream/pull/4282) was created. At this point it only had one commit: [`bffee5ad67521a652b1a24da86ee9150a2e727c0`](https://github.com/Joystream/joystream/pull/4282/commits/bffee5ad67521a652b1a24da86ee9150a2e727c0). The carthage HEAD at the time was at [`1f9b05aa365a3c21142a6aefdd5ee4a4a4f7ba03`](https://github.com/Joystream/joystream/commits/1f9b05aa365a3c21142a6aefdd5ee4a4a4f7ba03). All of this can be established by looking at the `actions/checkout@v1` output [during the first run (`Attempt #1`)](https://github.com/Joystream/joystream/actions/runs/3037056560/jobs/4889034259) of CI checks in this PR:
![image](https://user-images.githubusercontent.com/19978260/196492947-da72dfd8-54d7-40d9-80de-a7943819c99c.png)

    When inspecting this attempt you can also notice that all jobs in `run-network-tests` workflow failed, **except** the `Build joystream/node` job:
![image](https://user-images.githubusercontent.com/19978260/196495694-d2dd308c-7bbf-4975-90ea-a5a9aba0493f.png)


    This is important, because it's possible to manually re-run only the failed jobs. In this case any outputs produced by initially successful `Build joystream/node` are re-used, including `steps.compute_shasum.outputs.shasum`, which is the runtime shasum used to tag and identify `joystream/node` docker images.

2. A day later Klaudiusz [re-ran the failed jobs (`Attempt #2`)](https://github.com/Joystream/joystream/actions/runs/3037056560/jobs/4901933524). When inspecting this 2-nd attempt, you can notice that Carthage HEAD was already at [`97b311f071f6f76b5de78da281d88188466c63ce`](https://github.com/Joystream/joystream/commits/97b311f071f6f76b5de78da281d88188466c63ce) at this point:
![image](https://user-images.githubusercontent.com/19978260/196497442-02edadb6-f22a-41cd-8b18-5e4d3fcfc463.png)
In this commit, among other changes, `storage_buckets_num_witness` and `channel_bag_witness` parameters were introduced to extrinsics like `update_channel`, `create_video` and `update_video`. The [CLI was also adjusted to include the new parameters when creating those extrinsics](https://github.com/Joystream/joystream/commit/97b311f071f6f76b5de78da281d88188466c63ce#diff-f4562a64203b5b1c9ba27cef8b5a5195b9e54764068f7fbe9d528bbc9e63dbf6R133).

3. Now because during `Attempt #2` the `steps.compute_shasum.outputs.shasum` generated in `Attempt #1` was reused, the tests were ran using the outdated runtime docker image from `Attempt #1` (`joystream/node:aa980a87b30d2b10e8efeeea9fad882a4d740c66`):
![image](https://user-images.githubusercontent.com/19978260/196498100-7f729b35-4b14-479f-8ec9-cdc29e2c9adb.png)
However the changes in the CLI and `@joystream/types` that were recently merged to `carthage` were included. You can even see in [full test scenario output](https://pipelines.actions.githubusercontent.com/serviceHosts/e1f1b18e-34a8-42b1-995f-91b0187673de/_apis/pipelines/1/runs/49409/signedlogcontent/4?urlExpires=2022-10-18T17%3A08%3A46.3682340Z&urlSigningMethod=HMACV1&urlSignature=qSnaH%2BE8x0CPtF7oYgNYYYHatkDCpWPU4Izt55R9fB0%3D) that CLI was including `storageBucketsNumWitness` in the `UpdateChannelParameters`, right before the panic occured:
![image](https://user-images.githubusercontent.com/19978260/196498783-ef3d4ba1-9569-4212-9d07-097e79eefd27.png).
The reason I think it's safe, however, is that this happens when the node is trying to decode a badly encoded transaction. There are lots of reasons why this operation may fail (and cause panic), like a memory overflow for example. We already explored this specific case and concluded that this, by itself, isn't dangerous (unless the tx can somehow become part of valid block). As shown on the screenshot below, the node continues to operate as expected after this error:
![image](https://user-images.githubusercontent.com/19978260/196502676-ef41b95b-2ad7-4ed6-9aee-764f789a7bda.png)
 

4. 2 more attempts were executed after `Attempt #2`, but they failed for exactly the same reason. Then `carthage` branch was merged into https://github.com/Joystream/joystream/pull/4282, which solved the issue (actually adding and pushing any commit would solve the issue at this point, because it would update the `steps.compute_shasum.outputs.shasum` generated by `Build joystream/node` job)
