### ISSUE TITLE
Min\Max buy now price consts

### ISSUE THREAD

**Issue by attemka** [Joystream/joystream#4605]
currently, there is no restrictions on max buy now price for nft.
we're currently have `maxStartingPrice` and `minStartingPrice`, so I think something like `maxBuyNowPrice` and `minBuyNowPrice` should also be there.
@bedeho please help with these 2 consts values.

Also, we need to introduce runtime validation for the auctions and nft sells to prevent adding incorrect prices by bypassing client's validation.

checklist:

- [ ]  add consts weights in `runtime-modules/content/src/weights.rs`
- [ ] add auction min/max buy now price in `runtime-modules/content/src/lib.rs` 
- [ ] edit QN mappings in `query-node/mappings/src/content/nft.ts`
- [ ] edit runtime nft listing tests functions in `tests/network-tests/src/Api.ts`: 
    1. `createOpenAuctionParameters`
    2. `createEnglishAuctionParameter`
    3.  `sellNft`
    4.  `updateBuyNowPrice`

**Comment by dobertRowneySr** [comment]
> currently, there is no restrictions on max buy now price for nft.

True for the runtime logic. 
###### Runtime To-do list
- [ ] add min/max buy now limits to content on-chain state (no migration needed but they have to be initialised to some default value)
- [ ] expose above limits
- [ ] add unit tests for the various extrinsic involved with the buy now features `issue_nft`,`start_*_auction`, `sell_nft`, `update_buy_now_Price`  etc..
- [ ] regenerate weights (on ref machine)

No migration should be needed for this functionality, but there might remain NFTs with buy now prices too high because they were created before the constraint has been introduced in the runtime

###### Non runtime part
- [ ] expose QN mappings for nfts
- [ ] edit runtime nft listing tests functions in tests/network-tests/src/Api.ts: 
          createOpenAuctionParameters
          createEnglishAuctionParameter
          sellNft
          updateBuyNowPrice

**Comment by attemka** [comment]
closing for now, reopen if needed
