### ISSUE TITLE
Pioneer v1 UX: Forum fixes

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#467]
As part of #400:

One of the biggest pains with the current forum is that its really hard to keep of track whethere there is any new activity in the forum to check in on, you just get this top level view

<img width="1220" alt="Screenshot 2020-05-24 at 19 32 46" src="https://user-images.githubusercontent.com/437292/82762269-47cc9580-9e00-11ea-8094-5652c49b632d.png">

This is equally the case when you go into a specifica category. 

# Most recent active threads

A standard solution which is found in most other forums is to list, in each category (including also the root level), what the N most recent posts are, with a link to jump to it. It probably should be something slightly more sophisticated, like the last N posts in the last N threads which had activity, in order to avoid getting a bunch of posts all from the same thread. This could be shown ab

# Other fixes.

- The actual top level display of each category makes little sense. We should
  - drop the New thread button
  - drop the Creator column
- Drop "New category" and "Forum sudo" buttons.

# Comment

We can't do a deep fix of the UX issues here, beceaue it requies the query node to get all the required computed indexes, such as the total number of posts in a category.

**Comment by mochet** [comment]
* Forum is very confusing as it doesn't currently respect manual line breaks that are input in a post.
* Uppercase title is put to all lowercase on thread view (it shows correctly on subforum view) (shown incorrectly here: https://testnet.joystream.org/#/forum/threads/)
* Its not clear to an end-user that it accepts markdown formatting. Markdown isn't typical within forums, which typically use BBCode, so it would be good to educate people on what Markdown is or make it more clear how to customize formatting.
* When clicking reply, the user is taken to a new page and cannot see posts on the same page. The reply section should be at the bottom of each page of the thread so that a user can reference current posts without needing two windows open.
* Each post should have a post number next to it which is linkable.
* Can't currently create indented MD lists
* Date/time needs to be added alongside each thread/post
* Need the option to reply to or quote previous posts.
* Subforum view should include page numbers
	* If a thread is 20 pages long, I should be able to click on page 20 without having to click the thread first, and then click page 20
* A toolbar with formatting options needs to be added (like the one on github)
* Its not possible to tag other users (even without notifications) or tag other posts

**Comment by bedeho** [comment]
Really great, wil try to include as many of these as we can, but some will be hard with our current infrastructure, such as the last one.

**Comment by bedeho** [comment]
Another issue pointed out by the council
https://testnet.joystream.org/#/proposals/4

**Comment by mochet** [comment]
A forum poll option would go a long way in starting to build and identify feedback on all sorts of issues from desired features to expected payouts for tasks/roles. This would be good to see in the forum module. It is also a fun feature that most platforms today have. This would be a non-binding poll which is only used to gather userbase feedback.

Poll features that would be good to see:
- Anonymous voting (switchable)
- Up to 10 options
- Single or multi-choice voting
- Blind voting + time to release results (ex. poll duration is 1 week, users can see how many users have voted, but not what they have voted for, after 1 week voting outcomes are shown)
- Eventual permission sets (ex. a poll can be set for current storage providers, council members, or all users)
- Eventual multiple question polls, that would allow the poll to tackle more than one singular issue

**Comment by bedeho** [comment]
We actually have a fully implemented version of the on the blockchain side forum which allows for polls, but not anonymous, only single question. It would however take time to update the web UI to work with it, but its coming! Will make a note of the request.

**Comment by bedeho** [comment]
This issue is superseded by https://github.com/Joystream/joystream/issues/558, which captures the only feasible improvements at this time.
