### ISSUE TITLE
Pioneer v1 UX: Council tab

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#468]
This section is so badly constructed its not even funny.

<img width="799" alt="Screenshot 2020-05-24 at 21 43 57" src="https://user-images.githubusercontent.com/437292/82763404-b7924e80-9e07-11ea-8e33-b3b08fefeb50.png">

A proper analysis is required to regoranize this, but one thing I suspect is that it may need to be broken up, for example by separating out all of the election related stuff entirely.

**Comment by mochet** [comment]
Currently a user creates a vote for a candidate and this is remembered by the browser, by hash but does not remember the candidate. When clicking "Reveal a vote" the user is then given a list of addresses, not users, of votes to reveal. If a user voted for many candidates they are somewhat required to note all data at the time of vote or have very good memory.

The UI will initially show who was voted for, but after creating another vote, this information goes away. Its a bit misleading as the user would be under the impression they do not need to keep this information for each vote.

**Comment by mochet** [comment]
Another feature that would greatly improve the council UX (indirectly) would be to have a poll option. This could maybe be a forum feature though.
This would be a key thing to have in order to effectively gather user/role feedback prior to people creating proposals and in order to prevent wildly out of place proposals from being created or voted in.

**Comment by bedeho** [comment]
See response here https://github.com/Joystream/joystream/issues/467#issuecomment-636092656.

**Comment by bedeho** [comment]
Out of scope for pioneer 1.
