### ISSUE TITLE
WIP: Fast Runtime Configuration

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4894]
WIP: Mokhtar will compelet spec., freakstatic executes

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1204404358291458/1205602859471050) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
The idea here was to introduce a runtime configuration that could be used to run a test/staging network for QA testing where runtime and storage based configuration would match the "production" runtime, with one key difference. The block production interval would be 1s instead of 6s, but any period lengths (defined in blocks) (provided they are not hard coded but actually use helper macros (days!, minutes!, hours!) for council/election periods, proposal voting/gracing periods etc would still be computed based on 6s blocks. This would mean time would be accelerated or "warped" . 

I've implemented this in https://github.com/Joystream/joystream/pull/4913

Note there is already a way to run a local development chain with production runtime settings if all that is needed is to verify/confirm constants are as expected by running node with the following arguments:

```
joystream-node --chain prod-test --tmp --alice --rpc-cors=all --pruning=archive
```
