### ISSUE TITLE
Fix liaison handling

### ISSUE THREAD

**Issue by jfinkhaeuser** [Joystream/joystream#49]
See https://github.com/Joystream/storage-node-joystream/issues/57

Rather than having a special hardcoded liaison value that is queried from the app, instead the function that picks the liaison should always return the same value.

**Comment by mnaamani** [comment]
What the app currently reads from chain  is the repo-id and api endpoint of our hosted storage node acting as the liason. Until we have storage node syncing and actor account id to api/url endpoint resolution working, we need to also fix the accountid of the assigned when creating the DataObject:

https://github.com/Joystream/substrate-runtime-joystream/blob/b2d907a2ac6fe0a9f701b2f3e78788c6cca27b43/src/storage/data_directory.rs#L175

This can be a new value `Option<AccountId>` which is used if it is not `None`, otherwise the default behavior of selecting an storage node.
This value would could be updated with sudo.

**Comment by jfinkhaeuser** [comment]
You mean either this value is used, or the random selection function in https://github.com/Joystream/substrate-runtime-joystream/blob/b2d907a2ac6fe0a9f701b2f3e78788c6cca27b43/src/storage/data_directory.rs#L175 ?
