### ISSUE TITLE
Colossus S3 api implementation

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#5139]
# Progress
- [x] edit controller logic to incorporate s3 upload and file fetching for user request on `filesApi.get`
- [x] document upload object flow
- [x] improve in memory cache logic for stored objects
- [x] improve custom multer Storage engine implementation in order to accomodate upload request
- [x] define Abstract class for generic cloud storage provider
- [x] Document new class hierarchy
- [x] Adapt synch flow for connection handler (est. 4hrs)
- [x] implement `ConnectionHandler` for the aws typescript api (est 4hrs)
  - [x]  if necessary augment `AbstractConnectionHandler` for getting a list of assets on the cloud bucket for local cache setup
- [x]  Add member to object cache for object that it is stored on remote bucket 10 min
- [x]  Files Api should detect whether file is on remote or simply return  30 min
- [x]  Accept data object should upload the file and add its location (either on local volume or remote to the cache) 2hrs
- [x]  Get file should get the file from remote using Abstract connection handler and pipe the stream to the request 2hrs
- [x]  Revert Changes on storage engine (only accepted objects should be added to the bucket) 2 min
- [x]  Refactor abstract connection handler using only async parts: 10 mins

**Comment by ignazio-bovo** [comment]
#### Considerations
- colossus writes its storage on two instances: `POST` request by the user and synching with other Nodes to allow replication
- colossus reads its storage only on `GET` request

#### handling a get request
- a file can either be on the local volume (legacy) or on s3: the logic should be to first to establish if the file is not on the local volume (and in the case use the legacy controller logic) otherwise fetch file from s3

**Comment by ignazio-bovo** [comment]
# Connection Handler hierarchy
``` mermaid
classDiagram
    class AbstractConnectionHandler {
        -isReady()*: boolean
        -connect()*: Promise<void>
        -doUploadFileToRemoteBucket(key: string, cb: (err: any, data: any) => void)*: void
        -doGetFileFromRemoteBucket(key: string, cb: (err: any, data: any) => void)*: void
        -doCheckFileOnRemoteBucket(key: string, cb: (err: any, data: any) => void)*: void
        +uploadFileToRemoteBucket(key: string, cb: (err: any, data: any) => void): void
        +uploadFileToRemoteBucketAsync(key: string): Promise<any>
        +getFileFromRemoteBucket(key: string, cb: (err: any, data: any) => void): void
        +getFileFromRemoteBucketAsync(key: string): Promise<any>
        +isFileOnRemoteBucket(key: string, cb: (err: any, data: any) => void): void
        +isFileOnRemoteBucketAsync(key: string): Promise<any>
    }
```
Concrete subclasses should implements only logic for setting up connection with cloud provider api (via `connect()` and perform necessary Upload / Get / Check action on remote assets). All other function are automatically provided once the abstract method have been implemented.
For AWS S3 I envision a concrete `AwsConnectionHandler` relying on the official aws javascript sdk.
Furthermore the concrete connection handler will be initialised at server startup and save in `res.local` (global state) for access.

# Mutter middleware during upload
I have added an implementation of the `StorageEngine` called `CloudStorage` that it is initialised during storage node startup. The initialisation takes care of setting up the above concrete instantiation of a `AbstractConnectionHandler` (from `res.local`) above the `CloudStorage` class depends on.

# Get file via `GET` endpoint
New (in-memory) cache setup is used to determine whether the asset is stored locally or on remote cloud. Following that `res.local.connectionHandler` is used with respective method in order to forward the request to the cloud provider.

# Modified cache
The previous cache simply kept track of `assetId -> referenceCount` for establishing how many request are accessing (read only) the resource at any given time.
I have added the following information to this cache `assetId -> DataObjectEntry`
```typescript
export type DataObjectEntry = {
  accepted: boolean
  isOnLocalVolume: boolean
  pinCount: DataObjectPinCount
}
```
adding information about whether the file is on the cloud and if the file has been accepted in the operator's bucket

```mermaid
classDiagram
    IDataObjectIdCache <|.. DataObjectIdCacheMap : implements
    LocalDataObjects -- IDataObjectIdCache : uses
    interface IDataObjectIdCache {
        +keys(): Promise<IterableIterator<DataObjectId>>
        +has(id: DataObjectId): boolean
        +get(id: DataObjectId): Promise<Maybe<DataObjectEntry>>
        +set(id: DataObjectId, entry: DataObjectEntry): Promise<void>
        +delete(id: DataObjectId): Promise<boolean>
        +init(): Promise<void>
        +isReady(): boolean
    }
    class LocalDataObjects {
        -idCache: IDataObjectIdCache
        +getDataObjectIDs(): Promise<string[]>
        +loadDataObjectIdCache(uploadDir: string): Promise<void>
        +addDataObjectIdToCache(dataObjectId: string, isOnLocalVolume: boolean): Promise<void>
        +pinDataObjectIdToCache(dataObjectId: string): Promise<void>
        +unpinDataObjectIdFromCache(dataObjectId: string): Promise<void>
        +deleteDataObjectIdFromCache(dataObjectId: string): void
        +getDataObjectIdFromCache(dataObjectId: string): Promise<{ dataObjectId: DataObjectId; dataObjectEntry: DataObjectEntry } | undefined>
        +isDataObjectIdAccepted(dataObjectId: string): Promise<boolean>
        +setDataObjectIdAccepted(dataObjectId: string): Promise<void>
        +isDataObjectIdInCache(dataObjectId: string): Promise<boolean>
        +getLocalFileNames(directory: string): Promise<string[]>
    }
```
