### ISSUE TITLE
Create a proposal: set a bugdet (mint capacity) for the working group.

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#628]
This should be a general proposal for the multiple working groups.

**Comment by bwhm** [comment]
I read this as all future working groups will have the same limits (but separate mints ofc). Although this would remove some complexity, I'm not sure if this is ideal, as the actual costs and scope of the roles are quite different.

Since it will only apply to the storage providers for this release regardless:
```
min: 0,
max: 3000000
```

They are currently getting ~700k/week, so this allows for some inflation and payraises :)
