### ISSUE TITLE
Create a proposal: set a reward for the leader.

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#629]
This should be a general proposal for the multiple working groups.

**Comment by bwhm** [comment]
The limits above are based on the following assumptions:
- although the lead can also be an acting storage provider, this specific role and compensation is for their efforts as group lead only
  - this means the lead is allowed to hire themselves (with the same memberId) as an operator
  - this role is independent from the other, with a different reward and stake, and can quit or be fired from one without it affecting the other role
- there is one storage provider mint, and the only spending from this is for rewards for the lead and the other storage providers
- the reward relationship is tied to a specific `leadId`, and is established when the proposal executes.


With this in mind, I would say we impose some rather basic limits:

```
amount_per_payout: minting::BalanceOf
min: 0,
max: 10000,
payout_interval: BlockNumber
min: 600,
max: 3600,
first_payout_after_reward_created: BlockNumber
min: 0,
max: 14400,
```

**Comment by bwhm** [comment]
As I don't know the exact workflow of this proposal, I can't set the rest.

Is this similar to `Hire Curator Lead`, which has three actions baked in to one proposal:
- No current lead occupying the role: set lead 
- There is already a lead: fire old lead
- There is already a lead: fire old lead, and set new lead

If so, I assume a specific member is proposed, with a role key and a, unlike the above, a stake?

In #496, it's suggested to make a proposal to slash the storage lead. Repeating my question there:
Will this proposal only deal with slashing the lead, so that slashing and firing are two separate proposals?
