### ISSUE TITLE
UI issue: Proposal not showing all votes

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#694]
Proposal:
https://testnet.joystream.org/#/proposals/12

Chain state data:
"votingResults":{"abstensions":0,"approvals":6,"rejections":0,"slashes":0

Issue:
Only 3/10 votes are showing on the UI. The proposal passed with 6 votes, but failed actual execution.

**Comment by Lezek123** [comment]
As far as I remember only the votes of the current council members are beeing fetched, which is probably what causes the votes of no longer active council members not to be included on this proposal page (and can also be observed for other old proposals)

The reason it was implemented this way was because we had no good way of dealing with the `proposalsEngine.voteExistsByProposalByVoter` double map (we needed both proposal id and member id to retrieve the vote value, so to avoid checking all 450 existing member ids, we just decided to execute a query for each active council member, but didn't predict it would cause an issue like this one).

Now that there exists a workaround soultion I implemented while working on the proposal discussion system, that allows us to fetch all values in the double map using only the first key (proposal id in this case) - this issue shouldn't be hard to fix.

**Comment by bedeho** [comment]
1. This seems to be a mistake on the runtime complicating things, as the memberid should not have been used to identify the voter, but instead the council member id, which is within a very small range.
2. All of this goes away with the query node, so do not overinvest in finding a perfect solution, just pick a workaround that fixes the obvious UI issue.

**Comment by Lezek123** [comment]
Should be fixed with: https://github.com/Joystream/joystream/pull/696
