### ISSUE TITLE
Forum posts timestamps inconsistency

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#705]
It looks like forum posts created before the data migration from the old chain use a different timestamp format than the new ones. I'm accessing the value using `thread.created_at.time` field.

For example, post with ID `187` has a timestamp of `1579636674` and post with ID `229` - `1590572352000`. These are posts from the same thread. The old one uses a timestamp expressed in seconds and the new one in milliseconds.

I'd expect timestamps to be consistent so they can be parsed by clients without any additional logic.

ping @mnaamani

**Comment by mnaamani** [comment]
Hey @kdembler well spotted. The `Moment` type is used both in the old chain and new chain to represent the timestamp as a `u64`. 

We used this [tool](https://github.com/Joystream/transform-encoded-forum-export) to export the old forum state -> serialzed to json -> then back to import [into the chain genesis](https://github.com/Joystream/joystream/blob/master/node/src/forum_config/from_serialized.rs)

So I'm wondering if we lost some resolution from `u64` to `53bit` json signed number representation or if substrate in fact back then did actually use seconds instead of milliseconds for timestamps.. let me check.

**Comment by mnaamani** [comment]
Older version of substrate when forum was introduced:

https://github.com/paritytech/substrate/blob/6dfc3e8b057bb00322136251a0f10305fbb1ad8f/srml/timestamp/src/lib.rs#L163

Current version of substrate we use:

https://github.com/paritytech/substrate/blob/c37bb08535c49a12320af7facfd555ce05cce2e8/srml/timestamp/src/lib.rs#L175

Newer version does indeed use milliseconds and not seconds.

So either we would have to transform all the values or have the parsing logic deal with each case individually. It's easy to spot the older posts and threads, they have a `created_at.block` field as 1 (genesis)

**Comment by kdembler** [comment]
It's hard for me to understand how troublesome such transformation would be, although I guess it's not trivial. However, my two cents are, while parsing this isn't that problematic, if left like it is, this will be a debt that will need to be carried for a long time and every new client built would need to take this into account when parsing.

Also, are there some other `Moment` timestamps that can also be affected by this?

**Comment by bedeho** [comment]
- If this is soluble at the client layer, then lets do that for now.
- We will deploy the 2.0 forum soon, and here all timestamps will be removed from storage state, so this particular issue will go away on its own.

**Comment by mnaamani** [comment]
> Also, are there some other `Moment` timestamps that can also be affected by this?

I think its only the forum posts and threads. 

For initial members that were imported at genesis, we (me) mistakenly tried to set the timestamp at genesis, later realizing its value was zero (because it is set by validators when blocks are produced). 

So some members have the `registered_at_time` of their [Profile](https://github.com/Joystream/joystream/blob/3868fe0ba2d77d2c87fbfbb9c3a518e95ac387f1/runtime-modules/membership/src/members.rs#L90) set to 0 which is interpreted as `1/1/1970, 2:00:00 AM` 

![Screen Shot 2020-06-16 at 3 32 49 PM](https://user-images.githubusercontent.com/1621012/84774546-07bb9580-afef-11ea-8e20-bbbbd9c3436e.png)
