### ISSUE TITLE
Define & implement proposals parameters.

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/joystream#765]
Proposals
- terminate_role 
- decrease_stake
- fill_opening
- accept_applications
- begin_applicant_review
- add_opening
- slash_stake
- set_new_reward_amount
- set_mint_capacity

We need to provide values for the ProposalParameters for each proposal.

```
/// Proposal parameters required to manage proposal risk.
pub struct ProposalParameters<BlockNumber, Balance> {
    /// During this period, votes can be accepted
    pub voting_period: BlockNumber,

    /// A pause before execution of the approved proposal. Zero means approved proposal would be
    /// executed immediately.
    pub grace_period: BlockNumber,

    /// Quorum percentage of approving voters required to pass the proposal.
    pub approval_quorum_percentage: u32,

    /// Approval votes percentage threshold to pass the proposal.
    pub approval_threshold_percentage: u32,

    /// Quorum percentage of voters required to slash the proposal.
    pub slashing_quorum_percentage: u32,

    /// Slashing votes percentage threshold to slash the proposal.
    pub slashing_threshold_percentage: u32,

    /// Proposal stake
    pub required_stake: Option<Balance>,
}
```

**Comment by bwhm** [comment]
My suggestions below. I've copied the values for "Set Mint Capacity" for consistency, and otherwise tried to set somewhat reasonable values. 

I'm further assuming that neither "Accept Applications" or "Begin Applicant Review" would really be needed, but I guess it's better to have them than not. If we want to remove some for simplicity though, I'd say to cut them.

Finally, I'm assuming the lead hiring flow is implemented in such a way that if a lead exists when creating the "Add Opening" proposal, the whole flow would work fine until execution of "Fill Opening". By that I mean a user could create the "Add Opening", before both making a proposal to "Terminate Role", or execution of said proposal (assuming approval).

The main parameters I'm struggling to decide on, is the grace period for the entire hire lead flow in general, and particularly the "Begin Applicant Review" proposal. On one hand, I don't think it makes sense for the council to be able to "rush" this stage, leaving potential applicants out, but on the other hand, it's not ideal to wait unnecessarily long in hiring a (new) lead.
@bedeho?

## Add Opening

| Proposal Parameters             | Value        |
|:-------------------------------:|:------------:|
|`voting_period`                  | 72000        |
|`grace_period`                   | 0            |
|`approval_quorum_percentage`     | 60%          |
|`approval_threshold_percentage`  | 80%          |
|`slashing_quorum_percentage`     | 60%          |
|`slashing_threshold_percentage`  | 80%          |
|`required_stake`                 | 100000       |

## Accept Applications

| Proposal Parameters             | Value        |
|:-------------------------------:|:------------:|
|`voting_period`                  | 43200        |
|`grace_period`                   |  0         |
|`approval_quorum_percentage`     | 60%          |
|`approval_threshold_percentage`  | 75%          |
|`slashing_quorum_percentage`     | 60%          |
|`slashing_threshold_percentage`  | 80%          |
|`required_stake`                 | 25000        |

## Begin Applicant Review

| Proposal Parameters             | Value        |
|:-------------------------------:|:------------:|
|`voting_period`                  | 43200        |
|`grace_period`                   | 14400        |
|`approval_quorum_percentage`     | 60%          |
|`approval_threshold_percentage`  | 75%          |
|`slashing_quorum_percentage`     | 60%          |
|`slashing_threshold_percentage`  | 80%          |
|`required_stake`                 | 25000        |

## Fill Opening

| Proposal Parameters             | Value        |
|:-------------------------------:|:------------:|
|`voting_period`                  | 72000        |
|`grace_period`                   | 0            |
|`approval_quorum_percentage`     | 66%          |
|`approval_threshold_percentage`  | 80%          |
|`slashing_quorum_percentage`     | 60%          |
|`slashing_threshold_percentage`  | 80%          |
|`required_stake`                 | 100000       |

## Terminate Role

| Proposal Parameters             | Value        |
|:-------------------------------:|:------------:|
|`voting_period`                  | 72000        |
|`grace_period`                   | 0            |
|`approval_quorum_percentage`     | 66%          |
|`approval_threshold_percentage`  | 80%          |
|`slashing_quorum_percentage`     | 60%          |
|`slashing_threshold_percentage`  | 80%          |
|`required_stake`                 | 100000       |

## Set New Reward Amount

| Proposal Parameters             | Value        |
|:-------------------------------:|:------------:|
|`voting_period`                  | 43200        |
|`grace_period`                   | 0            |
|`approval_quorum_percentage`     | 60%          |
|`approval_threshold_percentage`  | 75%          |
|`slashing_quorum_percentage`     | 60%          |
|`slashing_threshold_percentage`  | 80%          |
|`required_stake`                 | 50000        |

## Slash Stake

| Proposal Parameters             | Value        |
|:-------------------------------:|:------------:|
|`voting_period`                  | 43200        |
|`grace_period`                   | 0            |
|`approval_quorum_percentage`     | 60%          |
|`approval_threshold_percentage`  | 75%          |
|`slashing_quorum_percentage`     | 60%          |
|`slashing_threshold_percentage`  | 80%          |
|`required_stake`                 | 50000        |

## Decrease Stake

| Proposal Parameters             | Value        |
|:-------------------------------:|:------------:|
|`voting_period`                  | 43200        |
|`grace_period`                   | 0            |
|`approval_quorum_percentage`     | 60%          |
|`approval_threshold_percentage`  | 75%          |
|`slashing_quorum_percentage`     | 60%          |
|`slashing_threshold_percentage`  | 80%          |
|`required_stake`                 | 50000        |

## Set Mint Capacity

| Proposal Parameters             | Value        |
|:-------------------------------:|:------------:|
|`voting_period`                  | 43200        |
|`grace_period`                   | 0            |
|`approval_quorum_percentage`     | 60%          |
|`approval_threshold_percentage`  | 75%          |
|`slashing_quorum_percentage`     | 60%          |
|`slashing_threshold_percentage`  | 80%          |
|`required_stake`                 | 50000        |
