### ISSUE TITLE
User stories for Rome

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#78]
# Overview
Each lead must provide a set of draft user stories for the items listed below. Submit them as comments below before 10:00GMT+2 on 16.07.19, so they can be added to the agenda for `Rome User Stories Meeting`.
The meeting will be spent evaluating them, so they can be included in the release plan. 

I propose keeping the user stories FOR the `conductor`, `root` `forum sudo` etc. outside the scope of this meeting, or at least separated out to avoid the meeting to drag out too long.

quality > quantity.

## Apollo 
**Responsible:** @bedeho 
Keywords:
Requirements, signup for role, leave role.

## Colossus
**Responsible:** @mnaamani 
Keywords:
Requirements, signup for role, leave role.

## Dynamic Content Directory
**Responsible:** @mnaamani 
Keywords:
Selection, migration, propose new schemas.

## Community Fund Proposal System
**Responsible:** @bwhm  
Keywords:
Application process, voting process.
Forum based -> Proposal based.

## Pioneer
**Responsible:** @siman 
I suspect it will be difficult for alex to write these before having seen the other user stories and possibly even specs. I propose we either let alex pick what applies to him, and let him modify/present them at the standup the following day.

---

Feel free to comment and edit.

**Comment by bwhm** [comment]
## Community Fund Proposal System

#### As a platform member and stakeholder, I want
- a community fund of real money.
- to be able to make proposals and apply for grants.
- to be able to to competitions, and get paid to arrange them.
- to be able to participate in competitions and win real money.
- to be able to propose increasing participation payouts.
- a forum category to discuss and evaluate proposals.
- insight on what Council Members thinks about proposals.

#### As a Council Member candidate, I want
- to communicate to stakeholders how I would allocate the resources as part of my campaign.
- show my constituency that I want to support their cause as part of my campaign.
- show that I can make good proposals that would help build the community.
- show that I can evaluate, improve and find flaws in other proposals.

#### As a Council Member, I want
- all of the above.
- the ability to vote and allocate the funds.

**Comment by bedeho** [comment]
I think having Pioneer as its own section is a bit misleading because many of the user stories in the other sections are in pioneer. I think user stories must be tied to functionality or behavior, not end products.

**Comment by mnaamani** [comment]
## Content Directory
These stories describe functionality of a general purpose Versioned Object Database system upon which the content directory for the platform will be constructed.

As system sudo I can:
- create a new `class group` *1
- assign a `class group` sudo
- have same permissions as class group sudo

As `class group` sudo I can:
- create a new Class
- create a new Entity of an existing Class in my group
- create a new Schema for a Class in my group, supporting use of an Object Property type that can map to a DataObjectID, of a specific DataObjectFamily from the Data Directory, using a simple text format to describe the schema.
- create a new object of a specific schema for an existing Entity in my class group.
- update the object properties of any object in my class group

Any user of the platform can:
- get a list of all classes, and entities
- for each class get all its entities
- for each entity get all versions of its object representation

*1 - A `class group` is a logical grouping of Classes. It allows for segmenting the database and assigning different sudo accounts for different groups. A class group sudo can only create new classes and entities, under their group.

Assume Database has following structure:
Classes: `["Podcast", "PodcastTheme", "Episode", "Person"]`
Schemas: 
```
Podcast {
  name: varchar(30),
  host: Internal(Person),
  // themes: Array(PodcastTheme) // array propertytype is not yet in spec
  theme: PodcastCategory // might be limiting if a show fits in multiple categories
}

PodcastTheme {
  name: varchar(30),
}

Person {
  memberId: Option<External("Membership", 0)>,
  email: varchar(150),
}

Episode {
   podcast: Internal(Podcast),
   title: varchar(50),
   guest: Internal(Person), // Array ? guests
   track: External("DataDirectory", DataObjectFamilyId = 0)
}
```

In Pioneer a user should be able to:
- browse list of `Podcast`s, by `Theme` or show host, and for each podcast get a list of `Episode`s
- list podcast by show host
- find all episodes (from different shows) where a guest appeared


Instead of Arrays (eg. to add all guests that appeared on a show), we can have create a Class: 
```
PodcastGuestAppearance {
  episode: Internal(Episode),
  guest: Internal(Person)
}
```

**Comment by bedeho** [comment]
Oh I really like the `PodcastGuestAppearance` thing, that would be so cool. It weould be great even for normal videoes. Youtube does not formalise the concept of who is in what videoes, so all discovery and search just keys off titles and keywords, this type of explicit encoding can be super powerful and open up lots of new use cases!

**Comment by mnaamani** [comment]
## Colossus

As a node operator I should be able to:
- (Stake) Configure and enter storage role entirely from the command line, in an interactive process, where only essential secret keys are required on the node running the storage node software.
- (Unstake) leave the role easily without loosing access to staked (stash) keys
- Re-enter the role after unstaking without overwriting old staking keys
- Get status of my node:
  - Sync status, IPNS publishing status. Total storage consumed...
- Get usage stats:
   - number of objects served/uploaded, total data transferred
- Check if there is a version update available
- Enter a test mode - non operational mode for testing setup and configuration
- Configure a remote IPFS node to use
- Configure a remote endpoint as joystream full node
- Gracefully shutdown node

The node itself should:
- Not enter operational status until chain is fully synced
- Synchronize data objects over IPFS from other storage providers
- Provide a REST API for receiving new data objects from publishers, and accepting transfers to distributors nodes
- Provide a REST API for service resolution

**Comment by bedeho** [comment]
NB1: provider refers to either storage provider or distributor.

NB2: These stories are kind of hand wavy. Many of the stories may be better suited off chain, e.g. coordinated through a server run by conductor. But it remains to be seen.

# Provider

**As a prospective provider I want to**

- see terms associated with existing providers roles
- see terms associated with open positions for new roles
- apply to an open position with one click
- one click download each auto generated key (stash, controller, session) for each role applied to
- get notified if accepted into a position
- see list of all positions I have occupied now and prior, and corresponding payouts, and circumstances of leaving.
- get notified if slashed
- get notified if evicted
- leave a role
- start apollo with given keys
- stop apollo
- see apollo session status of node
- see apollo recent usage log

# (Jsgenesis) conductor

**As a conductor I want to**

- add an open position with given terms
- close an open position
- slash a provider from a position
- evict a provider from a position
- get in touch with a provider out of band
- add obligation to provider
- remove obligation from provider
- quickly determine if a new accepted provider is correctly configured

**Comment by bedeho** [comment]
Done in Rome [release plan](https://github.com/Joystream/joystream/tree/master/testnets/rome#release-plan).
