### ISSUE TITLE
Idea: Runtime Constitution

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#799]
# Background

https://github.com/Joystream/joystream/issues/784

# Proposal

- A new module, called `constitution`, which just holds a simple singular hash in storage, which can be updated via root origin call that computes a new hash for a new text blob, and emits an event. That's it.
- A new proposal that allows the council to set a new constitution text.
- A query node schema which holds the history of all constitutional amendments, and the associated proposal.
- In pioneer (UI) one conveniently just show the diff between the new and the old text.

**Comment by mochet** [comment]
@bedeho Was going to create a new issue, but seems redundant. Could this also be used for managing or developing something like a council budget document?
I could see other roles benefiting from a similar system, like the membership screener having a clear, agreed upon document which can be edited at times which new users can see regarding rules and terms specific to that role?

I guess its also a question of how documents will work on-chain, but I can imagine a use for each working group being able to have a collaborative document rather than relying on just the forum to hold that information. If they were able to use a similar system to this, then it would probably mean that roles and the rules that define them can more organically evolve over time.

This would also mean more clearly defined roles, using the membership screener as an example, you would be able to have some consistent values written down rather than having a random new group lead come along and change the value for new members dramatically? There would be no system limitation to make payments out of range, but a sincere WG leader would ideally edit their role document via proposal before just enforcing arbitrary numbers?

edit - each document could have a forum thread for discussion, but the document itself could be embedded on the pages for each role and also linked centrally in some place, allowing users to quickly access the documents which define what the expectations are for each role.

**Comment by bedeho** [comment]
Just to make this super-specific: what you are saying is that you would like some other sort of public text which explains the rights and obligations of each working lead and that this text can only be amended by the council. This text would be analogous to some sort of directive?

**Comment by mochet** [comment]
Yes, a good example of how this is currently approached is with the current set of curator rules: https://testnet.joystream.org/#/forum/threads/53
These should really be done in a "binding" way, where the main rules are set in stone. Otherwise I could foresee a situation where new role leads join the platform and try to use their own set of rules which are wildly inconsistent with what has already been established. I think it would make sense for these "binding" rules to be governed by the council in order to try and ensure there is some level of consistency.

For easy readability each working group would have their own document which is centrally linked from the constitution, the easiest way to describe it would be a constitution wiki. Perhaps it is just one document and specific sections of the document are shown on the working group page. You could just have everything be a part of one central document, but I think it makes sense to have a separate document for each role, particularly concerning educating and informing all users in an easy way--when there are (I think) 11 roles, an interested user would probably not want to read through the information concerning all other roles.

I think separate documents would also help to avoid a situation where dozens of changes applicable to several roles are attempted to be pushed through in a single proposal, by having some separation it would help to ensure there are checks + balances.

An example would be for the Storage role, as a new user interested in the role, I should be able to visit the Storage page and see an embedded set of rules that govern the role, including information as how much downtime I would be allowed, how old my account has to be (in the case of avoiding Sybil attacks) and key rules and expectations. This document would also perhaps outline what is expected of the lead for this working group. In this way, users, providers, leads and council members have a clear set of rules applicable to each role on the platform with a clear process for adjusting them in place.

This wouldn't be used so much for documentation purposes, although a different on-chain wiki for that purpose would be very nice to have, but more intended as a binding set of rules that each role is expected to abide by.

If this proposal/constitution system also had a way to create new documents then it would allow for the council and userbase to create new collaborative documents for other purposes, but I'm not sure what the technical difficulties of having a system like that would be.

**Comment by bedeho** [comment]
Excellent, thanks for the clarification.

The problem with having genuinely separate documents that require distinct proposals to amend is that there may come a time where you want to change the different policies in concert. This would require multiple proposals, each of which can succeed or fail independently, leading to an incoherent (temporary?) outcome. Unless it's important to have different quorum requirements for each document, then I am not sure this is worth it. Keep in mind that having a single document does not prevent everyone from seeing perfectly well exactly where it is going to be changed, and would allow people to reject changesets that are too broad.

**Comment by mochet** [comment]
Its probably like the idea of separate mints, where some level of separation may be good but too much separation would introduce its own set of difficulties and challenges. Perhaps just a council constitution, working groups constitution and content rules constitution would be enough separation, as I could see the council constitution having its own distinct value from the other areas (as it basically influences everything). I could imagine that with enough time running on mainnet, that changes to the council rules/structure should require quite a significant quorum, whereas WG rules may not attract quite as much traction.

As a separate issue, the visual display of the appropriate areas of the constitution on each WG page within the UI is something I do feel is very important, since it signals a high level of transparency to everyone involved. That doesn't mean actual separate documents though, just that the relevant part of the constitution is visually shown where it is appropriate and easily links back to the main document.

**Comment by bedeho** [comment]
> As a separate issue, the visual display of the appropriate areas of the constitution on each WG page within the UI is something I do feel is very important, since it signals a high level of transparency to everyone involved. That doesn't mean actual separate documents though, just that the relevant part of the constitution is visually shown where it is appropriate and easily links back to the main document.

Exactly right.

**Comment by bedeho** [comment]
Implemented in Olympia.
