### ISSUE TITLE
Actors Module Work Log

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#89]
# Background

I have been working on the refactoring of the Actors module spec for Rome on and off for 2 weeks or so, and I want to start logging progress for the sake of clarity and review (which need not be in the log itself).

**Note: This is meant to be a low effort log, so it will be sloppy, otherwise maintaining will not feasible.**

**Comment by bedeho** [comment]
# 1

## Where I have been

I started out trying to build everything into the storage module, and soon found that it would be repeated lots of concepts which would have to be repeated in other subsystems (e.g. content directory, communication, builders, etc.) later. As a result I tried to identify a core set of features which could work across all, or many, of them. I also aspired to have the module allow for very light weight creation of ad-hoc roles, not necessarily with any other on-chain privilidge beyond the staking and rewards in the actors module. The reson for this was because it seemed like we would want this sort of light weight organiztion to be easy to setup for unanticipated off-chain activities, without having to do a runtime upgrade.

## Where I am going

The result of all of these aspirations was that even this Actors module starting becoming quite bloated, and it became hard to identiy the right set of abstractions that were truly universal. The next step was therefore to break up this module in a set of lower level modules.

Currently I am trying to design something which would look something like this

![staking_interplay](https://user-images.githubusercontent.com/437292/62532316-639c8600-b844-11e9-98a6-ccb45bc8ec11.png)

A quick summary goes as follows.

1. *roles-staking* is a low level staking module, which has not extrinsics, and only handles staking and slashing in a flexible way, for example so as to support things like contestable slashes, with appeals and arbitraraton, as something one can layer on top.

2. *role-rewards* is a low level rewards module, which as not extrinsics, which only handles timely minting of assets, with flexibility around budgets, pausing, etc.

3. *generic-roles* is a hypthetical high level module which would build in a permission system, organizational hierarchy, where actors can hire, fire, slash, etc. This would be to model this light weight organizational flexibility without runtime upgrades.

4. Two example subsystems (forum, sdn = storage & distribution network), are shown as using the two key role modules above. They have an orchastrator module which exposes a use case specific flow around adding/removing participants, as this cannot be generalized as of now, and layer the  appropriate permisssion on top of the roles modules. By moving the permissions and public interface out of the core module, like _forum_ and _snd_, it presumably will allow them to be maximally reusable in other runtimes. The orchestrator also holds the mapping between the subsystem specific actor identifiers and the underlying membership identifier.

## Key unresolved questions

1. For any of the actual orchestrators going to be shipped for Rome, should the process for announincing and adding new roles be on-chain or not?

2. Should _forum_ and _snd_ be (rewritten), to not have any extrinsics, only public methods, thereby remove the mutual dependency through the permissions interface?

**Comment by mnaamani** [comment]
This is a good approach. The pattern is of an orchestrator is very similar to what I described in the  permissions module as the "ProxyModule". 

In your proposed diagram if we can model the permissions for the forum and snd with the graph proposed in the ACM module, those two permissions modules can also be extracted out.

Yes I think both forum and snd should not be aware of a "permissions" system

**Comment by mnaamani** [comment]
So I can understand the model and key design choices here, which is giving ample opportunity for the governance system to be able to slash an actor before they totally unstake. But I can't help but feel that it would be sufficient to just make the unstaking period long enough (propotional to amount at stake) to allow enough time for the higher order processes to take decisions on slashing. (so there is a race with the "unstaking clock" but it is fair to both the actor and the governance system) 

Of course the problem with this simple approach is in the case when a slashing proposal comes in just before the end of the unstaking period. But then again if the governance process doesn't find a reason to slash an actor until the last minute then the problem maybe is in the governance process?

`Option<FnMut>` callbacks : I don't think its possible to store these in state storage. The `OnUnstaked` and `OnSlashed` types set in the module's config Trait will be sufficient to make callbacks

The `StakingStatus::Staked::lock_id` isn't strictly required because we don't need a unique value for each lock. A single global constant value for all locks created by the role staking module is sufficient.

I think for both the `adjust_stake` and `reduce_stake` operations it is simpler to allow the actor to make the balance transfers (before adding stake and after reducing stake).

**Comment by mnaamani** [comment]
Alternatively for the callbacks if we something more dynamic that can be set when creating the role, then we can use the `Call` type which implements the Dispatchable trait used to represent a "Proposal"  in the democracy and sudo modules.

```
trait Trait {
   type Proposal: Parameter + Dispatchable<Origin=Self::Origin>;
}
```
https://github.com/paritytech/substrate/blob/v1.0/srml/support/src/dispatch.rs#L39

`type Proposal = Call;   // when configuring the runtime` 

The function and its arguments can be encoded in extrinsics and storage. In extrinsics as a parameter it is of type `Box<Trait::Proposal>`.

Example usage in democracy module [1](https://github.com/paritytech/substrate/blob/v1.0/srml/democracy/src/lib.rs#L229) [2](https://github.com/paritytech/substrate/blob/v1.0/srml/democracy/src/lib.rs#L852)
.. in the [sudo module](https://github.com/paritytech/substrate/blob/v1.0/srml/sudo/src/lib.rs#L153)

**Comment by bedeho** [comment]
Lifting out spec here https://github.com/Joystream/joystream/issues/109
