### ISSUE TITLE
Validating Node stability issues

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#915]
Validators seem to have an issue where they periodically drop out of being a validator and the node hasn't crashed.
I'm not sure of the exact situation when this happens, but it often results in the validators having to reclick the validate button in the UI. It seems that when this does happen at least a few validators drop out at the same time.

**Comment by bedeho** [comment]
This doesn't sound like its related to anything we have built, may be connectivity issues with certain operators, or it may be a Substrate issue. Let's keep track of this though. We are migrating to a new version of Substrate soon, perhaps that clears it up.

**Comment by fierydev1** [comment]
So I have total 2 validators running
As you mentioned they were stopped
Although, VPS shows them running
Due to slashing their stash account balance went to 0
Upon transferring coins to stash, slashing was automatically deducted
A total of 192k tJoy was slashed for them combined 😂
I was slashed sometime back on 8th July as well
Not sure how much then
Didn't calculate
Without traditional explorer, not sure how to check easily/comfortably
Also, economically, it's not viable to run a validator as I'll be burning up all my tJoy balance
What do you guys think?

**Comment by bedeho** [comment]
Thanks for the excellent feedback. 
1) Agree, we badly need a better surfacing of such historical events, and its coming, unfortunately, it will take some time, because it's being bundled with a new version of our Pioneer app, which will take time. I will keep in mind whether we could deploy some halfway solution before that time.
2) I think a new proposal was just suggested to address this, at least temporarily: https://testnet.joystream.org/#/proposals/32
